### ISSUE TITLE
I can configure form fields

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#100]
AT:
* supported for start events and user tasks
* it is possible to provide multiple form fields
* it is possible to add form fields
* Supported types:
   * String
   * Long
   * Boolean
   * Date 
* I can provide
    * id (variable name)
    * type (string only)
    * label
    * default value

**Comment by meyerdan** [comment]
Support for enums id follow up issue

**Comment by meyerdan** [comment]
See also: https://docs.camunda.org/manual/7.4/user-guide/task-forms/#form-fields

**Comment by polenz** [comment]
all stuff implemented on branch: https://github.com/bpmn-io/bpmn-js-properties-panel/commits/form-fields-100
