### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#1018]
### Describe the Bug

As discussed in https://github.com/camunda/camunda-modeler/issues/3991 our goal is to make the error messages more forgiving, going from "general error (outside of editor)" to "local error (inside editor)".

We seem to have missed this, as the core editor still reports a very specific message that does not hint on the type of expected expression (FEEL expression), outside of editor:

![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/58601/be2b6886-15ae-4d80-b6d4-042e3972df77)

### Steps to Reproduce

1. type invalid FEEL expression
2. see misleading (and very detailed) error message

### Expected Behavior

We show `Unparseable FEEL expression` as an indicator to users what the input should be.

### Environment

- Host (Browser/Node version), if applicable: Any
- OS: Linux
- Library version: v5.9.0

**Comment by marstamm** [comment]
Whoops, that slipped through since we always use the properties panel with linting in our products. 
I'll adjust the labels we use for Properties panel only usage and with linting. I'll create a PR so the FEEL editor reports the same error as the linting lib.
