### ISSUE TITLE
Configuration of environment variables with subsequent selection

### ISSUE THREAD

**Issue by Happy-Child** [bpmn-io/bpmn-js-properties-panel#1034]
Hello.

I have a question and a suggestion for improvement. I have to ask the question here because there is no response from https://forum.bpmn.io/.

The kogito bpmn editor has a convenient feature for environment variables (screenshot below).
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/40471724/9a6a2d0a-2c59-4edf-8980-b7c9c03b6807)

You can create them in "Process Data" and then select values from the already formed list of environment variables in the Data I/O modal window (screenshot below).
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/40471724/b5566c1c-e868-404b-9502-f06935b67e46)

Suggestions for improvement:
Can the camunda bpmn editor implement a similar feature? Add a tab for creating a list of environment variables on the Process Configuration panel. Then these values can be selected as "Variable assignment value" in the Inputs & Outputs tabs.

Questions:
1. Please tell me if we want to implement this functionality ourselves, will it only affect this repository "bpmn-js-properties-panel"?
If not, please let me know which other modules might be affected. I am currently using the following configuration (screenshot below).
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/40471724/a16bacd4-36ba-4b1d-be12-58d9b1c44683)

2. And is such an implementation possible in principle? Or is it not worth spending time studying the source code?

Thank you!

**Comment by nikku** [comment]
@Happy-Child in Camunda 8 we have [data handling](https://docs.camunda.io/docs/next/components/modeler/data-handling/) to serve a similar purpose, working via editor auto-completion, built of [this extension](https://github.com/camunda/example-data-properties-provider).

Within Camunda 7 we do not plan to work with that, but surely there is ways for you to extend the existing properties panel tooling.
