### ISSUE TITLE
Panel headers and Zeebe's tab labels translations are missing

### ISSUE THREAD

**Issue by Rastuharem** [bpmn-io/bpmn-js-properties-panel#1044]
### Describe the Bug

In current state, exists [translation](https://github.com/bpmn-io/bpmn-js-examples/tree/main/i18n ) functionality, which works only on some of the tab's labels (#1014).
In header's case, no header can be translated.  

### Steps to Reproduce

1.) Create custom translate function, which translates any word into some symbol:
```js
export default {
  translate: [
    'value',
    function customTranslate(template, replacements) {
      return '✔';
    },
  ],
};
```

2.) Apply it to bpmn modeler
```js
import {
  BpmnPropertiesPanelModule,
  BpmnPropertiesProviderModule,
  ZeebePropertiesProviderModule,
} from 'bpmn-js-properties-panel';

import testTranslation from '@/some/path/toFile';
...
const options = {
  propertiesPanel: { parent: '#js-properties-panel' },
  additionalModules: [
    BpmnPropertiesPanelModule,
    BpmnPropertiesProviderModule,
    ZeebePropertiesProviderModule,

    testTranslation,
  ],
};

const bpmnViewer = new BpmnModeler(options);
```

3.) Check result:
<img width="569" alt="image" src="https://github.com/bpmn-io/bpmn-js-properties-panel/assets/95254106/e365716a-7309-4d89-b2df-1d9b64b3c933">

We can see that headers and some tabs are not translated.
(It seems that all Zeebe's tabs are not translated)

### Expected Behavior

All headers and tab's labels should be translated

### Environment

- Host: Node v.20.11.1
- OS: Windows 11
- Library version: 5.14.0

**Comment by Rastuharem** [comment]
I would like to try fix this issue

**Comment by barmac** [comment]
Thanks for raising this. We are happy to accept your contribution fixing this.
