### ISSUE TITLE
`create-react-app` fails to bundle properties panel - `minDash.isArray is not a function`

### ISSUE THREAD

**Issue by BehzadBakhshayesh** [bpmn-io/bpmn-js-properties-panel#1058]
### Bug Description

Hello. I created a React component using the "bpmn-js", "@bpmn-io/properties-panel", and "bpmn-js-properties-panel" packages. An error emerges when utilizing the CamundaPlatformPropertiesProviderModule, displaying: TypeError: minDash.isArray is not a function. It seems that this issue stems from the min-dash version, and updating it should resolve the error.

```json
"dependencies": {
  "@bpmn-io/properties-panel": "^3.21.0",
  "bpmn-js": "^17.8.2",
  "bpmn-js-properties-panel": "^5.17.1",
  "min-dash": "^4.2.1",
  "react": "^18.3.1",
  "react-dom": "^18.3.1"
},
```

### Reproduction Steps

I'm using the following code and try to bundle the application using `create-react-app`:

```javascript
import BpmnModeler from "bpmn-js/lib/Modeler";
import {
  BpmnPropertiesPanelModule,
  BpmnPropertiesProviderModule,
  CamundaPlatformPropertiesProviderModule
} from "bpmn-js-properties-panel";
import "bpmn-js/dist/assets/diagram-js.css";
import "bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css";
import "@bpmn-io/properties-panel/assets/properties-panel.css";
```

```javascript
bpmnModeler.current = new BpmnModeler({
  container: canvasRef.current,
  propertiesPanel: {
    parent: propertiesPanelRef.current
  },
  additionalModules: [
    BpmnPropertiesPanelModule,
    BpmnPropertiesProviderModule,
    CamundaPlatformPropertiesProviderModule
  ]
});
```

Then reload the application.

### Expected Outcome

Kindly address this issue.

### Environment

- Host: Browser
- Browser: Google Chrome v125
- OS: Windows 10
- Library Version: 2.0.0

**Comment by barmac** [comment]
This looks more like a bundler issue. Can you reproduce this problem in a [codesandbox](https://codesandbox.io/)?

**Comment by BehzadBakhshayesh** [comment]
[codesandbox](https://codesandbox.io/p/sandbox/serene-flower-c5rgl4?file=%2Fpackage.json%3A12%2C25)
When running the code on codesandbox, I observed that codesandbox had installed "bpmn-js": "17.8.1" without any errors. However, I had specified "bpmn-js": "^17.8.2" in my setup. The issue actually arises with version 17.8.2.

**Comment by BehzadBakhshayesh** [comment]
Error doesn't appear on [codesandbox](https://codesandbox.io/p/sandbox/serene-flower-c5rgl4?file=%2Fsrc%2FApp.js%3A93%2C1) but is present in my setup. Could you please review my [repository](https://github.com/BehzadBakhshayesh/React-bpmnjs-properties-panel)?

**Comment by nikku** [comment]
@BehzadBakhshayesh Please ensure you also recognize JavaScript files with an `mjs` extension.

**Comment by nikku** [comment]
As you're using just plain `create-react-app` this _should_ work out of the box.

**Comment by barmac** [comment]
I run your code locally, and the error is thrown from the `@bpmn-io/extract-process-variables` module. For a reason still unknown to me, the require `var minDash = require('min-dash');` is resolved as a path to a file:
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/28307541/f0d30b15-dfed-45a2-b9c7-36907c38d7ee)

**Comment by nikku** [comment]
@barmac `cjs` is not properly recognized as a JS asset, hence the static resolution to a file, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1058#issuecomment-2176142055.

I believe this is tracked upstream via https://github.com/facebook/create-react-app/issues/12700.

@BehzadBakhshayesh There is nothing we can do to remedy this. `create-react-app` simply has to [fix things](https://github.com/facebook/create-react-app/issues/12700)

**Comment by BehzadBakhshayesh** [comment]
@nikku @barmac Thank you.
