### ISSUE TITLE
Property panel is not visible

### ISSUE THREAD

**Issue by SumuduRasnayake** [bpmn-io/bpmn-js-properties-panel#1085]
### Describe the Bug

We have successfully integrated 'bpmn-js-properties-panel' with the Camunda 8 modeler in Angular 9.

However, after upgrading to Angular 17, we are facing an issue with loading the properties panel. Specifically, we are unable to locate the modules "BpmnPropertiesPanelModule" and "BpmnPropertiesProviderModule" as referenced in the library.

![image](https://github.com/user-attachments/assets/8b068945-e7ee-4a91-bf14-81d816a74d31)

### Steps to Reproduce

1. Create an angular 17 project.
2. Implement camunda and bpmn-js-properties-panel using npm.
3. Properties panel is not loaded.

### Expected Behavior

Properties panel should be worked properly with angular 17 as below.

![image](https://github.com/user-attachments/assets/f607e068-a527-49fa-bfdd-eb4421195925)

### Environment

- Host: [Chrome 129, Node 18 LTS]
- OS: [Windows 11]
- Library version: [
     pmn-js-properties-panel@5.25.0,
     @bpmn-io/properties-panel@3.24.1,
     bpmn-js@17.11.1,
     camunda-bpmn-js@4.5.0,
     camunda-bpmn-moddle@7.0.1,
]

**Comment by jarekdanielak** [comment]
There isn't enough information for us to reproduce the issue. Can you perhaps share an example of a repo where this is happening?

**Comment by SumuduRasnayake** [comment]
I have tried with this example 'https://github.com/SumuduRasnayake/camunda-17'.
Could you please provide if there are any alternative modules or methods, we should consider resolving this issue.

**Comment by jarekdanielak** [comment]
I run the project from your repo and the properties panel worked just fine. Only thing, you forgot to add [the styling](https://github.com/bpmn-io/bpmn-js-properties-panel?tab=readme-ov-file#styling).

I will close this issue as there is no bug to fix. It's likely a problem with your local environment. If you have any specific questions about your implementation, you can ask on the [bpmn.io forum](https://forum.bpmn.io/).

**Comment by SumuduRasnayake** [comment]
Could you please provide the Node.js version you used for this example?

**Comment by jarekdanielak** [comment]
I used Node v20.15.0

**Comment by SumuduRasnayake** [comment]
Noted with thanks.
