### ISSUE TITLE
I can pass a business key for a call activity

### ISSUE THREAD

**Issue by mburke84** [bpmn-io/bpmn-js-properties-panel#112]
AT:
* I can pass the business key for a call acitivity. When doing so I can either choose to propagate the business key of the current PI (behind the scenes the expression  `#{execution.processBusinessKey}` is added to the Xml.

See also: https://docs.camunda.org/manual/latest/reference/bpmn20/subprocesses/call-activity/#passing-business-key

**Comment by romansmirnov** [comment]
This should also be done for (case) call activity.

**Comment by gimbel** [comment]
I agree, do we need a separate ticket for it or will we use this ticket?

**Comment by polenz** [comment]
no separate ticket!

**Comment by polenz** [comment]
Branch for call activity refactoring: https://github.com/bpmn-io/bpmn-js-properties-panel/commits/callable-refactoring

Issue Branch: https://github.com/bpmn-io/bpmn-js-properties-panel/commits/businessKey-callActivity-112
