### ISSUE TITLE
Alternative styling for clear buttons

### ISSUE THREAD

**Issue by zeropaper** [bpmn-io/bpmn-js-properties-panel#115]

**Comment by zeropaper** [comment]
@meyerdan I have some doubts about what has to be done :sweat_smile:
Something like that?
![image](https://cloud.githubusercontent.com/assets/65971/12113354/69ac17f4-b3a2-11e5-9b6b-0b3951605d9f.png)

**Comment by meyerdan** [comment]
I like the positioning for the single text input.

As far as the textarea is concerned, it looks a bit "out there" :)

**Comment by zeropaper** [comment]
Same here, I'm not especially convinced by the positioning of the textarea button (and would rather leave it as it was in that case, completely outside).
The problem is, with the textarea, that it would be odd to have in the (inside) top right corner, because I would need to put a padding on the right side in order for the text to be visible
![image](https://cloud.githubusercontent.com/assets/65971/12136978/0e7cd02a-b44d-11e5-88c8-2a9ef1be0f0f.png)
And on textareas we have scrollbars to deal with...
![image](https://cloud.githubusercontent.com/assets/65971/12137024/50388a9a-b44d-11e5-9e14-6d6ca05f3afa.png)
So I would go for something like that:
![image](https://cloud.githubusercontent.com/assets/65971/12137093/c592d944-b44d-11e5-9351-3169ead45fa1.png)
Anyways, those changes can be made in a snap.

**Comment by zeropaper** [comment]
Other alternative
![image](https://cloud.githubusercontent.com/assets/65971/12137780/c72cb4ae-b453-11e5-9209-85d642afd960.png)
