### ISSUE TITLE
Alternative styling for disabled properties

### ISSUE THREAD

**Issue by zeropaper** [bpmn-io/bpmn-js-properties-panel#116]
Currently we do not show properties which cannot be used.
Example: if neither asyncBefore nor asyncAfter => exclusive is not visible

Alternative: such properties are visible but "disabled"

aka "B mode"

**Comment by zeropaper** [comment]
![image](https://cloud.githubusercontent.com/assets/65971/11840778/c34f8a2a-a3f8-11e5-943c-7cb9b424d536.png)

**Comment by zeropaper** [comment]
![image](https://cloud.githubusercontent.com/assets/65971/11840792/ef349fb8-a3f8-11e5-8952-400fdc467230.png)

**Comment by zeropaper** [comment]
![image](https://cloud.githubusercontent.com/assets/65971/11840814/1cd19782-a3f9-11e5-93f0-63a3ae277855.png)

**Comment by jasonlam0619** [comment]
@zeropaper  How did you do that, if I may ask?

**Comment by zeropaper** [comment]
You may ask but... 
it's old and I haven't work on that project since a while... so I can't answer.
sorry.

**Comment by nikku** [comment]
We'll not implement his any time soon.
