### ISSUE TITLE
I can set the initiator for a start event

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js-properties-panel#119]
AT:
- initiator attribute can be set for any start event except for start events inside of subprocesses

**Comment by shentschel** [comment]
We have to release https://github.com/camunda/camunda-bpmn-moddle/issues/22 to use this feature.

**Comment by meyerdan** [comment]
@nikku will release  camunda/camunda-bpmn-moddle and then merge this branch :)
