### ISSUE TITLE
I cannot set an illegal ID

### ISSUE THREAD

**Issue by saig0** [bpmn-io/bpmn-js-properties-panel#120]
Problem:
* I can set an ID (e.g. on process) which does not fit the type "xsd:ID" (defined by BPMN Specs)
* the process cannot be deployed on camunda BPM because of illegal ID

Expected:
* ID which are not of type "xsd:ID" can not be entered and an error message is shown

**Comment by nikku** [comment]
What is an illegal ID? An example would be helpful.

We do comprehensive validation already to make sure IDs are QNames. See aa6f19fc315a2981ceb552ef87489bea3aafc477.
