### ISSUE TITLE
I can set the called element for call activities

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js-properties-panel#13]

**Comment by meyerdan** [comment]
Discussion Point:

The way it is implemented now we effectively have three property entries:
* 'calledElement',
* 'calledElementBinding'
* 'calledElementVersion'

This is inconvenient for a user who wants to control whether the property is available or read-only (customization use case). The user should be able to configure this as a single property

**Comment by meyerdan** [comment]
@gimbel re my above comment:

* can you make sense of what I write about?
* what is your opinion on this?

**Comment by gimbel** [comment]
@meyerdan are these 3 elements exclusive to each other?
