### ISSUE TITLE
Redo problem when changing form field id

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#136]
steps to reproduce:
 * Select a start event
 * Create a form field using the properties panel
 * Edit the form field id to an invalid value (i.e. containing white space)
 * Undo
 * Redo

problem:
 * nothing happens on Redo

expected behavior:
 * to be discussed. Switch back to the invalid value?

possible solution: provide a command handler for the case, when values are changed in the DOM but no changes are made to the business object. This makes sure, that DOM-only values can be cached and restored.

**Comment by pedesen** [comment]
Branch: https://github.com/bpmn-io/bpmn-js-properties-panel/tree/form-field-redo-136

Test case: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/bf9221954eb477932de7c7e70c6d00a26797cd56/test/spec/provider/camunda/FormDataSpec.js#L228-L238

**Comment by nikku** [comment]
I'd keep the current behavior (i.e. not switch to the invalid value). If people like to have undo / redo, they can easily fix the validation errors before undo.

**Comment by pedesen** [comment]
I'm okay with it. But then we have to adjust the currently skipped test cases before closing the case :yum:

**Comment by nikku** [comment]
Really closed now :wink:.

**Comment by pedesen** [comment]
:+1:
