### ISSUE TITLE
Display problem when 4 tabs are visible

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#138]
When selecting an element which contains properties from all 4 tabs (i.e. user task), this happens:

![selection_015](https://cloud.githubusercontent.com/assets/2543743/12944858/356e8652-cfea-11e5-84c7-56e05f753ade.png)

**Comment by gimbel** [comment]
Should we consider fixing this in the current milestone?

**Comment by zeropaper** [comment]
The problem with tabs.. is that they don't scale.
My suggestions (use the operators "and", "or" or both combined with them):
 - rename "Input/Output" to "I/O"
 - (if more than X tabs,) make a dropdown menu
 - use an "accordion" widget
