### ISSUE TITLE
Add validation error messages in tableEntryFactory

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#144]
Validation error messages are missing (see screenshot) and should be shown for the id fields from tableEntryFactory. This affects:
- camunda:value ids (for form fields of type enum)
- camunda:properties ids (as children of form fields)

![validation](https://cloud.githubusercontent.com/assets/2543743/13280798/5a17c008-dae0-11e5-83c8-ba1cdc6e9221.png)

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
