### ISSUE TITLE
Integer validation for input fields

### ISSUE THREAD

**Issue by prameelapodigiri** [bpmn-io/bpmn-js-properties-panel#146]
Hi Team,

I need input integer validation for input field

My piece of code
----------------------------
var successMessageEntry = entryFactory.textField({
                id: 'successMessage',
                description: '',
                label: 'Success Msg',
                modelProperty: 'successMessage',
                validate: function(element, values) {
                  var successMessageValue = values.successMessage;

              var validationResult = {};
              var businessObject = getBusinessObject(element),
               newObjectList = [];

              var bo = getBusinessObject(element);
              var assigned = bo.$model.ids.assigned(successMessageValue);

              var idExists = !!assigned && assigned !== bo;
              if (!successMessageValue || idExists) {
                validationResult.id = "Element must have an unique id.";
              }

             return validationResult;

             if (typeof values.successMessage !== 'undefined' && values.successMessage !== '') {
                 newObjectList.push(bpmnFactory.create('bpmn:SuccessMessage', {
                   text: values.successMessage
                 }));
               }
            }

          });
     group.entries.push(successMessageEntry);

Thanks
-Prameela

**Comment by nikku** [comment]
There is no need to double post your issue here and [in the forum](https://forum.bpmn.io/t/integer-validation-for-input-textfields/521). Won't get you help faster.
