### ISSUE TITLE
Improve styling of "Configure Connector" link

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/bpmn-js-properties-panel#148]
The problem is that it looks like a traffic light, when no connector id is set.

![connector-link](https://cloud.githubusercontent.com/assets/2368139/13170679/1be5ee54-d6ee-11e5-8478-d2f014e764ee.png)

AT:
- improve the styling of the "Configure Connector" link, so that it is clear, that it is a link
- improve the styling so that it does not look like a traffic light ;)

**Comment by zeropaper** [comment]
As discussed with @romansmirnov, I'm assigning him the issue back so he can have a look.
