### ISSUE TITLE
Group form entries

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#150]
Instead of having one group for forms (see screenshot), we should consider grouping some entries in the forms tab. This benefits in the possibility to hide them individually.

![formgroups](https://cloud.githubusercontent.com/assets/2543743/13283800/4cead5b8-daf0-11e5-9692-b2896b31ae44.png)

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
