### ISSUE TITLE
Custom external editing component - some remarks

### ISSUE THREAD

**Issue by jeromew** [bpmn-io/bpmn-js-properties-panel#160]
Hello,

I have been trying to use bpmn-js-properties-panel to edit properties on a diagram that I am creating with diagram-js. I wanted to edit a short json property and thus tried to integrate https://github.com/josdejong/jsoneditor which has a nice tree view for json + json schema validation.

Maybe the results of my investigation can help change the API of properties-panel to make it easier to integrate custom components.

**1/ execute javascript at rendering time**

to integrate such a component, it is necessary to instanciante an object at rendering time and bind it on the dom that `bpmn-js-properties-panel` is going to append on the document.

the only way I could find to do this is to hijack https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/PropertiesPanel.js#L1007

```
if (html.get) {
      html = html.get(0);
}
```

my `JSONEditorEntryFactory.js` defines

```
resource.html = {
    get: function() {
        ...
        return html
    }
}
```

and this way I could create and bind the editor at rendering time.

It could be interesting to have an official way to call a function to get the html instead of only the string/jquery options.

**2/ notify `bpmn-js-properties-panel` of a change**

currently it seems that `bpmn-js-properties-panel` mainly reacts to change events on inputs. In my case I needed to find a way to propagate a change event from JSONEditor to `bpmn-js-properties-panel`.

I linked a hidden textarea to the onChange event of JSONEditor and `bpmn-js-properties-panel` is observing this textarea. The only problem is that the input.change event is not dispatched when a textarea.value is changed programmaticaly so I had to manually create and dispatch a 'change' event on the element.

It could be interesting to have an entry point to inform `bpmn-js-properties-panel` of a change.

**3/ definition of a new EntryFactory**

currently all the EntryFactories have accessors in `factory/EntryFactory.js` which makes it weird to "inherit" `bpmn-js-properties-panel`. Even more because there is no access to the impl of `setDefaultParameters` that is used as a helper.

It could be maybe be interesting to have a way to add new factories as some sort of plugin, with a `registerFactory` of some sort maybe.

---

I can send a PR with the (simple and hackish) JSONEditorEntryFactory.js if you think this is something that you would like to investigate. The only problem I see is that it does a `require('jsoneditor')` which would increase the overal payload of the library. If `EntryFactory.js` requires `JSONEditorEntryFactory.js` it will always be included even if no property panel uses it.

**Comment by nikku** [comment]
Individual entries do support returning their HTML via `setControlValue` now: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/PropertiesPanel.js#L866.
