### ISSUE TITLE
Restrict condition editing to sequence flows behind tasks / gateways

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#164]
Only places where sequence flow conditions should be editable:

* sequence flows with activities as source  (conditional flow)
* sequence flows with  gateways as source (exclusive / inclusive / complex gateway to be more specific)

**Comment by gimbel** [comment]
![image](https://cloud.githubusercontent.com/assets/3829733/15579952/1d6be5e2-2367-11e6-9bf6-e8e674e26bff.png)

**Comment by gimbel** [comment]
not sure about transaction
