### ISSUE TITLE
Add ability to select element template (custom task)

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#171]
* [ ] provide ability to select template in properties panel (based on task type and custom task descriptors)
* [ ] store template marker `camunda:modelerTemplate` with edited elements
* [ ] modify elements based on template definition on selection
* [ ] only show custom controls for a task with selected template
* [ ] update task internals on user input

**Comment by vkatushenok** [comment]
@nikku This looks to be already covered by #173, right?

**Comment by nikku** [comment]
Yes.
