### ISSUE TITLE
Add update title method

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#177]
Create a propertiesPanel method which updates the title every time the `propertiesPanel.changed` event has been fired. It should be possible to override this method in an instance of propertiesPanel.

See [forum thread](https://forum.bpmn.io/t/how-to-rename-the-title-of-the-property-panel/614)

**Comment by nikku** [comment]
@pedesen You want to work on this? Otherwise I'd close this refactoring ticket.

**Comment by pedesen** [comment]
Maybe, let's first check in the [forum](https://forum.bpmn.io/t/how-to-rename-the-title-of-the-property-panel/614/3) if there is still a need for it.
