### ISSUE TITLE
Providers break on minification

### ISSUE THREAD

**Issue by adrobisch** [bpmn-io/bpmn-js-properties-panel#178]
`BpmnPropertiesProvider` and `CamundaPropertiesProvider` are missing the `$inject` property, hence its not possible resolve their dependencies after minification (because params will be named like `a` or `b`).

I would expect something like

`Provider.$inject = ['eventBus', 'bpmnFactory', 'elementRegistry'];`

**Comment by gimbel** [comment]
Thanks for your feedback.

Are you interested in providing a pull request for that?

**Comment by gimbel** [comment]
Thanks Andreas, we will take a look at your pull request soon!
