### ISSUE TITLE
I can set delegate variable mapping for a call activity

### ISSUE THREAD

**Issue by Zelldon** [bpmn-io/bpmn-js-properties-panel#192]
AT:

* When I select an call activity, a variableMappingClass and variableMappingDelegateExpression input field is shown
* When I put a value into the variableMappingClass field, it is stored as `camunda:variableMappingClass` attribute
* When I put a value into the variableMappingDelegateExpression field, it is store as `camunda:variableMappingDelegateExpression` attribute

Example XML for variableMappingClass:

```
<callActivity id="callSubProcess" 
 calledElement="simpleSubProcess"                     
 camunda:variableMappingClass="org.camunda.bpm.test.Test"/>
```

Example XML for variableMappingDelegateExpression:

```
<callActivity id="callSubProcess" 
 calledElement="simpleSubProcess"             
camunda:variableMappingDelegateExpression="${test}"/>
```

**Comment by Zelldon** [comment]
Related to [CAM-5186](https://app.camunda.com/jira/browse/CAM-5186)

**Comment by polenz** [comment]
Depends on this commit: https://github.com/camunda/camunda-bpmn-moddle/commit/35e14131ed8f88183a25da81ba3e5821c55185c5

**Comment by pedesen** [comment]
The variableMappingClass and variableMappingDelegateExpression attributes should be removed from the call activity when changing the call activity type.
