### ISSUE TITLE
Is there any chance to see this library in bower?

### ISSUE THREAD

**Issue by PhantomYdn** [bpmn-io/bpmn-js-properties-panel#197]

**Comment by nikku** [comment]
Not planned for now. If you are in urgent need for it, you could [bundle it yourself](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bower-bundle).

**Comment by lifinanalytics** [comment]
Hello, Could you please release this feature soon as am using bower as a primary module manager in my project.
Thanks

**Comment by nikku** [comment]
Won't release a bower version any time soon.
