### ISSUE TITLE
I can set multiInstanceLoopCharacteristics

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js-properties-panel#20]
AT:
- loopCardinality
- completionCondition
- camunda:collection

**Comment by meyerdan** [comment]
Additional constraints that need to be implemented:
- loopCardinality and camunda:collection are mutually exclusive (I can only set one)
- if I set camunda:collection then I can also set camunda:elementVariable
(completionCondition can always be set)
