### ISSUE TITLE
Localize properties panel labels (I18N)

### ISSUE THREAD

**Issue by PhantomYdn** [bpmn-io/bpmn-js-properties-panel#207]
Hello,
We are working on [Orienteer - Business Application Platform](http://orienteer.org) and have embedded Camunda and your brilliant modelers/viewers. And it will be finally perfect if there is some good way to localize UI. We found some way to localize modeler, but without properties panel. Please help with that!

**Comment by nikku** [comment]
What exactly would you like to localize?

**Comment by PhantomYdn** [comment]
Every single label on property panel. Modeler themself localizable - but no key for properties panel on the right.

**Comment by nikku** [comment]
The modeler localization was contributed through a PR by a community member.

Would you like to contribute that for the properties panel? If so, approach us in our [forums](https://forum.bpmn.io/c/developers) and we can give you the necessary guidance.

For reference, the initial i18n implementation contributed to bpmn-js: https://github.com/bpmn-io/bpmn-js/issues/491.

**Comment by dissdoc** [comment]
Hi all!
I want to localize properties-panel, but I need a help for this problem.

My idea is: I am going to find all labels and replace it to localize-method  (like bpmn *locale*-method)
Am I true?
