### ISSUE TITLE
Separate camunda properties from core bpmn properties

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#21]
We should separate the camunda properties from the core bpmn properties such that a user can choose between a camunda enabled property panel and a panel which only provides the bpmn stuff.

**Comment by carrchang** [comment]
Hi, first release time of the customized properties panel is?

**Comment by meyerdan** [comment]
We have not fixed a  date yet but I would expect a first version of the panel to be released over the next 1-2 months.

**Comment by carrchang** [comment]
How and when the properties update into the model?

**Comment by polenz** [comment]
Hi carrchang,

Sorry, I did not completely understand your question? Are you inquiring about release dates or the functionality?

Regards,
Kristin

**Comment by carrchang** [comment]
It's about the functionality. Thank you!

--
13581578582
张智
