### ISSUE TITLE
Cannot modify 'Name' property through property panel under Internet Explorer

### ISSUE THREAD

**Issue by romero83** [bpmn-io/bpmn-js-properties-panel#210]
Hi,

I am just facing an issue that I cannot modify (event not firing?) 'Name' of the selected notation through property panel under Internet Explorer. I used property-panel v0.9.0 and IE version 10 and 11 for the test. Under Firefox and Chrome it works fine.
![ie_bug](https://cloud.githubusercontent.com/assets/9417960/18703319/acbce342-7fe5-11e6-9c9c-d16483f39e9b.PNG)
Workaround is that I modify the 'Name' through modelling by double click on the notation.

**Comment by romero83** [comment]
Actually it looks like cannot modify those fields which HTML is div contenteditable. Like Name, Element documantation, etc.

**Comment by pedesen** [comment]
An `input` event listener is added on the contenteditable div. This event is being fired when the content changes. But it is not supported by Internet Explorer for contenteditable divs. See https://developer.mozilla.org/en-US/docs/Web/Events/input#Browser_compatibility

**Comment by nikku** [comment]
I'd use a mutation observer for Internet Explorer 11. 

All other things become to complex. We do not need to support IE < 11 for editing anyway.

**Comment by nikku** [comment]
Other question: Is `changed` dispatched? Would work, too.

**Comment by romero83** [comment]
Be aware that you created contenteditable **div**s, so its label **for** attribute is not working anymore to bind to the field by ID because label is meant only for form elements (input, select, textarea).

**Comment by nikku** [comment]
IE :skull:.

Fixes available here: https://github.com/bpmn-io/bpmn-js-properties-panel/compare/master...ColinFrick:master
