### ISSUE TITLE
I can add conditions on conditional events

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#211]
I can configure conditional events and **add conditions** (like on conditional sequence flows) in the property panel.

AT:
- on intermediate, boundary and start Event-Subprocesses I can add conditions on conditional events
  
  Should look like this:

```
      <bpmn:conditionalEventDefinition>
        <bpmn:condition xsi:type="bpmn:tFormalExpression">${false}</bpmn:condition>
      </bpmn:conditionalEventDefinition>
```

Related to [CAM-6602](https://app.camunda.com/jira/browse/CAM-6602).

**Comment by Zelldon** [comment]
Hey,

the `bpmn:conditionalEventDefinition` got two new properties, `camunda:variableName` and `camunda:variableEvent`. It will be fabulous if they can be added to the properties panel, as well. 

The properties are used to define when the condition should be evaluated.

Greetings,
Chris

**Comment by pedesen** [comment]
I created a separate ticket for the `camunda:variableName` and `camunda:variableEvent` properties.

**Comment by polenz** [comment]
Review Hint:
Regarding the Engine Implementation: 
- Conditional Start Event in a subprocess is not allowed
- empty ConditionalEventDefinition is not allowed

AT:
- input field condition should be a required field

- for discussion: it should not be possible to model conditional start events in a subprocess?
