### ISSUE TITLE
unable to load module events

### ISSUE THREAD

**Issue by mrajende** [bpmn-io/bpmn-js-properties-panel#220]
I want to use this properties panel. I install the module with npm install --save bpmn-js-properties-panel.

Then when I run my app, I get an error unable to load module events.(..) that is a dependency in module scroll-tabs. How can this issue be resolved?

**Comment by nikku** [comment]
How do you bundle the library for the browser? Make sure to not exclude the `events` builtin if you use Browserify.

**Comment by mrajende** [comment]
I am not sure why it could be excluded.
in my project I first run 
1) npm install -- save bpmn-js-properties-panel
2) grunt build

[Gruntfilejs.txt](https://github.com/bpmn-io/bpmn-js-properties-panel/files/599793/Gruntfilejs.txt)
[packagejson.txt](https://github.com/bpmn-io/bpmn-js-properties-panel/files/599796/packagejson.txt)

renamed them to txt files to enable upload.

attached is the grunt and project file

**Comment by nikku** [comment]
Looks like you copied your structure from bpmn-js.

Make sure to remove [this line](https://github.com/bpmn-io/bpmn-js/blob/master/tasks/bundle.js#L93) from your `tasks/bundle.js` script.
