### ISSUE TITLE
Different elements with different tabs

### ISSUE THREAD

**Issue by anmarcek** [bpmn-io/bpmn-js-properties-panel#232]
There is a problem if I want to use the properties panel in the following scenario: Two elements (let's name them FooTask and BarTask) have different properties and therefore we define different tabs in the properties panel for each element. FooTask's properties are displayed on tab FooTab and BarTask's properties are displayed on tab BarTab. Now let's say the currently selected element is FooTask so the properties panel displays FooTab. Then a user selects a BarTask element so FooTab disappears and BarTab appears. However, BarTab is not selected - actually no tab is selected as properties panel tries to activate FooTab which is not present anymore.

**Comment by nikku** [comment]
Could you provide a minimal test case that allows us to reproduce this behavior?
