### ISSUE TITLE
CmdHelper method addAndRemoveElementsFromList can't remove elements

### ISSUE THREAD

**Issue by shifenghdu** [bpmn-io/bpmn-js-properties-panel#233]
UpdateBusinessObjectListHandler.js   
line 68:  if (objectsToRemove.indexOf(object) == -1)  
change to 
if(includes(objectsToRemove,object))  // lodash/collection/includes
will be ok

**Comment by philippfromme** [comment]
Can you please give some more context? What is the issue you encountered?

**Comment by nikku** [comment]
Cannot reproduce.
