### ISSUE TITLE
How to customize the properties panel?

### ISSUE THREAD

**Issue by jasonlam0619** [bpmn-io/bpmn-js-properties-panel#234]
![image](https://user-images.githubusercontent.com/8470477/27018539-ece28082-4f63-11e7-909d-d7776959136e.png)

Say I want to hide certain inputs or tabs. How to config?

Can't find relative APIs. So I tried to meddle in the CSS, but it just ignores external styles.

**Comment by philippfromme** [comment]
The properties panel can easily be customized through providing your own properties provider. You can see an example [here](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension). In the future please use our [forum](https://forum.bpmn.io/) for general questions.
