### ISSUE TITLE
IE issue - The code on this page disabled back and forward caching.

### ISSUE THREAD

**Issue by harafat007** [bpmn-io/bpmn-js-properties-panel#237]
Hi Team,
We are facing issues while trying to save the BPMN diagram (by clicking on the BPMN diagram) button on IE 11.
We keep getting error "DOM7011: The code on this page disabled back and forward caching. 
For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337 "

and the diagram wont save.

Please see the attached snapshot for details.

Thanks
Hussy

**Comment by harafat007** [comment]
https://github.com/bpmn-io/bpmn-js-properties-panel

**Comment by nikku** [comment]
I'm sorry but we can't reproduce your issue with the description you've provided.
