### ISSUE TITLE
Any plan to release a ES2015 version

### ISSUE THREAD

**Issue by carrchang** [bpmn-io/bpmn-js-properties-panel#246]

**Comment by nikku** [comment]
Why?

**Comment by carrchang** [comment]
I want to integrate modeler and panel into my single page app, but got some build errors. Finally, I create a minimized version of modeler with panel using same building ENV as `bpmn-js`, and then loaded using `script-loader` plugin for `webpack`.

So, It's not really needed now.

Thanks for your attention.
