### ISSUE TITLE
Provide compiled version of stylesheets

### ISSUE THREAD

**Issue by snoop244** [bpmn-io/bpmn-js-properties-panel#251]
First off, thanks for the massive amount of effort the team has put in to creating these bpmn-* and diagram-js projects.  I can't imagine how much work went into this.

While I reference React in my issue, the request for a .less compilation task in the properties-panel component seems like a good thing generally.  I'm not a javascript developer, but I assume it is possible...

Edit: Same challenge with cmm-properties-panel... but no example application to help with the workaround.  I guess I need to learn Gulp.

Note that I tried ide less transpilers in both vs code and intellij to no effect and I tried the instructions provided by the create-react-app team to deal with less files, but it did not work on these particular .less files.

### Expected Behavior
When I npm install properties panel in a framework (e.g. React and create-react-app) that does not play well with less, I expect the npm module itself to handle the compilation to css.  As it stands, the example projects that use the properties panel set up the less compilation tasks.  As a workaround, I was able to build the examples and copy the resulting compiled css file to my React project

Ideally the properties-panel module itself would automate the compilation.

### Actual Behavior
React project does not compile the less styles and panel is unstyled and non functional.

### Steps to reproduce the Behavior
Use create-react-app to boilerplate a React v16 project
Integrate bpmn-js (success)
Integrate bpmn-js-properties-panel (success, shows in dom, but no styling and non-functional)

**Comment by nikku** [comment]
So what you're asking about is a pre-compiled stylesheet?

**Comment by snoop244** [comment]
Yes please.

**Comment by nikku** [comment]
We accept pull requests that provide the described functionality.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/aea0d168a3e51ce1845114ab82086634969715e3.
