### ISSUE TITLE
get, set and validate methods fire any click on element

### ISSUE THREAD

**Issue by snoop244** [bpmn-io/bpmn-js-properties-panel#252]
Since these features are not fully documented, this could be expected behaviour, but I don't think so.

### Expected Behavior
When I attach a validate, get or set method to entryFactory.textField, I do not expect it to fire on any click of the element in the diagram nor on any click or keyboard event in the textfield itself.

NOTE: I was experimenting with this feature to understand when it would fire to see if I could use it to fetch a list of possible values via a REST call to a service and then set the textfield value.  

### Actual Behavior
My test functions attached to validate, get and set fired on every click of the element in the diagram (i.e. when the panel is activated) and every character typed in the text field.  I may misunderstand the intent of these hooks/callbacks, mind you, and this may be intended behaviour.

### Steps to reproduce the Behavior
Attach a method to the get, set, or validate properties of a property panel textfield and then click the element in the diagram or type a character in the textfield.  The method will fire.

**Comment by snoop244** [comment]
I just spent some time in the Camunda properties panel code to see how you guys used get and set and, I am clearly misunderstanding how it all works.  You can go ahead and close this as your code clearly uses get and set without problems.

I would be grateful if you could provide a hint as to how I can hook into the properties panel to inject look-up lists from REST calls instead of the current approach that expects manual entry from the user.  For example, instead of asking the end user to enter the "Candidate Users" and "Candidate Groups", I would like them to select from a list fetched from our user management system.  I thought the get and set hooks could be used, but now I'm not so sure.

LMK if I should just pose this on Stackoverflow.

**Comment by dorseth** [comment]
I would also like to know that, absolutely same task - to inject the list from an object to properties name.
Now I'm doing some dirty magic with jQuery, but it's a no-go in the long term and it doesn't work on contenteditable for some reasons (I guess it doesn't pass validation hooks).
