### ISSUE TITLE
How to properly use setTemplates

### ISSUE THREAD

**Issue by ludoo0d0a** [bpmn-io/bpmn-js-properties-panel#253]
I'd like to load from a remote source all elements templates.
I see the method [setTemplates in loader](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/1e167391798d9d1472c91678be8f8e29cc4f2114/lib/provider/camunda/element-templates/ElementTemplatesLoader.js#L70) .

But I don't know how to access from my modeler instance. and then use it.

Thanks for you help.

**Comment by nikku** [comment]
You may inject the elementTemplateLoader via `Modeler#get`:

```javascript
var bpmnJS = ...;

bpmnJS.get('elementTemplateLoader`).setTemplates([ ... ]);
```
