### ISSUE TITLE
Different entries shown for connection and connection label

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-properties-panel#254]
Support ticket: https://app.camunda.com/jira/browse/SUPPORT-4053

Expected behavior:
* same entries shown for connection and connection label

Actual behavior:
* different entries shown

![foobar](https://user-images.githubusercontent.com/7633572/35920524-63a24d58-0c18-11e8-9ba3-19a001827c6f.gif)

**Comment by nikku** [comment]
Would not be the expected behavior for me.

Clicking a label, I'd like to change it.
Clicking a sequence flow, I''d like to configure the actual flow.

**Comment by philippfromme** [comment]
This issue represents the expected behavior depicted in the support ticket. There is room for discussion though.

**Comment by nikku** [comment]
If we go for the route I mentioned the properties panel should clearly identify whether the label or the actual element is selected though. Not sure if that is the case right now.

**Comment by nikku** [comment]
This addresses https://github.com/camunda/camunda-modeler/issues/731.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/40935240b4ef01bfd435f7c20d594cbea1976832.
