### ISSUE TITLE
FormHelper hardcodes extension element type to camunda:FormData

### ISSUE THREAD

**Issue by snoop244** [bpmn-io/bpmn-js-properties-panel#255]
### Expected Behavior
Trying to adapt code used to allow for the creation of form fields.  I have created my own extension element but it does not work with form fields.  I am basically copying your code and swapping it in by replacing the existing extension name:
```
camunda:FormData
```
with my own variant:
```
mycompany:SchemaData
```

My application needs to support both concepts (form fields and a schema definition), so camunda:FormField is still actively used in my application without problems.  

I may be heading down the wrong path here, so feel free to send me in another direction, but I copied and edited the code to create a layout that is very similar to the Form Fields layout in the Forms tab of the Properties Panel, but with some minor changes and my own extension names.  

### Actual Behavior
As a user, the customizations work fine except when I go to add new form fields with the "+" button, the field deletes itself.  I can see that the field is added when I step through the application in my debugger, but then it fails a test and is removed as an orphan by this line:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/c4eba3c75c472daad4c91f23a27e0c45c7906386/lib/PropertiesPanel.js#L995

...most likely because the arguments in the following function call in FormHelper include the hardcoded camunda:FormData rather than being passed the extension element type from the calling function.  
```javascript
  var formData = getExtensionElements(bo, 'camunda:FormData');
```
Since my type is not a camunda:FormData, it returns nothing and my newly added form field is removed.
Perhaps it is hardcoded for a good reason and I am heading down the wrong path with my attempted customization but, ideally, I could use FormHelper with any custom extension element.

**Comment by nikku** [comment]
I'd ask you to file a pull request that fixes the behavior if you'd like things to be changed.

* Adhere to our coding style
* Provide necessary tests

A maybe simpler alternative for you is to copy the utility, adapt it to your use case and don't worry about the `FormHelper` anymore.
