### ISSUE TITLE
Release bpmn-js-properties-panel v0.24.0

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#261]
* [x] Add CHANGELOG similar to [bpmn-js](https://github.com/bpmn-io/bpmn-js/blob/master/CHANGELOG.md)
* [x] release
* [x] integrate into Camunda Modeler (closing open tickets)

**Comment by philippfromme** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/f21f5662b829c6e1f577574215d27268c667583f.
