### ISSUE TITLE
Text content of contenteditables is not properly retrieved when line breaks were inserted

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-properties-panel#266]
### Steps to reproduce the Behavior

1. Type "foo"
2. Press `ENTER`

### Expected Behavior

1. Text retrieved is "fooENTER"

### Actual Behavior

1. Text retrieved is "fooENTERENTER"

**Comment by damthor** [comment]
Any update on this? I'm working on syntax highlighting for certain input areas and this kind of interferes with it.
It seems that there are differences on how the text inside contenteditables is rendered:
- when editing, each line break is rendered as `<div><br></div>` or `<div>text</div>`
- when reopening the entry for an element, each line break turns to a `<br>` instead (and by that, somehow more line breaks are added)

**Comment by nikku** [comment]
No update. But we would be happy to learn more if you contribute your knowlege.

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
