### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by dpan7** [bpmn-io/bpmn-js-properties-panel#267]
Hi there, 

I am facing some weird issue with the style of the properties-panel on my project (Angular I do not know if it is relevant). Although, I have managed to integrated successfully to the project, it seems that the style does not load.

![bpmn](https://user-images.githubusercontent.com/37615091/41709883-00ab30a4-754d-11e8-848e-bf9210527b61.PNG)

Do you have any insights in order to identify the problem? 

I know that the whole question it might seems a little vague, so let me know if you want further info in order to provide me an answer. 

Thanks in advance for your help.

**Comment by nikku** [comment]
How do you load the properties panel style sheet?

**Comment by dpan7** [comment]
I am not. I thought it is done automatically via the npm repo which I downloaded. Should I imported to the page?

**Comment by nikku** [comment]
The properties panel contains a [stylesheet](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/styles/properties.less) that must be compiled manually and included in the app.

See the [properties-panel example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel) for details.
