### ISSUE TITLE
Missing global variable names , pre-packaged by rollup，undefined event and query after out~

### ISSUE THREAD

**Issue by 365966815** [bpmn-io/bpmn-js-properties-panel#268]
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
D:\software\develop-tools\environment\nodejs-module\node_global\node_modules\rollup\dist\rollup.js (guessing 'query')
D:\software\develop-tools\environment\nodejs-module\node_global\node_modules\rollup\dist\rollup.js (guessing 'event')
created ../../src/main/resources/META-INF/resources/webjars/bpmnx/modeler/bpmn-properties-panel.development.js in 1.8s

this is my rollup.config.js
``` javascript
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import globals from 'rollup-plugin-node-globals';
import builtins from 'rollup-plugin-node-builtins';


export default {
    input: 'lib/index.js',
    output: {
        file: 'bpmn-properties-panel.development.js',
        name: 'BpmnJsPropertiesPanel',
        format: 'umd'
    },
    plugins: [
        globals(),
        builtins(),
        resolve({
            browser: true,
            moduleDirectory: 'node_modules'
        }),
        commonjs(),
        json(),
    ]
};
```

**Comment by nikku** [comment]
Is this a feature, question or issue?

**Comment by nikku** [comment]
Closing via [this comment](https://forum.bpmn.io/t/bpmn-properties-panel-pre-packaged-by-rollup-undefined-event-and-query-after-out/2436/5?u=nikku).
