### ISSUE TITLE
Provide a pre-packaged version similar to bpmn-js

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#270]
Provide a pre-packaged version of the bpmn-js-properties-panel helps folks to easier embed it into their projects.

__Tasks__

* [ ] Stylesheets are pre-compiled to `CSS` (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/251)
* [ ] Pre-packaged artifact is generated
* [ ] Styles + JS artifacts are published in `dist` folder with `npm publish`

**Comment by daveleenew** [comment]
please provide tutorial without node.js? thanks

**Comment by stormqueen** [comment]
An example on how to use it without node.js would help me too

**Comment by vasicvuk** [comment]
+1

**Comment by 1weidong** [comment]
A pre-packaged version and an example on how to use it without node.js would help me too

**Comment by sergiorighi** [comment]
+1

**Comment by caoliy3567** [comment]
> +1

+10086

**Comment by barmac** [comment]
This seems to be done with v1.0.0
