### ISSUE TITLE
When used in a Typescript app, error in a bundled lodash files

### ISSUE THREAD

**Issue by Etchelon** [bpmn-io/bpmn-js-properties-panel#271]
I have a Typescript (Angular 6+) app where I use bpmn-js, and I'm trying to add a customized property panel as per your example.
When I import this library and add the propertiesPanelModule to the BpmnModeler object, at runtime I get the following exception in the browser console:

![image](https://user-images.githubusercontent.com/4141889/42872113-57c797b2-8a7c-11e8-90b3-c01c084ac18b.png)

Googling the error gave as first result this issue you posted to lodash's writer:
https://github.com/lodash/lodash/issues/915

Sadly this is an old issue and lodash is now at version 4.17.10.
I don't understand:
- why I have this issue in my app but not in the example, considering that the code I use is copied from the example because I'm just starting with bpmn-js.
- what exactly global should be... anyway I tried to include lodash as a "global" script tag in the HTML but the error doesn't go away.

How can I solve this? I noticed that this library references the old ^3.0.1 version of lodash...

**Comment by nikku** [comment]
As you mentioned: This issue should go away with a proper development setup.

So what is your setup like? How does it differ from the example?

**Comment by Etchelon** [comment]
I'm not sure. Even trying to replace lodash 4.17.10 with ^3.0.1 in my project's package.json didn't work.
I've managed to make it work, after a bit of debugging, by doing the following (obviously temporary solution):
- in lodash/internal/SetCache.js, lodash/internal/CreateCache.js and lodash/internal/metaMap.js, I've substituted the line
`/** Native method references. */
var Set = getNative(global, "Set");
`
with
`var global = global || (global = window);
/** Native method references. */
var Set = getNative(global, "Set");
`
`global` seems to be undefined in the browser at every level in my app (main.ts, other js files). Maybe webpack, which is used internally by the angular cli, doesn't set global and therefore it is undefined.
What I don't understand clearly is why lodash checks for `global` in lodash/index.js:
`  /** Detect free variable `global` from Node.js. */
  var freeGlobal = freeExports && freeModule && typeof global == 'object' && global && global.Object && global;

  /**
   * Used as a reference to the global object.
   *
   * The `this` value is used if it's the global object to avoid Greasemonkey's
   * restricted `window` object, otherwise the `window` object is used.
   */
  var root = freeGlobal || ((freeWindow !== (this && this.window)) && freeWindow) || freeSelf || this;
`
and then uses `global` instead of `root` in its internal methods...

I've also found this thread which I didn't grasp completely: https://github.com/lodash/lodash/issues/223 but this comment from @jdalton:

> @magestican For v3 not so much. The issue is resolved in v4.

made me think that the solution is probably that you upgrade to lodash v4... it's just a feeling, I'm not asking you to do that of course, but my current workaround to edit files in node_modules isn't a feasible solution given that my projects are managed with continuous integration where npm packages are continuosly reinstalled from scratch...

**Comment by Etchelon** [comment]
If the info I gave you do not suffice, and you want to try to debug the issue, I'll prepare a zip containing the project and the steps to set it up, in case you're not familiar with angular and typescript.

**Comment by nikku** [comment]
This is a general, AngularJS related issue, cf. https://github.com/angular/angular-cli/issues/8160.

The fix, as per [this comment](https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833) is to shim global in `polyfills.ts`:

```typescript
// shim global
// @see https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833
(window as any).global = window;
```
