### ISSUE TITLE
Camunda diagram not updating on jquery input

### ISSUE THREAD

**Issue by blakekp** [bpmn-io/bpmn-js-properties-panel#274]
### Expected Behavior
when using jquery to place text in an input and triggering the "input" event the background bpmn diagram is updated so upon download said information is held within the xml(I see this everywhere but for my use the extensions and general tabs are specifically the problem)

### Actual Behavior
unless a physical key is pressed the data is not propogated and then also dissappears if clicking off of the element, jquery events for input textInput focus blur keyup keydown and change do nothing( i used $element.trigger('eventname'); but also did it with vanilla js and the jqeury.event objects)

### Steps to reproduce the Behavior

use jquery to fill in a box on the properties panel, do not type anythong and immediately click away to another item or download the xml, upon going back to the item the info will be gone and when downloading the xml the info is not contained in there.

**Comment by blakekp** [comment]
we have a drop down of pre planned templates which allow us to fill in information easily for given tasks on the properties panel, what is the event triggering your debounce singleton? Are you still tied into the dom event model? I did see a custom event bus lying around and I could call directly to it if needed?

thanks for the help!

**Comment by nikku** [comment]
The way to handle these scenarios is to apply properties via [`Modeling#updateProperties`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/Modeling.js#L87) or a [composite operation](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/master/lib/cmd) directly to the model. The properties panel will reflect the changes accordingly.
