### ISSUE TITLE
Please provide ES6 module integration

### ISSUE THREAD

**Issue by mouseMD2017** [bpmn-io/bpmn-js-properties-panel#277]
Please provide proper support for es6 module import; I'm using vue-js and can't use require in js script part.

### Expected Behavior
import via `import PropertiesPanel from 'bpms-js-properties-panel' ` in script section is working

### Actual Behavior
import via `import PropertiesPanel from 'bpms-js-properties-panel' ` in script section is not working, throws error `Unexpected identifier`

### Steps to reproduce the Behavior
integrate `import PropertiesPanel from 'bpms-js-properties-panel' ` in script part of index.html of vue-js SPA.

**Comment by nikku** [comment]
The properties panel can be integrated just fine in ES 6 contexts so this must be an issue with your setup.

Please provide a concrete example repository that allows us to reproduce the behavior.

**Comment by mouseMD2017** [comment]
nikku: is there a chat, where we could discuss things in detail ? I think this would rather lead to a solution than endless post and reply lists :)
