### ISSUE TITLE
Entries hidden due to restricted container height

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-properties-panel#282]
When having many entries in the properties panel some of them are hidden due to [this](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/styles/groups.less#L4) CSS rule. The rule has no obvious benefits so it should be removed.

Support: https://app.camunda.com/jira/browse/SUPPORT-5085

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/4b25c5f4b5338bb5f6a6843a6854f61776d93bf4.
