### ISSUE TITLE
show value of input/output parameter

### ISSUE THREAD

**Issue by anhaltFelix** [bpmn-io/bpmn-js-properties-panel#288]
### Expected Behavior

I add a variable in the input/output tab and directly the key := value pair. 

### Actual Behavior

I add a variable in the input/output tab and directly the key : datatype. 

![image](https://user-images.githubusercontent.com/40464246/51032554-c4aaf680-15a0-11e9-948a-46a27de54a9c.png)

### Steps to reproduce the Behavior

Open the input/output tab on a Service Task.
Click on the plus-icon over the input parameters textarea.
Set some random value.
Look at the input parameters textarea.

**Comment by philippfromme** [comment]
This is not a bug. The list always displays _key:type_. Since the value could also be a list, map or script it would not be feasible to display it in the list.
