### ISSUE TITLE
How to localize properties panel labels

### ISSUE THREAD

**Issue by mmirzaeyan** [bpmn-io/bpmn-js-properties-panel#291]
hi 
how can i localize properties panel labels ? i see some issue on #207  and #230 but i don't really understand how can i localize labels in properties panel.  

thanks.

**Comment by pinussilvestrus** [comment]
Hi @mmirzaeyan,

what did you already do achieve the localization of the properties panel? What did you not understand in detail? Some more information will help us to help you 🙂 

In the future, you're welcome to use [our forum](https://forum.bpmn.io/latest) for asking questions. GitHub issues are more intended for bugs and feature requests.

**Comment by nikku** [comment]
Please follow along our [bpmn-js I18N example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/i18n). You localize the properties panel in the same way you localize bpmn-js.
