### ISSUE TITLE
Sanitize entities when building HTML

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#296]
#### Description

We do not properly sanitize entities (labels, ...) we build the properties panel UI from. This leads to [UI bugs](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/286#issuecomment-469174622) (cf. screenshot below) or script injection in the worst case.

An example for missing entity escaping can be found [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/SelectEntryFactory.js#L51).

#### Expected Behavior 

* [ ] We properly sanitize user input in all places where it is being used to build the properties panel.
* [ ] Escaping is [ported to all our properties panels](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/296#issuecomment-476146350)
* [ ] DMN https://github.com/bpmn-io/dmn-js-properties-panel/issues/9
* [x] CMMN https://github.com/bpmn-io/cmmn-js-properties-panel/issues/63

#### Additional Context

This is how the UI looks like if a description such as `List<Foo>` is rendered: 

![image](https://user-images.githubusercontent.com/58601/54914035-5bc2f180-4ef4-11e9-94ae-6a93e725f922.png)

**Comment by nikku** [comment]
A fix for this issue must be ported to our [DMN](https://github.com/bpmn-io/dmn-js-properties-panel) and [CMMN](https://github.com/bpmn-io/cmmn-js-properties-panel) properties panels, too.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/cmmn-js-properties-panel/pull/64.

**Comment by nikku** [comment]
Released as `v0.31.0`.

**Comment by AndrewBaliushin** [comment]
I used to use line breaks (<br> tag) in description of my custom fields. With this update it's no longer working. 
Is there a way to ignore/disable character sanitization for 'EntryFieldDescription', or to have multiple descriptions for the entry?
![image](https://user-images.githubusercontent.com/9324257/63254086-c269f280-c27b-11e9-8bc6-b6ffaf715f87.png)

**Comment by nikku** [comment]
Please create a new issue with your bug report.
