### ISSUE TITLE
I found a bug of i18n in bpmn-js-properties-panel

### ISSUE THREAD

**Issue by 919980059** [bpmn-io/bpmn-js-properties-panel#297]
![QQ截图20190327171913](https://user-images.githubusercontent.com/38972672/55064291-ae4b0c00-50b4-11e9-9438-f6d9585331c5.png)
![QQ截图20190327171856](https://user-images.githubusercontent.com/38972672/55064323-bacf6480-50b4-11e9-8e04-6245e99dfd07.png)
![QQ截图20190327170250](https://user-images.githubusercontent.com/38972672/55064874-bb1c2f80-50b5-11e9-9a40-1d574a30d11c.png)

**I translate all of the  value  in my custom translate js file,but i haven't found the param of the Description and some form validation error messages  in custom translate function，so i tried to overwrite the description param in camundaPropertiesProvider parts like translate(description),it works!** 

![QQ截图20190327170424](https://user-images.githubusercontent.com/38972672/55065185-57decd00-50b6-11e9-832c-d8a8d23672a1.png)
![QQ截图20190327170410](https://user-images.githubusercontent.com/38972672/55066592-113ea200-50b9-11e9-8b25-f0075c301bc3.png)

**Maybe the same problem will happen in Bpmn properties parts,i'm looking for it.**

**Comment by nikku** [comment]
Thanks for raising this issue.

We have an open pull-request that should fix this: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/295.

**Comment by 919980059** [comment]
> Thanks for raising this issue.
> 
> We have an open pull-request that should fix this: #295.

![image](https://user-images.githubusercontent.com/38972672/55122792-22c88e00-513b-11e9-9c14-8d970453c6d5.png)
Hi nikku!
I found the same problem in the general Utils,but i don't konw how to  pass translate as input to 
validation functions in a js way,I‘m more familiar with TS and angular.

**Comment by nikku** [comment]
Should be merged / fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/295.
