### ISSUE TITLE
Error Messages Not Translated

### ISSUE THREAD

**Issue by 919980059** [bpmn-io/bpmn-js-properties-panel#300]
![image](https://user-images.githubusercontent.com/38972672/57439154-ffcfe480-7277-11e9-826f-36e0f0623014.png)
In Utils.js and maybe some easily overlooked places,no translate module or forget to translate the description.

**Comment by barmac** [comment]
Thank you for opening the issue. Please feel free to create a pull request fixing this. Read [the contributing rules](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/.github/CONTRIBUTING.md) beforehand so that your contribution does not need any additional work to be merged.
