### ISSUE TITLE
React integration error

### ISSUE THREAD

**Issue by kollerdroid** [bpmn-io/bpmn-js-properties-panel#308]
I am trying to add this module to my React app.
I managed to integrate the Modeler component following your example about Viewer.

### Expected Behavior
It should be work with React as in case of Viewer and Modeler components.

### Actual Behavior
Getting an error message after adding _propertiesPanelModule_ to _additionalModules_ option.

### Steps to reproduce the Behavior

````ts
const canvas = canvasRef.current;
const panel = panelRef.current;
let bpmn = new Modeler({
  container: canvas,
  propertiesPanel: {
    parent: panel
  },
  additionalModules: [
    propertiesPanelModule, // Getting an error, after adding this
    propertiesProviderModule
  ]
});
return (
  <div className="content with-diagram">
    <div className="canvas" ref={canvasRef} />
    <div className="properties-panel-parent" ref={panelRef} />
  </div>
);
````

````js
Diagram.js:32 Uncaught (in promise) TypeError: Cannot read property '__depends__' of undefined
    at visit (Diagram.js:32)
    at Array.forEach (<anonymous>)
    at visit (Diagram.js:32)
    at Array.forEach (<anonymous>)
    at bootstrap (Diagram.js:45)
    at createInjector (Diagram.js:82)
    at Modeler.Diagram (Diagram.js:138)
    at Modeler.Viewer._init (Viewer.js:568)
    at Modeler.Viewer (Viewer.js:151)
    at new Modeler (Modeler.js:129)
````

**Comment by nikku** [comment]
`propertiesPanelModule` does not seem to be defined.

Please verify this:

```console.log(propertiesPanelModule, propertiesProviderModule);```

**Comment by kollerdroid** [comment]
Both of them is defined:
````ts
{__depends__: Array(2), __init__: Array(1), propertiesPanel: Array(2)}propertiesPanel: Array(2)0: "type"1: ƒ PropertiesPanel(config, eventBus, modeling, propertiesProvider, commandStack, canvas)length: 2__proto__: Array(0)__depends__: Array(2)0: {__init__: Array(1)}1: undefinedlength: 2__proto__: Array(0)__init__: Array(1)0: "propertiesPanel"length: 1__proto__: Array(0)__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() {__init__: Array(1), propertiesProvider: Array(2)}propertiesProvider: (2) ["type", ƒ]__init__: ["propertiesProvider"]__proto__: Object
````

**Comment by nikku** [comment]
Did you manage to resolve the issue?

**Comment by kollerdroid** [comment]
Not yet :-(
Many thanks for your support!

**Comment by kollerdroid** [comment]
I managed to resolve the issue.
I had to create 2 small changes to make it work:

**Diagram.js** (_line 28_):
```ts
if (hasModule(m)) { //->
if (!m || hasModule(m)) {
```
I don't know why but one time `m` is `undefined`...

**PropertiesPanel.js** (_line 24_):
```ts
var scrollTabs = require('scroll-tabs').default;  //->
var scrollTabs = require('scroll-tabs').default || require('scroll-tabs');
```
This is because I use rollup for creating the bundle.

@nikku Please check it, thank you!

**Comment by nikku** [comment]
This is probably an issue with your setup. Glad you were able to fix it.

**Comment by nikku** [comment]
One day maybe the properties panel will be migrated to ES modules. Until that is the case it will continue to consume ES-modules in weird ways. That may be a problem in certain setups, especially strict Rollup setups.

You can always bundle a pre-packaged version of the BPMN editor that includes the properties panel. For the official version we recommend Rollup, for a combined version with the properties panel we recommend Webpack as that is the bundler we fully support. 

Cf. https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-bundle
