### ISSUE TITLE
Unnatural default import usage

### ISSUE THREAD

**Issue by kollerdroid** [bpmn-io/bpmn-js-properties-panel#309]
You use default import/export features in some places as unnatural way which causes problems at runtime.

**node_modules/bpmn-js-properties-panel/lib/Utils.js**
Ids = require('ids').default;

**node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js**
var scrollTabs = require('scroll-tabs').default;

### Expected Behavior
You should not add the 'default' name to the require statement because default export name is not equals with 'default'.
```ts
Ids = require('ids').default; //There is no 'default' named method in 'ids' module
Ids = require('ids');  //This would be the correct way of importing a default export
```
### Actual Behavior
You add 'default' name to require statement to import the default export from other module.
The bundled code throws an error because 'default' method not found:
```js
Ids$2 = Ids$1.default;  //Causes error
Ids$2 = Ids$1.default || Ids$1;  //Standard way works
```
![image](https://user-images.githubusercontent.com/37207139/61950894-94acc900-afaf-11e9-8bf6-de4214762392.png)

### Steps to reproduce the Behavior
Error always comes for me until I do not change the require statement as:
```ts
// Ids = require('ids').default;
Ids = require('ids').default || require('ids');  //Workaround for the standard way

//var scrollTabs = require('scroll-tabs').default;
var scrollTabs = require('scroll-tabs').default || require('scroll-tabs');
```

Webpack probably has a resolution for it but Rollup doesn't.
I don't want to touch your code in node_modules.
Please do this little changes or provide a nice way to resolve this problem.

Thank You!

**Comment by nikku** [comment]
Please share a setup with us that allows us to reproduce the issue you're seing.

**Comment by kollerdroid** [comment]
[bpmn-js-properties-panel-demo.zip](https://github.com/bpmn-io/bpmn-js-properties-panel/files/3446297/bpmn-js-properties-panel-demo.zip)

You can find the details in the README.md.

**Comment by nikku** [comment]
Thank you for sharing the example setup. Using it I was able to to reproduce the issues you're seeing. 

As [commented on your original issue](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/308#issuecomment-518232175), we suggest you to build a pre-packaged distribution of the BPMN editor using webpack that you can then consume in your app (via Rollup). We won't support Rollup until we decide to port the properties panel to ES modules.

**Comment by nikku** [comment]
We could fix the two issues you mention here, we won't be able to fix [this one](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/308#issuecomment-505020061) though, which is bigger than you may think it is.

**Comment by nikku** [comment]
I'm closing this issue, as we won't properly support Rollup for bundling any time soon.
