### ISSUE TITLE
Is it possible to edit Activiti-related properties

### ISSUE THREAD

**Issue by lshz0088** [bpmn-io/bpmn-js-properties-panel#310]
### Expected Behavior
Activiti-related properties can be edited.

### Actual Behavior
// make camunda prefix known for import, editing and export
  moddleExtensions: {
    camunda: camundaModdleDescriptor
  }

**Comment by lshz0088** [comment]
like this:
![image](https://user-images.githubusercontent.com/27722002/62194210-0029d880-b3ac-11e9-9144-250843a8a445.png)

**Comment by lshz0088** [comment]
**This is what is being generated.**
**I added activiti schema myself**

![image](https://user-images.githubusercontent.com/27722002/62194316-36675800-b3ac-11e9-8eae-644538aa7b60.png)

**Comment by nikku** [comment]
It is not possible to edit Activiti related properties. It is also beyond the scope of what we can support.

Maybe there is an extension out there that adds support for the `activiti` namespace. I'm not aware of one. You may be better of asking that question in the Activiti community forum, if there is one.
