### ISSUE TITLE
tests partly failing

### ISSUE THREAD

**Issue by asoahc** [bpmn-io/bpmn-js-properties-panel#312]
Hi,

I try to run the tests of bpmn-js-properties-panel und get some ideas for tests of my customized properties-panel. I am able to start the tests in my environment, but all tests the folder test/spec/provider are failing with following error message:

"No provider for "propertiesPanel"! (Resolving: labelSupport -> attachSupport -> propertiesPanel)"

All other tests in factory or helper folder are running.

Could you check this?

Best regards,
aSoahc

**Comment by nikku** [comment]
Could you provide us with the exact setup and run instructions (command line) you use to reproduce the issue?

**Comment by asoahc** [comment]
Hi Nikku,

I took the new version 0.31 and run executed "karma start"
The results attached as file.

[propertiesPanelTest.log](https://github.com/bpmn-io/bpmn-js-properties-panel/files/3475574/propertiesPanelTest.log)

![image](https://user-images.githubusercontent.com/22494340/62599861-a36b7800-b8ed-11e9-845f-7459820a2eff.png)

But it is not failing for all tests. Utils, factory/EntryFieldDescription and implementation type are running fine.

Best Regards,
aSoahc

**Comment by asoahc** [comment]
As setup instructions: I just download this version and run npm install.
My operating system is Win 10 and I am working with VS Code.

**Comment by pinussilvestrus** [comment]
Do you use `karma start` directly, with your globally installed karma?

Why not using `npm test` or even `npx karma start` instead?

**Comment by asoahc** [comment]
Hi Pinus,

i used "npm test".

**Comment by nikku** [comment]
The following does work absolutely fine for me:

```bash
git clone git@github.com:bpmn-io/bpmn-js-properties-panel.git
cd bpmn-js-properties-panel
npm install
npm run all
```

**Comment by nikku** [comment]
Please verify the above commands fail for you. If that is the case we re-open this issue and continue the investigation.

**Comment by asoahc** [comment]
Hi Nikku,
thank you very much. Now the tests are running fine.
That are a hugh amount of tests.

Now I am thinking how to bring bpmn-js-integration tests together with the properties-panel tests.
Because I have a customized bpmn-js modeler with extended properties-panel and finally I would like to run (maybe not all) the tests against my stuff.
Maybe I will come back with further questions.  

Best Regards,
aSoahc
