### ISSUE TITLE
Line breaks in EntryFieldDescriptions are not working in v0.31.0 or later 

### ISSUE THREAD

**Issue by AndrewBaliushin** [bpmn-io/bpmn-js-properties-panel#315]
__Describe the Bug__

After implementation of #296 (Included in release v0.31.0) it's no longer possible to use line breaks (&lt;br&gt; tag) in EntryFieldDescription. 

__Expected Behavior__

`EntryFactory#textField(options)` with
`options.description = "first line<br>second line"`
produces two line description: 
```
    first line 
    second line
```

__Actual Behavior__

Because of html character sanitization produces 
`first line<br>second line`
![image](https://user-images.githubusercontent.com/9324257/63260726-62c71380-c28a-11e9-9b7c-ce496b880642.png)

__Steps to reproduce the Behavior__

Use `EntryFactory#textField(options)` with `options.description = "first line<br>second line"`

__Tasks__

* [ ] `<br>` and `<br\s/>` yields newlines

**Comment by nikku** [comment]
We will restore the ability to model new lines via `<br>` .

**Comment by nikku** [comment]
It was not documented but is a valid feature :wink:.
