### ISSUE TITLE
Use independent prefixes in property providers

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#316]
We use the `camunda` prefix for _all_ our bpmn property entries when creating them via our factorys, e.g. [`TextInputEntryFactory`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/TextInputEntryFactory.js#L41). 

![image](https://user-images.githubusercontent.com/9433996/64525624-90d7ca80-d301-11e9-821d-7cbcc47b6e84.png)

This way it could be very confusing that these entries have a `camunda` prefix, despite the fact they don't belong to the Camunda engine. In the `CamundPropertiesProvider` [we use the `cam` prefix](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/parts/ConditionalProps.js#L33).

### Expected Behavior

Suggestion: we only use the prefix to prevent ID clashes.

Make the prefixes clearer by avoiding a misleading namespace. Furthermore, use a unique identifier for each properties panel instance

`id="{PROPERTIES_PANEL_INSTANCE_ID}_{suffix}"`

### Additional Context

Related by https://github.com/zeebe-io/zeebe-modeler/issues/90

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
