### ISSUE TITLE
Modification to bpmn-js-properties-panel

### ISSUE THREAD

**Issue by prabhushan** [bpmn-io/bpmn-js-properties-panel#318]
Hi,
I want to extend bpmn-js-properties-panel to add my own provider. As a first step,I just made a version change and wanted to install in my local machine.
I did npm run build and npm install in my bpmn-js-properties-panel folder.

In my parent project (angular) I did **npm install <path to bpmn-js-properties-panel in my local folder>**

When I start my angular project , I do not see any errors but I dont see the complete panel

![image](https://user-images.githubusercontent.com/4810069/66648017-6c208c80-ebf8-11e9-9cf7-a3cefdb0614e.png)

Please help

**Comment by pinussilvestrus** [comment]
It's hard to help you without knowing your project. Would you be you able to share your setup?

**Comment by philippfromme** [comment]
1. Have you included the stylesheet for the properties panel? Here's an example: https://codesandbox.io/s/bpmn-js-custom-modeler-senuf

2. The [bpmn.io forum](https://forum.bpmn.io/) is a better place for general questions.

**Comment by pinussilvestrus** [comment]
@prabhushan did this solved your issue?

**Comment by pinussilvestrus** [comment]
Let's close this for now since there seem to be no real issue. @prabhushan feel free to re-open if you have further problems, or just refer to our forum.
