### ISSUE TITLE
A pre-packaged version and an example on how to use it without node.js would help me too

### ISSUE THREAD

**Issue by 1weidong** [bpmn-io/bpmn-js-properties-panel#340]
__Is your feature request related to a problem? Please describe__

__Describe the solution you'd like__

__Describe alternatives you've considered__

__Additional context__

**Comment by philippfromme** [comment]
This is not how you use GitHub issues. Stick to our [forum](https://forum.bpmn.io/t/the-properties-panel-does-not-display/5044) for questions. There will be no pre-packaged properties panel.
