### ISSUE TITLE
Add ability to extract process variables (and their scope) from given diagram

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#342]
__Is your feature request related to a problem? Please describe__

As part of our "Smart Low-Code" MVP we want to have a functionality to extract process (and subprocess) variables from a given diagram (cf. https://github.com/bpmn-io/internal-docs/issues/148). 

Variables can be related to a specific scope. With this iteration, we only deal with process and sub process variables. We have to make sure, the extracted variables are related to the correct scope. Correct means here to set the scope for the highest scope in which the given variable is available. Consider cases from [this example file](https://github.com/bpmn-io/bpmn-js-properties-panel/files/5027977/example-vars.bpmn.txt).

A more advanced example can be found [here](https://docs.google.com/presentation/d/1BGJ0oZMoAmXfibvHy0gCpuj2HVkQWkWtnBmiqqx9D9o/edit?usp=sharing).

__Describe the solution you'd like__

Create util that collects all available process variables for the current diagram / the root element / any given container (?). Currently, the only way to indicate a _reliable_ process variable is from `camunda:outputParameter` properties. This might change if we're going to implement the ability to declare process start variables (cf. [Variable Management Prototype](https://rpa-prototypes.netlify.app/variable-management-new/)).

The [concept of process variable](https://docs.camunda.org/manual/latest/user-guide/process-engine/variables/) is tightly coupled to the Camunda Engine, so it makes sense to make it available in the [Camunda Properties Provider](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/master/lib/provider).

Things to extract for each variable.
* Name
* Origin / Written from (multiple places?)
* Scope (in which the variable is available)

Additionally, we can store the places where the variable is read, but maybe not in this iteration.

The util will be built inside a standalone module which can then be integrated inside the properties panel.

__Describe alternatives you've considered__

/
__Additional context__

Child of https://github.com/bpmn-io/internal-docs/issues/148.
Related to [Variable Management Prototype](https://rpa-prototypes.netlify.app/variable-management-new/).

**Comment by pinussilvestrus** [comment]
Cases from example file

## Case 1 - Example 1: Variable in global + subprocess

![image](https://user-images.githubusercontent.com/9433996/89405393-c35d9380-d71b-11ea-89ae-f499278eba44.png)

<details>
  <summary>BPMN 2.0 XML</summary>

  ```xml
  <bpmn:process id="Process_1xc2901" isExecutable="false">
    <bpmn:task id="Activity_0ttnd70" name="LookAtMe">
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:outputParameter name="var">fooBar</camunda:outputParameter>
        </camunda:inputOutput>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1iam392</bpmn:incoming>
      <bpmn:outgoing>Flow_1e9u4jn</bpmn:outgoing>
    </bpmn:task>
    <bpmn:dataObjectReference id="DataObjectReference_1pr82yc" name="var is available here" dataObjectRef="DataObject_15i8wb1" />
    <bpmn:dataObject id="DataObject_15i8wb1" />
    <bpmn:subProcess id="Activity_02wxdb2" name="var is available here">
      <bpmn:incoming>Flow_1e9u4jn</bpmn:incoming>
      <bpmn:outgoing>Flow_1nwkrxq</bpmn:outgoing>
      <bpmn:startEvent id="Event_1idvqs9">
        <bpmn:outgoing>Flow_0ypur88</bpmn:outgoing>
      </bpmn:startEvent>
      <bpmn:task id="Activity_1qcbv1g">
        <bpmn:incoming>Flow_0ypur88</bpmn:incoming>
        <bpmn:outgoing>Flow_0en2m9w</bpmn:outgoing>
      </bpmn:task>
      <bpmn:sequenceFlow id="Flow_0ypur88" sourceRef="Event_1idvqs9" targetRef="Activity_1qcbv1g" />
      <bpmn:endEvent id="Event_0e2g4zz">
        <bpmn:incoming>Flow_0en2m9w</bpmn:incoming>
      </bpmn:endEvent>
      <bpmn:sequenceFlow id="Flow_0en2m9w" sourceRef="Activity_1qcbv1g" targetRef="Event_0e2g4zz" />
    </bpmn:subProcess>
    <bpmn:startEvent id="Event_0pp5byy">
      <bpmn:outgoing>Flow_1iam392</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:task id="Activity_1khqi5h">
      <bpmn:incoming>Flow_1nwkrxq</bpmn:incoming>
      <bpmn:outgoing>Flow_0pfmbh2</bpmn:outgoing>
    </bpmn:task>
    <bpmn:endEvent id="Event_050vyup">
      <bpmn:incoming>Flow_0pfmbh2</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0pfmbh2" sourceRef="Activity_1khqi5h" targetRef="Event_050vyup" />
    <bpmn:sequenceFlow id="Flow_1nwkrxq" sourceRef="Activity_02wxdb2" targetRef="Activity_1khqi5h" />
    <bpmn:sequenceFlow id="Flow_1e9u4jn" sourceRef="Activity_0ttnd70" targetRef="Activity_02wxdb2" />
    <bpmn:sequenceFlow id="Flow_1iam392" sourceRef="Event_0pp5byy" targetRef="Activity_0ttnd70" />
  </bpmn:process>
  ```
</details>

**Available Variables**

a) for process

| variable name | written in  |  scope  |
|---|---|---|
|  var  | LookAtMe  | process  |

**Comment by pinussilvestrus** [comment]
Result of Kickoff (6th August):
* We going to build this as a standalone module for better reusability.

**Comment by pinussilvestrus** [comment]
Work is happening inside this project: https://github.com/bpmn-io/extract-process-variables

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/extract-process-variables

**Comment by Kimbo0o** [comment]
Very useful feature. Is it possible to get the scope of an element, e.g. of a task as well? I would like to generate a list of variables available to a task.
