### ISSUE TITLE
Consistently refuse non QName process ids

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#346]
__Describe the Bug__

See https://github.com/zeebe-io/zeebe-modeler/issues/237, raised by [@ajeans](https://github.com/ajeans)

__Steps to Reproduce__

1. Create a new BPMN
2. Add a call activity to it, with process-id "123"
3. Save the BPMN
4. Create a second BPMN
5. Define its id as "123"

__Expected Behavior__

If QName is indeed mandatory for process-ids, it should also be enforced in the details of the call activity.

__Environment__

OS: Ubuntu 20.04
Zeebe Modeler Version: 0.9.1

**Comment by imrishabh18** [comment]
@MaxTru I want to take up this😄. Can you guide me how to resolve this issue?

**Comment by MaxTru** [comment]
Dear @imrishabh18 ,

this is a great issue to start contributing to bpmn-io :-)

Please feel free to create a Pull Request to resolve this issue. When doing that, please follow our [contribution guidelines](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/.github/CONTRIBUTING.md). 

For this particular issue (I just had a quick look, bare with me if I missed something):
* There is a validation already implemented (https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/Utils.js#L169) and I would assume it can be re-used
* This validation is already used for the Id field (https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/bpmn/parts/IdProps.js#L35)
* To resolve https://github.com/zeebe-io/zeebe-modeler/issues/237, we would also need to add that validation in zeebe modeler (https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/app/tabs/bpmn/custom/properties-provider/parts/CallActivityProps.js)

Therefore I actually think we can close this issue here without any change and just to the change based on this one:  https://github.com/zeebe-io/zeebe-modeler/issues/237

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
