### ISSUE TITLE
Improve Process Variables Overview

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#348]
__Is your feature request related to a problem? Please describe__

The current implementation offers every information we need (name, createdIn, scope), but it's just a first iteration from the design perspective.

![image](https://user-images.githubusercontent.com/9433996/93865959-569c5980-fcc7-11ea-8ffe-8b0e69434499.png)

For example, when the process variables list is empty, the layout is kind of weird currently.

![image](https://user-images.githubusercontent.com/9433996/90394467-0102da80-e093-11ea-912a-7672d427198a.png)

__Describe the solution you'd like__

Improve the UI. Cf. to this [Zeplin file](https://zpl.io/a8M3AWd) for instructions.

__Describe alternatives you've considered__

/

__Additional context__

Changes were introduced with #343. 
Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349.

**Comment by johnjacobkenny** [comment]
@pinussilvestrus Is there a recommended way to add all the process variables to the model using camunda modeler?

**Comment by pinussilvestrus** [comment]
What do you mean with _all process variables_? Are you also refer to variables not initiated in the diagram, but in the implementation/process start/ ...? 

[Here you can find a list](https://github.com/bpmn-io/extract-process-variables/blob/master/README.md#properties-support) of what kind of variables we are currently collecting from the diagram. We plan to increase this in the future to make it possible to specify variables without an actual implementation in the diagram (e.g. via documentation).

**Comment by johnjacobkenny** [comment]
Yes @pinussilvestrus that list helps. 

As you mention in your last sentence, I meant exactly to specify which all variables may be expected as a means of upfront documentation, which would then be available through the modeller as autocomplete for variables

e.g. conditional start event (`#{variableToTriggerConditionalStartEvent}`) or `${execution.setVariable("variableToTriggerConditionalStartEvent", true)}`

**Comment by pinussilvestrus** [comment]
Yes exactly, this documentation approach is in the scope of our future work which should make it easier to increase the number of usable variables.
