### ISSUE TITLE
Improved Input/Output variable mapping component is implemented and can be used in the properties panel

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#349]
__Is your feature request related to a problem? Please describe__

We want to support the user when working with process variables. As part of this, the user shall be able to perform the input/output mapping more easily.

This feature covers the implementation of a new UI component which replaces the existing input/output mapping (which is implemented as list).

This component will then be used in the properties panel in multiple places
* General Input/Output tab for tasks
* Simplified property panel for tasks with applied element templates (see https://github.com/camunda/camunda-modeler/issues/1894)

__Describe the solution you'd like__

The current component looks like this:
![Screenshot_20200818_120611](https://user-images.githubusercontent.com/42800119/90500481-3c60e000-e14b-11ea-8393-b8c52908a165.png)

The target state of the new component can be found on [Zeplin](https://zpl.io/VKMepB7).

__Describe alternatives you've considered__

See [Zeplin](https://zpl.io/VKMepB7)

__Additional context__

Child of https://github.com/bpmn-io/internal-docs/issues/148
Required for https://github.com/camunda/camunda-modeler/issues/1894

**Comment by barmac** [comment]
So it occurs that we can't really nest entries in entries. I am leaving the implementation based on \<details> on [this branch](https://github.com/bpmn-io/bpmn-js-properties-panel/tree/349-implement-details-component) and will start over with other approach.

**Comment by philippfromme** [comment]
As part of implementing this new component, we will have to add a new property to `camunda-bpmn-moddle` to save the description unless we want to use the `bpmn:documentation` field for this purpose.

![image](https://user-images.githubusercontent.com/7633572/92096169-dc1e9f00-edd6-11ea-8dff-45bee499072e.png)

**Comment by pinussilvestrus** [comment]
We won't add this new description field until we don't clarify the overall concept, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/350#issuecomment-688660386.
