### ISSUE TITLE
The property camunda:variableEvent should be camunda:variableEvents

### ISSUE THREAD

**Issue by runi95** [bpmn-io/bpmn-js-properties-panel#355]
__Describe the Bug__

The camunda property field `camunda:variableEvent` for a conditional event is not recognized by Camunda because `camunda:variableEvents` is expected.

__Steps to Reproduce__

1. Create a conditional event
2. Modify the "Variable Event" property field
3. See that the resulting bpmn xml file ends up with the property `camunda:variableEvent` which is not recognized by Camunda

__Expected Behavior__ 

The expectation is something like this:
```
<bpmn:conditionalEventDefinition id="ConditionalEventDefinition_0wm7q4o" camunda:variableName="onlyOnUpdate" camunda:variableEvent="update">
    <bpmn:condition xsi:type="bpmn:tFormalExpression">${true}</bpmn:condition>
</bpmn:conditionalEventDefinition>
```

__Environment__

- Host (Browser/Node version), if applicable:  camunda-modeler
- OS: Manjaro Linux 20.1
- Library version: 0.35.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting. I guess this related to https://github.com/camunda/camunda-modeler/issues/836.

**Comment by prithviraj-maurya** [comment]
Would like to work on this
