### ISSUE TITLE
Emit events for changing values inside a form-element (e.g input-output values)

### ISSUE THREAD

**Issue by Felix-Staud** [bpmn-io/bpmn-js-properties-panel#356]
__Is your feature request related to a problem? Please describe__

I've tried to react to changes of a specific I/O value inside the properties-panel I/O tab.
Unfortunately the only event I could use at the end was the `elements.changed` event from bpmn-js which is a bit of an overkill.

__Describe the solution you'd like__

The form-elements (e.g. the simple input) should emit events to the bpmn-js eventBus.
For example on `input` event emit could look like this:
```javascript
// [...]
this._eventBus.fire('propertiesPanel.inputOutputTab.change', {
    param: /*...*/,
    value: /*...*/, 
    oldValue: /*...*/,
    
   // (maybe some more options)
}
// [...]
```

__Describe alternatives you've considered__

For now I'm using the `elements.changed` event but this is an overkill since i have to loop through the changed elements everytime because i wanna check if the single value I'm watching was changed

**Comment by pinussilvestrus** [comment]
What we're currently doing is to execute this generic change command on any change event (in case something is changed): https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/PropertiesPanel.js#L715, https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/PropertiesPanel.js#L552. 

There were no more events/commands needed, but I see the point of having a more specific change event. We're open to contributions to improve the situation.

**Comment by philippfromme** [comment]
I don't think we're going to build anything like this in the near future. In the meantime, instead of listening to `elements.changed` you can also listen to `commandStack.properties-panel.update-businessobject-list.postExecuted`:

```javascript
eventBus.on(
  "commandStack.properties-panel.update-businessobject-list.postExecuted",
  ({ context }) => {
    const { objectsToAdd } = context;

    const inputParameters = objectsToAdd.filter(object => is(object, 'camunda:InputParameter'));

    console.log(inputParameters);
  }
);
```

This way you could at least avoid listening to every `elements.changed` event.

**Comment by Felix-Puetz** [comment]
@philippfromme that sounds like a way cleaner and less overkill approach.

thanks for the quick answer 👍
