### ISSUE TITLE
Allow usage of improved input output parameter mapping component in element template view

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#358]
__Is your feature request related to a problem? Please describe__

We want to support the user when working with process variables and mapping these to input / output parameters. As part of this, the user shall be able to perform the input/output mapping more easily.

This feature covers the integration of the new UI component (see https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349) in the element template view (ie. the view in the properties panel after an element template was applied).

This affects the `camunda:inputParameter` and the `camunda:outputParameter` bindings in the `<elementTemplateConfig>.json`. 

__Describe the solution you'd like__

In the current state the user might configure an element template for `camunda:inputParameter` and `camunda:outputParameter` as following:
```
      {
        "label": "Some input var",
        "type": "String",
        "value": "${varA}",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "someInputVar"
        }
      }
```
(Notice that in the following section when talking about `type` the third line of the above snippet is meant [and not the binding type]).
Hereby the `type` may be one of the following: `String`, `Text`, `Hidden`, `Dropdown` (`Boolean` doesnt make sense). This existing functionality **shall not be changed**.

In the target state, the new Input Output Parameter Mapping component (see #349) shall be rendered in the element template view (ie. the view in the properties panel after having applied an element template) **(1) if the binding is `camunda:inputParameter` or `camunda:outputParameter` and (2) if no type is specified in the `<...>.json`**. (Idea behind: the user UI component *defaults* to the default component).

If no type is specified in the `<...>.json` and the binding is one of the following: `property`, `camunda:property`, `camunda:in`, `camunda:in:businessKey`, `camunda:out`, `camunda:field`, **the rendered component shall default to `String`**.

If no type is specified in the `<...>.json` and the binding is `camunda:executionListener`, **the rendered component shall default to `Hidden`**.

If the new Input Output Paramter Mapping component is rendered, it shall be rendered in the Input Paramter, Output Parameter section (See [zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/5f3d4a24fe86422d21252e45))

If a `description` is provided, it shall be rendered as specified in zeplin.

__Describe alternatives you've considered__

n/a

__Additional context__

See [zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/5f3d4a24fe86422d21252e45)

**Comment by pinussilvestrus** [comment]
Additional Topic to consider once we finish the general implementation: How to implement a toggle like this

![image](https://user-images.githubusercontent.com/9433996/93178627-c7c29680-f734-11ea-9d7a-48696b2729db.png)

So the user can choose whether to _use_ the variable or not.

**Comment by MaxTru** [comment]
@pinussilvestrus Could we also handle the update of the documentation (see https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates) as part of this issue or shall we have a separate one?

**Comment by pinussilvestrus** [comment]
I'd rather update the documentation at once (also including the new element template view, apply / unlink, ..) in a separate issue in the Camunda Modeler.

**Comment by MaxTru** [comment]
Issue to update the documentation: https://github.com/camunda/camunda-modeler/issues/1945
