### ISSUE TITLE
`editable` configuration has no impact when using default `type` rendering for `camunda:inputParameter` or `camunda:outputParameter`

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#376]
__Describe the Bug__

`editable` configuration has no impact when using default `type` rendering for `camunda:inputParameter` or `camunda:outputParameter`.

Example:
```json
{
    "name": "Mail Task",
    "id": "com.camunda.example.MailTask",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
     {
        "label": "Template",
        "description": "By the way, you can use <a href=\"https://freemarker.apache.org/\">freemarker templates</a> here",
        "value": "Hello ${firstName}!",
        "editable": "false",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "messageBody",
          "scriptFormat": "freemarker"
        }
      }
    ]
  }
```

__Steps to Reproduce__

1. Use the above element template
2. Apply to element
3. Now this happens => I can still edit the inputParameter value
![Screenshot_20201001_181921](https://user-images.githubusercontent.com/42800119/94835943-a939ec00-0412-11eb-9044-f029426cdc89.png)

__Expected Behavior__

We need to decide what to do: 
(A) either we explicitly don't support `editable` for the default rendering (e.g., by highlighting this in the docs) **or** 
(B) we support it (which would also require us to add another config-option for the `type` dropdown in the UI and think about dealing with this when selecting `List` or `Map`).

__Environment__

- Host (Browser/Node version), if applicable: Camunda Modeler 30092020 on Manjaro Linux
- Library version: develop branch

**Comment by pinussilvestrus** [comment]
```json
 "properties": [
     {
        "label": "Template",
        "description": "By the way, you can use <a href=\"https://freemarker.apache.org/\">freemarker templates</a> here",
        "value": "Hello ${firstName}!",
        **"type": "Text",**
        "binding": {
          "type": "camunda:inputParameter",
          "name": "messageBody",
          "scriptFormat": "freemarker"
        },
        "constraints": {
          "notEmpty": true
        }
      }
    ]
```

Declaring the type won't render the default component.

**Comment by MaxTru** [comment]
Copied the wrong template, updated the description

**Comment by MaxTru** [comment]
At least for the October release - we will go for (A). I will adjust the docs accordingly.
