### ISSUE TITLE
`constraints` configuration has no impact `camunda:inputParameter` or `camunda:outputParameter`

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#377]
__Describe the Bug__

`constraints` configuration has no impact `camunda:inputParameter` or `camunda:outputParameter`.

Example:
```json

[
  {
    "name": "Mail Task1",
    "id": "com.camunda.example.MailTask1",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "label": "Sender",
        "editable": false,
        "binding": {
          "type": "camunda:inputParameter",
          "name": "sender"
        },
        "constraints": {
          "notEmpty": true,
          "pattern": {
            "value": "^[A-z0-9._%+-]+@[A-z0-9.-]+\\.[A-z]{2,}$",
            "message": "Must be a valid email."
          }
        }
      }
    ]
  }
]

```

__Steps to Reproduce__

1. Use the above template
2. Apply to service task
3. See that `contraints` has no impact

__Expected Behavior__

Element template configurations should have consistent impact IMO.

We could either
(A) Make it explicit that `constraints` is not supported **or**
(B) Implement the constraints behaviour for the default rendering 

(B) might be difficult since we would also need to think about constraints would work with the valid dropdown-type selections `List` or `Map`. So I would argue for (A)

__Environment__

- Host (Browser/Node version), if applicable: Camunda Modeler Nightly 30092020 on Manjaro Linux
- Library version: develop branch

**Comment by pinussilvestrus** [comment]
I'd also argue for (A).

**Comment by MaxTru** [comment]
At least for the October release - we will go for (A). I will adjust the docs accordingly.
