### ISSUE TITLE
Autosuggest: Close expression after applying a suggested variable

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#378]
__Is your feature request related to a problem? Please describe__

We offer auto-suggesting of available process variables when creating expressions in input mappings. One feature we offer on top is that we [also suggesting those items if the user starts typing an expression](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/parts/implementation/InputOutputParameter.js#L452) (`${`), without closing bracket.

![Kapture 2020-10-02 at 13 20 21](https://user-images.githubusercontent.com/9433996/94918041-0afd6300-04b2-11eb-88de-405455653760.gif)

However, after the variable got applied to the input, the expression is not valid in this case due to the missing closing bracket. The user would have to add it afterward on his own.

It would be nice if we could support the user by automatically adding this.

__Describe the solution you'd like__

Add closing bracket (`}`) after a suggestion item got applied, in case (and only in case) the user is typing inside[ an unclosed expression](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/parts/implementation/InputOutputParameter.js#L452). The cursor should be still on the position after the inserted item.

__Describe alternatives you've considered__

* Adding a warning hint, if the expression is unclosed (?)
* We could also make this completely independent to the auto-suggesting, and simply add the closing bracket once a starting clause was typed (without the action of auto-suggesting). We should handle this issue when talking about the JUEL expression code editor in the next steps.

**Comment by andreasgeier** [comment]
I would not combine a variable suggestion overlay with auto-addding closing brackets. Where is the relation? I would see this as part of the effort the replace simple textareas with a code editor view where we can think about such typical features like adding a closing bracket when you type in the opening bracket etc.

**Comment by pinussilvestrus** [comment]
Valid point @andreasgeier, I added this to the alternatives. We will then see, how to deal with that.

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
