### ISSUE TITLE
Test `1) should not ignore <a> if br used within URL field` fails on ChromeHeadless

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#385]
__Describe the Bug__

One test fails when running the testsuite on `ChromeHeadless`

__Steps to Reproduce__

1. Run tests on `ChromeHeadless`

```
1) should not ignore <a> if br used within URL field
     factory/EntryFieldDescription escaping
     AssertionError: expected '<a href="https://test<br />website.com" target="_blank"> HELLO <br> WORLD </a>' to equal '<a href="https://test&lt;br /&gt;website.com" target="_blank"> HELLO <br> WORLD </a>'
    at Context.eval (webpack:///./test/spec/factory/EntryFieldDescriptionSpec.js?:226:65)
```

__Expected Behavior__

Test succeeds on `ChromeHeadless`

__Environment__

- Host (Browser/Node version), if applicable: `ChromeHeadless`
- OS: Arch Manjaro Linux
- Library version: v0.37.2

__Context__
Also see #384

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
