### ISSUE TITLE
Validate element templates and handle errors accordingly.

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#386]
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

Currently there is only a rudimentary validation of element templates implemented (ie. see [validator.js](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/Validator.js)). Therefore wrong configurations will potentially lead to technical error message in the console.

Therefore this epic shall include:

- [ ] Use https://github.com/camunda/element-templates-json-schema, https://github.com/bpmn-io/json-schema-validator when parsing element templates. This will allow a more extensive validation of templates
- [ ] Ignore invalid templates and inform user accordingly
- [ ] To be decided: do not sync invalid templates from Cawemo (in fact this would probably better be done on Cawemo side - just mentioning it for completness)
- [ ] To be decided (depends on https://github.com/bpmn-io/element-templates-json-schema/issues/5): apply template validation using different schema version based on element template version

(*note that these questions might change based on kickoff / clarification of this issue*)

__Why should we do it?__

See above.

__Context__

Blocked by https://github.com/bpmn-io/element-templates-json-schema/issues/5

**Comment by pinussilvestrus** [comment]
Example of how to integrate the new schema with our new validator: https://github.com/camunda/element-templates-json-schema/tree/master/example#element-templates-json-schema-example

**Comment by philippfromme** [comment]
Miro board with my findings so far: https://miro.com/app/board/o9J_leoG2N0=/

**Comment by MaxTru** [comment]
Moving to backlog since we will not do this as part of OKR Q1 work

**Comment by pinussilvestrus** [comment]
A note regarding

> To be decided (depends on camunda/element-templates-json-schema#5): apply template validation using different schema version based on element template version

We version the schema itself. Every element template (json) can specify the _version_ of the used schema by declaring the `$schema` property, e.g.

Using v0.1.0

`"$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.1.0/resources/schema.json"`

Using v0.2.0

`"$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.2.0/resources/schema.json"`

Using the latest

`$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json"`

Therefore we could consider making the validation in the properties panel agnostic to that and always validate against the specified version.
