### ISSUE TITLE
Check IE Compatibility

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#39]
Check compatibility with internet explorer and compile a list of bugs.

TODO: which internet explorer versions are supported?

**Comment by meyerdan** [comment]
Check compatibility with internet explorer and compile a list of bugs.

TODO: which internet explorer versions are supported?

**Comment by polenz** [comment]
All tests are running with IE 11 and IE 10.
IE 9 is not necessary at the moment.
