### ISSUE TITLE
Is there a way to lose the DOM warning when adding a Property in the Extensions tab?

### ISSUE THREAD

**Issue by nnthanhhuy** [bpmn-io/bpmn-js-properties-panel#407]
__Describe the Bug__

Show error warning when adding
![Untitled73](https://user-images.githubusercontent.com/71427779/103603971-6e2fe300-4f42-11eb-80fe-57e975f490e4.png)

codesanbox: https://codesandbox.io/s/exciting-raman-svwir?file=/src/index.js:827-850 

__Expected Behavior__

I want to remove DOM warnings when adding a Property in the Extensions tab.
Look forward to the help

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 10]
- Library version: [e.g. 2.0.0]

----

Related to [forum post](https://forum.bpmn.io/t/5649).

Further details provided [here](https://forum.bpmn.io/t/5649/2).

**Comment by nikku** [comment]
Do you see any negative impact, functionality wise? Or is this about getting rid of the warnings only?

**Comment by nnthanhhuy** [comment]
As of now, I just want to get rid of warnings. Thanks for the feedback

**Comment by nikku** [comment]
Thanks for the reproduction. We'll move this to backlog and se when we'll be able to work on this one.
