### ISSUE TITLE
`Version` label for element templates: `version` string is duplicated

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#408]
__Describe the Bug__

(Issue was spotted by @barmac 
When applying a template (with metadata) to a task, the Version information label contains the word `version` twice:
![image](https://user-images.githubusercontent.com/42800119/103811512-4aad8b00-505d-11eb-9a88-1e084f1ce471.png)

__Steps to Reproduce__

1. Apply an element template to a task 
2. Check the `Version` label

__Expected Behavior__

Version label is there only once. 

__Environment__

- Camunda Modeler 4.5 RC0 https://github.com/camunda/camunda-modeler/releases/tag/v4.5.0-rc.0
- OS: Mac

**Comment by pinussilvestrus** [comment]
This got also fixed by https://github.com/bpmn-io/bpmn-js-properties-panel/pull/409, right?

![image](https://user-images.githubusercontent.com/9433996/103888533-31502180-50e5-11eb-8ffa-f0a222fdc4b3.png)

**Comment by barmac** [comment]
[Indeed](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/409/commits/b8161d7ff2a29b846f4a83dd1649eb181884e8b4#diff-a6c4c2e9187479e7e6b86a75b1f9bebf09d36054d591dd03dc08124c12593055R60).
