### ISSUE TITLE
Upgrade to bpmn-js version ^8

### ISSUE THREAD

**Issue by aegonz** [bpmn-io/bpmn-js-properties-panel#410]
__Is your feature request related to a problem? Please describe__

When installing this while using bpmn-js version 8 or higher it fails.

__Describe the solution you'd like__

Upgrading the dependency up to version 8

**Comment by pinussilvestrus** [comment]
Can you explain what you mean by "it fails"? Can you share your error log?

**Comment by pinussilvestrus** [comment]
Are you referring to this warning?

> npm WARN bpmn-js-properties-panel@0.38.1 requires a peer of bpmn-js@^3.x || ^4.x || ^5.x || ^6.x || ^7.x but none is installed. You must install peer dependencies yourself.

If yes, #411 will fix this problem by increasing the peer dependency.
