### ISSUE TITLE
Implement new UI component supporting `camunda:errorEventDefinition` for external `ServiceTasks`

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#422]
__What should we do?__

CamBPM will support `camunda:externalEventDefinitions` for external service tasks starting with 7.15. (see [issue](https://jira.camunda.com/browse/CAM-12040)). 

Goal of this issue is, to support defining, editing and deleting `camunda:externalEventDefinitions` for external service tasks.

![Screenshot_20210125_111248](https://user-images.githubusercontent.com/42800119/105692076-46f38280-5efe-11eb-8963-a3012bcf3a5c.png)

In particular:

- [ ] Add a new section "Errors thrown" to the "Input/Output" tab for serviceTasks with implementation==external.
- [ ] Re-use the "list of collapsibles" UI element, we used for input and output parameters
- [ ] The "list of collapsbile" headers shall display `<errorName> (code: <errorCode>) <- <expression>` (note that the expression part shall only be displayed, if an expression is defined and if the item is collapsed.
- [ ] Fields as sketched in the UI
- [ ] Note that some fields modify the referenced global error entity and not the `camunda:errorEventDefinion` per se

__Why should we do it?__

See overall objective https://github.com/camunda/camunda-modeler/issues/2070
Child of camunda/camunda-modeler#2070

**Comment by MaxTru** [comment]
Update to requirements:
As @andreasgeier pointed out correctly, the "Expression" should also have a validation.

@azeghers please investigate whether "must have value" or "must contain valid expression" validation is better from the user perspective.

**Comment by azeghers** [comment]
Noted :+1:

**Comment by azeghers** [comment]
# Testing session with Miklas and Thorben on 2021/03/10 :

### Rough recreation of test case
![image](https://user-images.githubusercontent.com/42282939/111627510-69fc2d80-87ef-11eb-9870-33ba18c9c812.png)

Tested in cockpit with an hardcoded `${true}` throw expression, and with a boolean variable in the external task.
Both resulted in the `camunda:ErrorEventDefinition` being triggered, and the error path was taken.
