### ISSUE TITLE
Scoped bindings: allow "scopes" to be an Array, being backwards compatabile to current concept

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#423]
__What should we do?__

In order to support the configuration of global entities (e.g., `bpmn:error` or `bpmn:message`), we will use scoped bindings (see parent issue). Since one might have multiple of these global entities, we need to adjust the scoped binding implementation. It shall be possible to define scoped bindings as Array (rather than as object). 

This issue only aims at adding the capability to define scoped bindings as Array.

**As-is situation**
```json
...
    "scopes": {
      "camunda:Connector": {
        "properties": [
          {
            "label": "ConnectorId",
            "type": "String",
            "value": "My Connector HTTP - GET",
            "binding": {
              "type": "property",
              "name": "connectorId"
            }
          },
          {
            "label": "Method",
            "type": "String",
            "value": "GET",
            "binding": {
              "type": "camunda:inputParameter",
              "name": "method"
            }
          },
          {
            "label": "URL",
            "type": "String",
            "value": "https://bpmn.io",
            "binding": {
              "type": "camunda:inputParameter",
              "name": "url"
            }
          },
          {
            "label": "Response",
            "type": "String",
            "value": "wsResponse",
            "binding": {
              "type": "camunda:outputParameter",
              "source": "${S(response)}",
              "scriptFormat": "freemarker"
            }
          }
        ]
      }
...
```

**To-be situation**
```json
...
"scopes": [
    {
      "type": "camunda:Connector",
      "properties": [
        {
          "label": "ConnectorId",
          "type": "String",
          "value": "My Connector HTTP - GET",
          "binding": {
            "type": "property",
            "name": "connectorId"
          }
        },
        {
          "label": "Method",
          "type": "String",
          "value": "GET",
          "binding": {
            "type": "camunda:inputParameter",
            "name": "method"
          }
        },
        {
          "label": "URL",
          "type": "String",
          "value": "https://bpmn.io",
          "binding": {
            "type": "camunda:inputParameter",
            "name": "url"
          }
        },
        {
          "label": "Response",
          "type": "String",
          "value": "wsResponse",
          "binding": {
            "type": "camunda:outputParameter",
            "source": "${S(response)}",
            "scriptFormat": "freemarker"
          }
        }
      ]
    }
  ]
...
```

Note that, the *to-be situation* shall be the new default (e.g., in terms of documentation), yet the old format shall be understood (but only for the existing type, which is `camunda:Conncetor`.

Tasks:

- [ ] Allows `scopes` to contain a list of objects, where the `type` property defines the type
- [ ] Implement backwards-compatabile logic so that existing element templates with scoped bindings (only type we suppor as-is is `camunda:Connector`, so only this case needs to be taken care of) are still valid
- [ ] Update [docs and samples](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates)

__Why should we do it?__

See overall objective https://github.com/camunda/camunda-modeler/issues/2070
Child of camunda/camunda-modeler#2070
Overall concept https://miro.com/app/board/o9J_lZ7EwN0=/ (see right side of the board)

**Comment by pinussilvestrus** [comment]
We will have to [update the schema](https://github.com/camunda/element-templates-json-schema/blob/master/resources/schema.json#L533) as well (soon or later) - to be compatible.

**Comment by MaxTru** [comment]
> We will have to [update the schema](https://github.com/camunda/element-templates-json-schema/blob/master/resources/schema.json#L533) as well (soon or later) - to be compatible.

Yep - absolutely. I added this as task in the parent issue https://github.com/camunda/camunda-modeler/issues/2070 (since we have a few child issues about changing element templates)
