### ISSUE TITLE
Implement new element template binding `camunda:errorEventdefinition` 

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#424]
__What should we do?__

Add a new element template binding type `camunda:errorEventDefinition`.

(Note that this issue requires us also to support globalEntities to be defined using element templates [see parent issue](https://github.com/camunda/camunda-modeler/issues/2070))

**Example 1: support user-defined input type `String`**

Element Template Configuration
```json
{
  "name": "eventDefinitionDraft",
  "id": "max.eventDefinitionDraft",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "label": "Error Throw Expression",
      "type": "String",
      "value": "${ true }",
      "binding": {
        "type": "camunda:errorEventDefinition",
        "errorRef": "error1"
      }
    }
  ],
  "scopes": [
    {
      "type": "bpmn:Error",
      "id": "error1",
      "properties": [
        {
          "label": "Error Code",
          "type": "String",
          "value": "GET",
          "binding": {
            "type": "property",
            "name": "errorCode"
          }
        },
        {
          "label": "Error Message",
          "type": "String",
          "value": "My Connector - HTTP GET",
          "binding": {
            "type": "property",
            "name": "camunda:errorMessage"
          }
        },
        {
          "label": "Error Name",
          "type": "String",
          "value": "https://bpmn.io",
          "binding": {
            "type": "property",
            "name": "name"
          }
        }
      ]
    }
  ]
}
```

Resulting XML
```XML
<bpmn:serviceTask ...>
      <bpmn:extensionElements>
        <camunda:errorEventDefinition id="ErrorEventdefintion_13asda3" errorRef="Error_0x9vl7b" expression="${ true }" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_04k3izd</bpmn:incoming>
      <bpmn:outgoing>Flow_1s764or</bpmn:outgoing>
</bpmn:serviceTask>
...
<bpmn:error id="Error_0x9vl7b" name="https://bpmn.io" errorCode="GET" camunda:errorMessage="My Connector HTTP - GET" />
```

Resulting UI
![Screenshot_20210127_155113](https://user-images.githubusercontent.com/42800119/106008355-7e595f00-60b7-11eb-9694-e23202078033.png)

**Example 2: support default rendering when no input type is specified**

Element Template Configuration
```json
{
  "name": "eventDefinitionDraft",
  "id": "max.eventDefinitionDraft",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "label": "errorNameA",
      "value": "${ true }",
      "binding": {
        "type": "camunda:errorEventDefinition",
        "errorRef": "error1"
      }
    },
    {
      "label": "errorNameB",
      "value": "${ someVar == 123 }",
      "binding": {
        "type": "camunda:errorEventDefinition",
        "errorRef": "error2"
      }
    }
  ],
  "scopes": [
    {
      "type": "bpmn:Error",
      "id": "error1",
      "properties": [
        {
          "label": "Error Code",
          "type": "Hidden",
          "value": "my Error code",
          "binding": {
            "type": "property",
            "name": "errorCode"
          }
        },
        {
          "label": "Error Message",
          "type": "Hidden",
          "value": "my Error message",
          "binding": {
            "type": "property",
            "name": "camunda:errorMessage"
          }
        },
        {
          "label": "Error Name",
          "type": "Hidden",
          "value": "my Error Name",
          "binding": {
            "type": "property",
            "name": "name"
          }
        }
      ]
    },
    {
      "type": "bpmn:Error",
      "id": "error2",
      "properties": [
        {
          "label": "Error Code",
          "type": "Hidden",
          "value": "405",
          "binding": {
            "type": "property",
            "name": "errorCode"
          }
        },
        {
          "label": "Error Message",
          "type": "Hidden",
          "value": "",
          "binding": {
            "type": "property",
            "name": "camunda:errorMessage"
          }
        },
        {
          "label": "Error Name",
          "type": "Hidden",
          "value": "errorNameB",
          "binding": {
            "type": "property",
            "name": "name"
          }
        }
      ]
    }
  ]
}
```

Resulting XML
```XML
<bpmn:serviceTask ...>
      <bpmn:extensionElements>
        <camunda:errorEventDefinition id="ErrorEventdefintion_13asda3" errorRef="Error_0x9vl7b" expression="${ true }" />
     <camunda:errorEventDefinition id="ErrorEventdefintion_62da3s" errorRef="Error_0x9vl7a" expression="${ someVar == 123 }" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_04k3izd</bpmn:incoming>
      <bpmn:outgoing>Flow_1s764or</bpmn:outgoing>
</bpmn:serviceTask>
...
<bpmn:error id="Error_0x9vl7b" name="my Error Name" errorCode="my Error code" camunda:errorMessage="my Error message" />
<bpmn:error id="Error_0x9vl7a" name="errorNameB" errorCode="405" camunda:errorMessage="" />
```

Resulting UI
![Screenshot_20210127_155426](https://user-images.githubusercontent.com/42800119/106008792-f2940280-60b7-11eb-9f98-0d63d0a2edc3.png)

Tasks:

- [ ] Add new binding `camunda:errorEventDefinition` supporting 
  - [ ] reject bindings that have no errorRef (Validator)
  - [ ] `"type": "String"` => see example 1, implement inside [`CustomProps`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/parts/CustomProps.js) (get + update values)
  - [ ] ommited `"type"` => render default component (see example 2), re-use existing `Errors` implementation, disabled expression field, removed Error selection, no description (don't add meaningful value and they can't be added in Cawemo anyway)
  - [x] new binding property `errorRef`. The value of `errorRef` shall logically be resolved and be replaced by a UUID to the respective global `bpmn:error` (which is defined as a scoped binding in the same template). (Also see [parent issue](https://github.com/camunda/camunda-modeler/issues/2070))
- [ ] Update [docs and samples](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates)

__Why should we do it?__

See overall objective https://github.com/camunda/camunda-modeler/issues/2070
Child of camunda/camunda-modeler#2070
Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/425

**Comment by pinussilvestrus** [comment]
Things popped up on testing with @volkergersabeck 
* JSON Schema needs another release to work with Cawemo (v0.3.0)
--> Let's do it as a follow-up action
* Element Templates with an incompatible version still are shown in the Catalog Modal
--> @pinussilvestrus will investigate in the current Nightly, not part of this PR
* When Template is unlinked again, the error is not shown in the IO Tab reference select

![image](https://user-images.githubusercontent.com/9433996/111616002-aa54af00-87e1-11eb-8806-597f3c504cb2.png)

--> I will investigate this
