### ISSUE TITLE
Move empty dropdown entry to the top of the list

### ISSUE THREAD

**Issue by azeghers** [bpmn-io/bpmn-js-properties-panel#444]
__Is your feature request related to a problem? Please describe__

During testing of a feature, it has been noticed that the "empty" entry of dropdowns is always at the bottom, which is rather unusual.

__Describe the solution you'd like__

Have the empty option of the select element on top of the dropdown

__Describe alternatives you've considered__

None

__Additional context__

https://user-images.githubusercontent.com/42282939/109956249-bae62f00-7ce3-11eb-80c6-8067802f2093.mp4

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
