### ISSUE TITLE
Input parameters not working inside a web component

### ISSUE THREAD

**Issue by simeon-penev** [bpmn-io/bpmn-js-properties-panel#458]
__Describe the Bug__

The input parameters cannot be opened inside a webcomponent, because 'min-dom' is using document and not document.body.<web component>.shadowDom

The error occurs in InputOutputParameter.js:77 because entryNode is null:
```
  result.setOpen = function(value) {
    var entryNode = domQuery('[data-entry="' + collapsible.id + '"]');
    collapsible.setOpen(value, entryNode);
  };
```
__Steps to Reproduce__

1. Build the properties panel inside a web component and add 2 input parameters. 
2. Try to open one of the input parameters from the icon 'arrow' on the left side.
3. Error is shown in the console

__Expected Behavior__

The input parameters can be edited inside a web component.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
Chrome and Edge Chromium
- OS: [e.g. Windows 7]
Windows 10
- Library version: [e.g. 2.0.0]
0.40.0

**Comment by nikku** [comment]
@simeon-penev What would be the exact fix to make it shadow DOM _and_ DOM compatible? Do you mind contributing a fix?

`domQuery` supports a second, context parameter like so: `domQuery('.some-selector', someDiv)`

**Comment by simeon-penev** [comment]
@nikku Thanks for the suggestion, just posted the pull-request #460
