### ISSUE TITLE
Multiline input for expression

### ISSUE THREAD

**Issue by Hubel** [bpmn-io/bpmn-js-properties-panel#461]
Some expressions are editable only with a single line `input` element such as the listener's definition:
![image](https://user-images.githubusercontent.com/10436633/113828398-9ff45800-9784-11eb-90a2-a33070aa6425.png)

This is a bad usability for nontrivial expressions.

The definitions of expressions for inputs is solved much better with a flexible textarea and a helpful description:
![image](https://user-images.githubusercontent.com/10436633/113829128-6e2fc100-9785-11eb-9d98-42638b7a6d1e.png)

Would you please consider adjusting to this pattern for all expressions?

**Comment by pinussilvestrus** [comment]
Thanks for reporting! We are currently investigating in general improvements of the Properties Panel and the discovery of expression-ready inputs is one part of it.

In the meantime, we are open to contributions that improve the situation.

**Comment by barmac** [comment]
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.
