### ISSUE TITLE
Can't edit variables, form doesn't show up.

### ISSUE THREAD

**Issue by NiMusco** [bpmn-io/bpmn-js-properties-panel#464]
Randomly, under the "variables" tab, when I pick a variable from the list, can't see the form to edit it.
It happens both in "Out mapping" or "In mapping".

So, to make it work I have to select another task, or refresh and try it again.

### Expected Behavior

![Captura de pantalla de 2021-04-08 17-17-24](https://user-images.githubusercontent.com/12497746/114091000-7fb0c000-988e-11eb-91ff-56113dfd1030.png)

### Actual Behavior

![Captura de pantalla de 2021-04-08 17-17-00](https://user-images.githubusercontent.com/12497746/114090996-7e7f9300-988e-11eb-9e29-06a5e7e670a2.png)

### Steps to reproduce the Behavior

-Click a task with variables.
-Go to "variables" tab.
-In "In mapping" list, click any variable.

A form with "type", "source", "target" and "local" inputs should appear.
It doesn't always happen. Sometimes it just stays blank, as showed above.
But when it happens, resizing the list (from the bottom right corner) sometimes make the inputs appear.

### Environment

Browser:
-Firefox 87.0.
-Chrome 85.0.
-Older versions too.

OS:
-Windows 10 64bits.
-Ubuntu 18.04

Library version:
-bpmn-js@4.0.1

**Comment by pinussilvestrus** [comment]
Hi @NiMusco, thanks for reporting!

Can you maybe update your issue to fit [our template](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/new?assignees=&labels=bug&template=BUG_REPORT.md)? It would be especially interesting to us which version of the library you are using and maybe an example diagram where you were able to reproduce the problem.

Concrete steps to reproduce would be even better.

**Comment by NiMusco** [comment]
Thanks, @pinussilvestrus . I updated it with as much information as I have.
Sorry if it's not enough, the issue itself is sort of arbitrary.

**Comment by pinussilvestrus** [comment]
Thanks!

> bpmn-js@4.0.1

This is a rather old version of [`bpmn-js`](https://github.com/bpmn-io/bpmn-js). Any reason why you didn't upgrade so far (also to the latest `bpmn-js-properties-panel` version)? Maybe that would resolve your issue.

**Comment by pinussilvestrus** [comment]
@NiMusco any updates on this? Does updating the libraries helped you out?

**Comment by pinussilvestrus** [comment]
Let's close this one until we don't get further details.
