### ISSUE TITLE
Template select action not aligned with other actions

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/bpmn-js-properties-panel#495]
__Describe the Bug__

For details, see https://github.com/bpmn-io/bpmn-properties-panel/pull/141#discussion_r734339068

__Expected Behavior__

The expected alignment is described in the linked issue comment and is also available in the [prototype](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v15/).

**Comment by barmac** [comment]
@andreasgeier is it still the case on the latest artifacts?

**Comment by andreasgeier** [comment]
This seems to be fixed in the test artifact.

**Comment by barmac** [comment]
Cool, thank you!
