### ISSUE TITLE
The Unlink button is easy to overlook when template is unknown

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-properties-panel#498]
__Describe the Bug__

During the 9th November weekly, it was expressed that the unlink button is hard to spot for unknown template dropdown.

![image](https://user-images.githubusercontent.com/28307541/140912008-fd776043-b727-4609-b136-728ea8fef7fb.png)

__Steps to Reproduce__

1. Select a shape with an unknown template
2. Click the dropdown
3. now this happens

__Expected Behavior__

It should be as easy to spot as the remove button.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/545

**Comment by barmac** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/545 :)
