### ISSUE TITLE
I can set the resultVariable property

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#50]
AT:
- camunda:resultVariable can be set

**Comment by pedesen** [comment]
- add test cases for non message events
- some more explanation could be useful here: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/7b06354c3989473cb94d699a986dab50f135d45a/lib/provider/camunda/parts/ServiceTaskDelegateProps.js#L38
