### ISSUE TITLE
Deleting the first input item leaves the very next input in the list collapsed.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [bpmn-io/bpmn-js-properties-panel#502]
__Describe the Bug__

By creating more than one input list, and deleting the first in order we see that the very next input in the list is collapsed. 

__Steps to Reproduce__

1. Create more than one input item list.
2. Delete the first input item in the list.
3. We could see that the very next input item is collapsed while the later ones remain expanded.

This issue is replicable in output items list as well. 

__Expected Behavior__

Align the expansion/collapsing of the items in the list when deleting an input item.

__Environment__

- OS: [Windows 11]
- Library version: [4.11.1]

https://user-images.githubusercontent.com/85225325/142232638-61c27d18-3d1e-43e1-8bca-34d92e626b90.mp4

**Comment by nikku** [comment]
Fixed as of December 2022 (`bpmn-js-properties-panel@1.14.x`): 

![capture 5qE3bJ_optimized](https://user-images.githubusercontent.com/58601/210399064-04aeec40-b3e3-4ba8-9189-a418926b4892.gif)

**Comment by nikku** [comment]
Actually fixed for C8 diagrams only.
