### ISSUE TITLE
Clicking on  the "create" button we could see the blue outline being wonky and does not maintain the shape of the button.

### ISSUE THREAD

**Issue by GeethaParthasarathy** [bpmn-io/bpmn-js-properties-panel#503]
__Describe the Bug__

While trying to click on the "create" button we could that the blue outline is wonky and does not maintain the shape of the button.

__Steps to Reproduce__

1. Long Press on the create button to see the above mentioned error visible.
2. The same does not happen with the "select" button.

__Expected Behavior__

The outline of the "create" button should be corrected to fit the button as like in the "select " button.

__Environment__

- OS: [ Windows 11]
- Library version: [4.11.1]
![wonky-create_button](https://user-images.githubusercontent.com/85225325/142234599-27a52a4a-3ab4-4c88-bc94-e2da017a2c65.jpg)

**Comment by smbea** [comment]
This will be fixed upstream via https://github.com/bpmn-io/properties-panel/pull/148

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/1bada812a9127dcc9c51d3920d0c3639b64d9164.
