### ISSUE TITLE
I cannot set condition on a sequence flow outgoing from inclusive gateway

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-properties-panel#507]
__Describe the Bug__

I cannot set condition on a sequence flow outgoing from inclusive gateway. Condition group is missing.

Before:

![image](https://user-images.githubusercontent.com/28307541/143405859-8a5dbe50-792b-499f-8f7f-f19b1ceceb70.png)

Now:

![image](https://user-images.githubusercontent.com/28307541/143405961-7489a835-dc17-4cc3-b50a-1a0935409f53.png)

__Steps to Reproduce__

1. Create an inclusive gateway
2. Append a task and select the sequence flow
3. now this happens

__Expected Behavior__

I can set condition.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by MaxTru** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/518
