### ISSUE TITLE
Implementation is missing on message throw and end events

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-properties-panel#508]
__Describe the Bug__

> The message end event is missing an implementation. (...) Same for intermediate message throw event

__Steps to Reproduce__

1. Select a message end or throw event
2. now this happens

__Expected Behavior__

Implementation is available.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment]
Closed via #517
