### ISSUE TITLE
Basic PropPanel@next improvments based on internal feedback

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#515]
### Critical (ready)

- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/507
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/508

#### Quick fix

- [x] https://github.com/camunda/camunda-modeler/issues/2586
- [x] [update ordering](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/522)

#### Styling issues

- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/505
- [ ] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/504
- [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/503
- [ ] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/502

#### Feature requests

- [ ] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/506

### Dismissed (give explanation!) (Wontfix)

_Nothing here, so far_

### Postponed (requires evaluation)

_Evaluate this later. Consider consulting person who provided feedback and others._

- [ ] In Error events, the "Code variable" and "Message variable" should be handled as the "Name", "Code" and "Message". It looks wrong, that three only appear with a new "Global error", even if only the first 3 field will change their values when you select another error. (Ingo)

Check other global elements (root elements) whether we can have a unified pattern.

- [ ] For user tasks "Due date", "Follow up date" and "Priority" deserve a separate section. (Ingo)
- [ ] The header should show the ID as the label is visible in diagram. Right now I need two clicks to get the activity ID: Select element and open General. (Ingo)
- [ ] I would like to have a way to sort or organize the properties. I found my eyes wandering as I switched task types. It could be very confusing/frustrating at least until the user got used to it. hmmm, maybe a way to hide/show rarely used properties to clean up the properties panel (Joe Pappas)
- [ ] It would be cool if the properties panel could be undocked (Joe Pappas)
- [ ] https://github.com/camunda/camunda-modeler-design/issues/47 (Felix +3)
- [ ] Perhaps instead of having + and > just have it expand upon clicking and then have the user either see properties or an option to add. Or make it configurable (Joe Pappas)

**Comment by ingorichtsmeier** [comment]
Hi @barmac,

what about taking this with a higher priority, as it would take more effort on discussing than builing it: 

> The header should show the ID as the label is visible in diagram. Right now I need two clicks to get the activity ID: Select element and open General. (Ingo) 

What do you think, @andreasgeier ?

**Comment by andreasgeier** [comment]
> what about taking this with a higher priority, as it would take more effort on discussing than builing it:
> > The header should show the ID as the label is visible in diagram. Right now I need two clicks to get the activity ID: Select element and open General. (Ingo)

This is in the evaluation section because I would need to better understand for which users and use cases the ID is so important that it deserves a permanent place in the header.

**Comment by MaxTru** [comment]
> > what about taking this with a higher priority, as it would take more effort on discussing than builing it:
> > > The header should show the ID as the label is visible in diagram. Right now I need two clicks to get the activity ID: Select element and open General. (Ingo)
> 
> This is in the evaluation section because I would need to better understand for which users and use cases the ID is so important that it deserves a permanent place in the header.

I like the discussions. Let's also consider the Personas we have in Confluence: https://confluence.camunda.com/display/HAN/Personas. 
Notice that Software Developer Persona has the highest relevance in this context. So the question is, would the Software Developer rather see ID or Name of an element in the top area. cc. @andreasgeier @ingorichtsmeier

**Comment by ingorichtsmeier** [comment]
Hi @andreasgeier,

in automation projects you will get feedback like this in your tests:
```
java.lang.AssertionError: Expecting ProcessInstance {id='9', processDefinitionId='TwitterQAProcess:1:4', businessKey='null'} to be waiting at [Activity_1ahjwi2], but it is actually waiting at [Activity_0u9sbg9].
```
It is no fun to check all elements in a diagram with 50 tasks and Gateways.

**Comment by ingorichtsmeier** [comment]
An alternative solution is to open (exapand) the General section always when you select a new element. All other sections are closed.

**Comment by andreasgeier** [comment]
@ingorichtsmeier 

> It is no fun to check all elements in a diagram with 50 tasks and Gateways.

In this case, the ID in the header wouldn't be a solution, right? You still need to look at all the elements. This sounds like a need for a search, doesn't it?

> An alternative solution is to open (exapand) the General section always when you select a new element. All other sections are closed.

This is already the case. If you expand the general section once (or any other section), it stays open during the user session, also for newly created elements.

**Comment by MaxTru** [comment]
>In this case, the ID in the header wouldn't be a solution, right? You still need to look at all the elements. This sounds like a need for a search, doesn't it?

Notice that search is possible already:
![Search](https://user-images.githubusercontent.com/42800119/144814572-0d710f6d-68dc-4a25-af82-e2c82012b90d.gif)

**Comment by MaxTru** [comment]
>[...] This sounds like a need for a search, doesn't it?

Just to make sure we are on the same page: search is implemented alread
![Search](https://user-images.githubusercontent.com/42800119/144814724-3694b8c4-1228-42af-83be-8add406eee03.gif)
y:

**Comment by andreasgeier** [comment]
@MaxTru sure, I added the screenshot to my comment already 🙂

**Comment by pinussilvestrus** [comment]
@andreasgeier and I added an evaluation for the ordering feedback on this [Miro board](https://miro.com/app/board/uXjVOdWGXhY=/?invite_link_id=799865526891). Waiting for feedback now, most changes are already available via [this pull request](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/522).

**Comment by MaxTru** [comment]
No immediate next steps planned for now, will move to backlog.

**Comment by ingorichtsmeier** [comment]
Hi @MaxTru,

is there any build to download so I can verify the current state of the new property panel?

**Comment by MaxTru** [comment]
Hi @ingorichtsmeier ,

you can do the following:

```
git clone git@github.com:bpmn-io/bpmn-js-properties-panel.git
cd bpmn-js-properties-panel
git checkout next
npm i
npm run start:platform
```

=> This should start a browser window with the adjusted Properties Panel.

Alternatively: we can provide a build soon (we are currently in the phase of integrating the latest changes into the Camunda Modeler, we will have that probalby next week, and from there onward one can just use the nightly Camunda Modeler. I hope this helps? cc. @barmac
