### ISSUE TITLE
Support completion condition for multi-instance 

### ISSUE THREAD

**Issue by Lzgabel** [bpmn-io/bpmn-js-properties-panel#530]
Zeebe may soon gain support for multi-instance completion condition, see [camunda-cloud/zeebe#5439](https://github.com/camunda-cloud/zeebe/issues/5439) and [camunda-cloud/zeebe#8321](https://github.com/camunda-cloud/zeebe/pull/8321).

Child of camunda/camunda-modeler#2641

**Comment by pinussilvestrus** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/531
