### ISSUE TITLE
Removing an element template clears its name

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#570]
__Describe the Bug__

If I remove a linked element template the activities name is cleared:

![capture IpqPNi_optimized](https://user-images.githubusercontent.com/58601/152775474-e312850c-2764-4edd-b211-cc7abcec29f1.gif)

As a user I do not expect the name to be part of the element template, thus keeping it.

__Steps to Reproduce__

1. Load [element-templates.bpmn](https://github.com/bpmn-io/bpmn-js-properties-panel/files/8014624/element-templates.bpmn.txt)
2. Remove template from any element
3. See that name is removed with it

__Expected Behavior__

Name like elements that I can continue to customize as I have a template applied (group categroy value?, name, text annotation body?) are not reset as the template is being removed.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: bpmn-js-properties-panel@1.0.0-alpha.2, `#master` (both cloud and platform providers affected)

**Comment by pinussilvestrus** [comment]
What we could to, is to update the [`templateUtil`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/element-templates/util/templateUtil.js#L15) to set the old label to the new element, if applicable

```js
import { getLabel } from 'bpmn-js/lib/features/label-editing/LabelUtil';

export function removeTemplate(element, injector) {
  const modeling = injector.get('modeling'),
        replace = injector.get('replace'),
        selection = injector.get('selection');

  const label = getLabel(element);      

  // ...

  const newElement = replace.replaceElement(/*...*/);
  
  if (label) {
    modeling.updateLabel(newElement, label);
  }

  selection.select(newElement);
}
