### ISSUE TITLE
As a user I want to change a task to a different type as an element template is applied

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#572]
__Is your feature request related to a problem? Please describe__

As I model my diagram I tend to start with plain tasks rather than executable, i.e. `bpmn:ServiceTask` ones. Everything else does slow me down because I'd have to manually make each of my tasks a service task.

As I make my diagram executable I'm revising each task, making it either a service task, business rule task, ...

What I wanted to do is to apply a "mail task" template on a blank task; that template shall make the task a `bpmn:ServiceTask` before applying the template. If it was not a `camunda:ServiceTaskLike` or `zeebe:ServiceTaskLike` it was not executable by the engine.

What I have to do is to manually change the task to be a service task first, which is annoying. A unneeded indirection:

![capture ze0qpr_optimized](https://user-images.githubusercontent.com/58601/152796134-77388873-5275-4604-9151-5a559f826bbf.gif)

_Camunda Modeler v5 screen capture, showcasing `ServiceTask -> REST task` transition required._

Furthermore, when searching for an element template, the service task template wouldn't even show up for blank tasks, which makes it harder to discover.

__Describe the solution you'd like__

* [ ] Be able to configure a type binding for an element template; if it does not match with the current task the task is morphed into the target type _before_ the other element template properties are applied
* [ ] Given a type binding, also display these element templates on template select (maybe as a follow up action)

:arrow_right: Goal: Make it quicker to make a task executable backed by an element template.

__Describe alternatives you've considered__

Consider the current limitation a feature, not a bug.

__Additional context__

Came up in the context of connectors, specifically https://github.com/camunda/web-modeler/issues/524.

**Comment by MaxTru** [comment]
So something like this?

```
{
    ...
    "name": "Some Template",
    "appliesTo": [
      "bpmn:ServiceTask",
      "bpmn:Task" // <----- new!
    ],
    "properties": [
      {
        "type": "Hidden",
        "value": "bpmn:ServiceTask",
        "binding": {
          "type": "type"   // <------------ new!
        }
      }
```

**Comment by nikku** [comment]
Exactly.

**Comment by nikku** [comment]
During undo / template removal I'd not revert the type change.

**Comment by currandwyer** [comment]
@nikku I think this is related to the question I'm working on here. Broadly speaking how are connectors selected, and narrowly speaking how are task types changed to apply a specific element template once they've been added to the canvas. 

This is still WIP as you can see, more to come here: https://www.figma.com/file/TLVCfr4a1fjhV61yZvi0Jd/Connectors%3A-Reference-Flow-%26-Prototype?node-id=757%3A19820
![Screen Shot 2022-02-10 at 09 34 13](https://user-images.githubusercontent.com/11223953/153368470-e55849e1-55fd-4ad9-b9f8-49b9343f7aa5.png)

**Comment by nikku** [comment]
@currandwyer Exactly. Option 2 is what this is going to support from anywhere (properties panel, but also replace menu potentially.

**Comment by MaxTru** [comment]
Next step: discuss priority / necessity of this

**Comment by pinussilvestrus** [comment]
> What do you think of something like this @nikku @pinussilvestrus ?
> 
> ```
> {
>     ...
>     "name": "Some Template",
>     "appliesTo": [
>       "bpmn:ServiceTask",
>       "bpmn:Task" // <----- new!
>     ],
>     "properties": [
>       {
>         "type": "Hidden",
>         "value": "bpmn:ServiceTask",
>         "binding": {
>           "type": "type"   // <------------ new!
>         }
>       }
> ```

That looks good 👍 I'd assume that any other type instead of `Hidden` is not supported for this binding (to be validated via schema).

**Comment by nikku** [comment]
Not exactly sure if I correctly understand your question:

> Given the possibility to create an element directly from any template (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/582) + having it available via replace menu

How would this help me to change a, let's say _blank task_ to a _service task (configured as a REST connector)_?

**Comment by pinussilvestrus** [comment]
> But for that we need the ability to replace from a blank task to a (template defined) element type + additional properties configured.

Isn't that what the issue here is aiming?

I
* have a blank task
* want to change it to a service task
* want to apply the service task template

That would also be solved by 
* have a blank task
* choose the (service task) element template from the replace menu

**Comment by pinussilvestrus** [comment]
I guess the problem here is that the (service task) element template wouldn't show up for the blank task, right?

**Comment by nikku** [comment]
> I guess the problem here is that the (service task) element template wouldn't show up for the blank task, right?

Exactly. And if it did, there would be no way for the element to become a service task in the process of applying the template. Hence this issue.

**Comment by pinussilvestrus** [comment]
Thanks for the clarification 👍

**Comment by nikku** [comment]
Please update the issue so it better captures this fact. My appologies for not making that clear in the first place.

**Comment by marstamm** [comment]
RE the JSON schema:

instead of adding the type to the `properties` array, we can also have it as a root property

```
  'appliesTo': [
    'bpmn:Task',
    'bpmn:ServiceTask'
  ],
  'elementType': {               // <-- new
    'value': 'bpmn:Task' 
  }
```

This ensures that there is only **one** target type and we don't have to validate `type: 'hidden'`. Cf. https://github.com/camunda/element-templates-json-schema/pull/48#issuecomment-1077719731

**Comment by pinussilvestrus** [comment]
What just came to my mind: in our create element API for `cloud-element-templates` we use `appliesTo` to determine the type of the to be created element. I'd assume the new `elementType` would overrule this?

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/cloud-element-templates/create/TemplateElementFactory.js#L65

**Comment by nikku** [comment]
Yes, I believe so. We use 

(1) the existing type, if it satisfies (2) or (3)
(2) `elementType`, if provided
(3) the first type denoted in `appliesTo`

to find the type of the element.

**Comment by marstamm** [comment]
> create element API for `cloud-element-templates`

I totally forgot this existed, thank you for reminding me. I think it makes sense tho, as `elementType` is the only type we want created

**Comment by marstamm** [comment]
Something that @barmac mentioned during the weekly:

Consider the element Template:

```
  'appliesTo': [
    'bpmn:Task'
  ],
  'elementType': {
    'value': 'bpmn:ServiceTask' 
  }
```

Would this still be a valid Template, even though the the Service Task is only implicitly included through its super class? As we also check if an element can be applied using the `is()` utility (includes subclasses) rather than a perfect match, I think we should support this.

**Comment by MaxTru** [comment]
>Would this still be a valid Template, even though the the Service Task is only implicitly included through its super class? As we also check if an element can be applied using the is() utility (includes subclasses) rather than a perfect match, I think we should support this.
Makes sense. I agree

**Comment by nikku** [comment]
> Would this still be a valid Template [...]? As we also check if an element can be applied using the is() utility (includes subclasses) rather than a perfect match, I think we should support this.

I don't see a reason it should not be (a valid template). Our users should be able to facilitate the full power of our meta-model.
