### ISSUE TITLE
Name field shouldn't be displayed for Association

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js-properties-panel#576]
__Describe the Bug__

__Steps to Reproduce__

1. select `bpmn:association`
2. open general tab and see Name property present
3. try to edit and see it doesn't save

https://user-images.githubusercontent.com/25825387/152963199-55e3be25-6eef-42dd-bfab-29310e02a3f3.mov

__Expected Behavior__

Name field should not be present for `bpmn:Association` since this not part of the bpmn schema

__Environment__

- Library version: latest

**Comment by pinussilvestrus** [comment]
Shouldn't that be fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/566?
