### ISSUE TITLE
Empty Business Rule Task not Indicated as Empty

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-properties-panel#578]
__Describe the Bug__

When creating a new `bpmn:BusinessRuleTask` it doesn't have a `zeebe:CalledDecision` or `zeebe:TaskDefinition` extension element by default. However, in the properties panel _DMN decision_ is preselected as the implementation type. This is misleading.

![wkZv027AN0](https://user-images.githubusercontent.com/7633572/153001533-652866e0-b30c-4730-89cd-06f8818563b2.gif)

__Steps to Reproduce__

1. Create new business rule task
2. Open the _Implementation_ group in the properties panel
3. _Implementation_ has _DMN decision_ selected

__Expected Behavior__

_&lt;none>_ is selected by default.

<img width="257" alt="brave_BVi8PDHn4z" src="https://user-images.githubusercontent.com/7633572/153001542-25f59817-53ff-4ff1-a7c9-0d1d97f0b796.png">

__Environment__

- Library version: 1.0.0-alpha.2

**Comment by philippfromme** [comment]
I don't think this has been fixed.

1. The `Called decision` group is displayed when `<none>` is selected

![ZwxH7PuYWU](https://user-images.githubusercontent.com/7633572/157673706-572557fc-fa6e-4e9c-9bd5-2d0cac5f629f.gif)

2. Setting `Implementation` to `<none>` results in an error

```
index.esm.js?c024:777 Uncaught TypeError: Cannot read properties of undefined (reading 'ns')
    at BpmnModdle.Moddle.getType (index.esm.js?c024:777:1)
    at BpmnModdle.Moddle.create (index.esm.js?c024:750:1)
    at BpmnFactory.create (BpmnFactory.js?905a:75:1)
    at createElement (ElementUtil.js?0d36:17:1)
    at setValue (BusinessRuleImplementationProps.js?d679:74:1)
    at Object.handleChange [as inputfalse] (index.esm.js?77d2:1915:1)
    at HTMLSelectElement.$ (preact.module.js?f2f1:1:1)
```

This is due to `setValue` not taking `""` into account:

```js
const setValue = (value) => {
    const businessObject = getBusinessObject(element);

    let extensionElement, extensionElementType;

    if (value === DMN_IMPLEMENTATION_OPTION) {
      extensionElement = getCalledDecision(element);
      extensionElementType = 'zeebe:CalledDecision';
    } else if (value === JOB_WORKER_IMPLEMENTATION_OPTION) {
      extensionElement = getTaskDefinition(element);
      extensionElementType = 'zeebe:TaskDefinition';
    }

    if (!extensionElement) {
      extensionElement = createElement(
        extensionElementType, // if value is "" then extensionElementType will be undefined
        { },
        null,
        bpmnFactory
      );

      addExtensionElements(element, businessObject, extensionElement, bpmnFactory, commandStack);
    }
  };
```

**Comment by smbea** [comment]
I think that was a misunderstanding on my part @philippfromme. Will work on this as soon as I can
