### ISSUE TITLE
Allow customization of group-toggle element

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [bpmn-io/bpmn-js-properties-panel#598]
__Is your feature request related to a problem? Please describe__

My users have found the group-toggle element to be unintuitive and not in line with other software they are using. I concur with this.
Most editors and IDEs I know (Visual Studio Code, Atom, IDEA, Chrome Dev Tools etc.) use a downwards or sideways pointing arrow to indicate if a section is or can be collapsed. 

__Describe the solution you'd like__

I would like to be able to specify a custom element to be used as the group-toggle.

__Describe alternatives you've considered__

I have tried re-styling the element with css (failed because of the position of the span and because I would need something other than a span), moving it with javascript (failed because the element is generated after my moving code would run) and overriding the properties panel with a custom version (see [this forum thread](https://forum.bpmn.io/t/edit-appearance-of-group-toggle-override-createpanel/6968/3) for details.

__Additional context__

![groupToggle](https://user-images.githubusercontent.com/21172799/155901466-0d69d1b5-3690-4611-9d9e-4f2cd1f0e537.png)
This is how I am used to collapse elements / sections and what I would ultimatly like to achieve.

**Comment by pinussilvestrus** [comment]
> My users have found the group-toggle element to be unintuitive and not in line with other software they are using

Can you maybe explain what you mean by this? The current version of the properties panel actually offers arrows to indicate the collapse / expand state.

![image](https://user-images.githubusercontent.com/9433996/155945505-3e0989d0-065f-487e-9eca-daab7facb673.png)

Given the example you gave, it looks similar to me. Is there anything different from your expectation? Or do you use another version (e.g. `0.x.x`)?

**Comment by pinussilvestrus** [comment]
@Adrian-Bielefeldt did this solve your issue?

**Comment by pinussilvestrus** [comment]
I'm closing this one since there are no further updates. Feel free to re-open 👍
