### ISSUE TITLE
Make it possible to get all possible template options for an element

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#604]
__Is your feature request related to a problem? Please describe__

In the old properties panel, we had a [simple util](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/0.x/lib/provider/camunda/element-templates/parts/Helper.js#L24) to get all applicable element templates for a given element. With the removal of the chooser, this API / util is not available anymore.

Furthermore, implementors have to do this on their own, e.g. 
* [the Camunda Modeler](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js#L348)
* [the Connectors modeling demo](https://github.com/bpmn-io/connectors-modeling-demo/blob/master/connectors-extension/ConnectorsExtension.js#L139)

__Describe the solution you'd like__

Provide a simple API to retrieve all element templates a given element can be applied to. Something like

```js
const elementTemplates = modeler.get('elementTemplates');

const applicableTemplates = elementTemplates.getApplicable(element);

// do whatever I want
```

__Describe alternatives you've considered__

/

__Additional context__

Related to https://github.com/bpmn-io/internal-docs/issues/467 (not a hard requirement)
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/582

**Comment by marstamm** [comment]
Let's overload the `getAll` method so it supports the same arguments as `get`

- `getAll()` returns all elementTemplates
- `getAll(id)` returns all versions of the given template ID
- `getAll(element)` returns all applicable templates for the element

**Comment by nikku** [comment]
I'm fine with doing that if we blow up explicitly if `null` is passed (null not being a valid _nothing_, _string_ or _element_).
