### ISSUE TITLE
Template selector doesn't work

### ISSUE THREAD

**Issue by jurgenhaas** [bpmn-io/bpmn-js-properties-panel#608]
__Describe the Bug__

We have integrated BPMN.iO into Drupal a while ago and worked with version 8.x of bpmn-io and version 0.4 of this module. We're also using the camunda and the template extensions.

Now, we're upgrading to version 9.x and 1.0-alpha which is a huge step forward. Thanks a lot for that.

All is working fine, except the template selector doesn't show up. We validated all our templates, and they are just fine. Also, debugging the `setTemplates` confirms, that the validator accepts all templates as valid.

The button "+ Select" only shows on elements, where we have applicable templates. But when we click on the button, nothing happens. Not even an error or warning in the browser console.

When we open existing models which already use some of those templates, then we get the drop-down "Applied" and we can unlink the template. Also, elements with an applied template show all the defined properties from the template. The other test, removing all our templates from the application and opening an existing model, then we get the red indicator "Missing template".

All that tells me that the templates are ok and recognized. Only the select template action doesn't work.

I don't know how I should further debug this and hope, somebody from the community could help me finding out what's wrong.

**Comment by jurgenhaas** [comment]
I have verified, that this is working:

```
  return jsxs(HeaderButton, {
    title: "Select a template",
    class: "bio-properties-panel-select-template-button",
    onClick: selectTemplate,
    children: [jsx(CreateIcon, {}), jsx("span", {
      children: translate('Select')
    })]
  });
```

When clicking the button, this event

```
  const selectTemplate = () => eventBus.fire('elementTemplates.select', {
    element
  });
```

gets executed. But it feels as if nothing is listening to the fired event `elementTemplates.select` - is there anything I need to add separately to the app?

**Comment by pinussilvestrus** [comment]
>  But it feels as if nothing is listening to the fired event` elementTemplates.select`

This is expected as of now. The properties panel library itself doesn't provide such a selection, it leaves it open to the implementor to listen to the event (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/573).

As an example, the [Camunda Modeler is implementing it itself](https://github.com/camunda/camunda-modeler/blob/develop/client/src/plugins/element-templates-modal/modeler/PropertiesProvider.js#L16)

![image](https://user-images.githubusercontent.com/9433996/158059611-a99d9cdb-cc80-44b0-821b-613aecc136b4.png)

**Comment by jurgenhaas** [comment]
The link in #573 to https://github.com/bpmn-io/connectors-modeling-demo responds with a 404, unfortunately.

**Comment by nikku** [comment]
@jurgenhaas We'll see if we can provide you with a chooser or a way to build one. 

It is really something that is missing with properties-panel@1, I acknowledge that.

**Comment by jurgenhaas** [comment]
Oh, that would be fantastic

**Comment by nikku** [comment]
Is something along the lines of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/573 what would help you?

**Comment by jurgenhaas** [comment]
Well, there is only an animated Gif in there. The link to the promissing repo responds with a 404 as I mentioned above. But what the Gif shows would be great as a starter.

**Comment by nikku** [comment]
On a site-note it would be really interesting to understand what you folks are doing / building on top of our tooling.

**Comment by nikku** [comment]
Please create issues in this repository for everything you found.

**Comment by jurgenhaas** [comment]
Done in https://github.com/bpmn-io/element-template-chooser/issues/1 and https://github.com/bpmn-io/element-template-chooser/issues/2
