### ISSUE TITLE
Support documentation URL in element template

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#614]
__Is your feature request related to a problem? Please describe__

As a user I want to see detailed documentation for a templated task, to be shown in the properties panel as well as the template chooser.

__Describe the solution you'd like__

* [ ] I can attach a documentation URL to an elemen template

__Describe alternatives you've considered__

None.

__Additional context__

_Example showing an integration into the properties panel:_

![image](https://user-images.githubusercontent.com/58601/158794676-cf748ff5-32e4-44f2-a896-021a66cef82d.png)

_Example showing an integration into the element / template chooser:_ 

![image](https://user-images.githubusercontent.com/58601/158796350-851fe8f8-0c08-41b2-a558-3cc8f1629336.png)

---

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/610.

**Comment by pinussilvestrus** [comment]
I would imagine it something like

```jsonc
// Element Template
{
  "name": "My Task",
  "id": "com.camunda.example.MyTask",
  "appliesTo": [ "bpmn:ServiceTask" ],
  "description": "An example task",
  "documentationRef": "https://www.example.com/myTask"
}
```

```jsonc
// JSON Schema
{
  "documentationRef": {
    "$id": "#/documentaionRef",
    "type": "string",
    "pattern": "^(https|http)://.*", // or whatever pattern we use
    "errorMessage": {
      "pattern": "Malformed documentation URL"
    }
  }
}
```

**Comment by pinussilvestrus** [comment]
@MaxTru @marstamm could you maybe have a look at my proposal (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/614#issuecomment-1070945702)? If there is nothing against it, I could already start bringing the new property to the Schema.

I would even say let's support it for both 7 and 8, there is no reason to only focus it on Camunda Platform 8.

**Comment by marstamm** [comment]
I don't see any problems with this approach, I think we can go ahead with it

**Comment by pinussilvestrus** [comment]
This is fixed upstream via https://github.com/camunda/element-templates-json-schema/pull/47. A schema release is pending, though.

**Comment by MaxTru** [comment]
Implementation to follow-up with: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/616
