### ISSUE TITLE
Display link to element template documentation

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#616]
__Is your feature request related to a problem? Please describe__

As a user I want to be able to read documentation related to a specific task type ("element template"), if provided (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/614):

![image](https://user-images.githubusercontent.com/58601/158796500-7adf1aa4-5c23-4ae0-96de-8a3ce1a3d07f.png)

__Describe the solution you'd like__

* [ ] If provided, display a link to the element (template) documentation in the [properties panel header](https://github.com/bpmn-io/properties-panel/blob/main/src/components/Header.js#L10).
* [ ] update [element template docs](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/about-templates/)

__Describe alternatives you've considered__

None.

----

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/614.

**Comment by pinussilvestrus** [comment]
This also depends on how much the panel header is aware of element templates: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/610#issuecomment-1070929874 + https://github.com/bpmn-io/bpmn-js-properties-panel/issues/610#issuecomment-1073543140

**Comment by pinussilvestrus** [comment]
@currandwyer is the icon already available to use? 

![image](https://user-images.githubusercontent.com/9433996/159434326-6590a75a-9ffd-4d42-afcf-568c613f26bc.png)

**Comment by nikku** [comment]
```svg
<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M10.064 10.0646V5.66793H11.3333V10.0653C11.3333 10.3998 11.2055 10.6949 10.9499 10.9505C10.6943 11.2061 10.3992 11.334 10.0646 11.334H1.26933C0.915062 11.334 0.614938 11.211 0.368963 10.965C0.122988 10.719 0 10.4189 0 10.0646V1.26933C0 0.915062 0.122988 0.614938 0.368963 0.368963C0.614938 0.122988 0.915062 0 1.26933 0H5.66667V1.26933H1.26933V10.0646H10.064ZM11.3338 0.00160619H6.93648L6.93585 0.000976562V1.27031H9.17922L3.01074 7.43879L3.896 8.32405L10.0645 2.15557V4.39894H11.3338V0.00160619Z" fill="#818698"/>
</svg>
```

This is the icon. @currandwyer Please share design resources with @pinussilvestrus where approprate, too.

**Comment by pinussilvestrus** [comment]
This is kind of related to make it possible to display URLs in descriptions: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/626

However, as I understand it, the goal here should be to make documentation URLs easier discoverable, without having to open the template section.

**Comment by pinussilvestrus** [comment]
The basic implementation is done via 

* https://github.com/bpmn-io/properties-panel/tree/documentation-links-header
* https://github.com/bpmn-io/bpmn-js-properties-panel/tree/616-documentation-header

![Kapture 2022-03-25 at 14 45 12](https://user-images.githubusercontent.com/9433996/160132743-af45834a-02f4-431c-909e-c826fd4bf06a.gif)


I will conduct a chat with @currandwyer to clarify the design of the link. We have other places where we have action icons (e.g. add, collapse) and I believe we should make sure they behave similarly.

**Comment by nikku** [comment]
Looks great already. The icon does not seem to be aligned vertically on the header though. Is this intentional? Looks a bit disturbing I think.

**Comment by pinussilvestrus** [comment]
> Looks great already. The icon does not seem to be aligned vertically on the header though. Is this intentional? Looks a bit disturbing I think.

I didn't style it at all so far, only dropped the icon and aligned it to the left 🙂

**Comment by nikku** [comment]
Interestingly I'm using a slightly different icon ([this one](https://www.figma.com/file/LhvREvT2outP5YroJDamfq/Connectors%3A-Initial-UI-Specifications?node-id=171%3A318)). @currandwyer please point to source of truth.
