### ISSUE TITLE
Verify replacement between element templates works correctly 

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#617]
__What should we do?__

As part of our improved template modeling UX we want to support switching between different element templates (i.e. change from REST connector to SendGrid connector):

![capture Tjkon7_optimized](https://user-images.githubusercontent.com/58601/158799431-e8c0d4a7-beb6-4a64-b74b-3e78dd1aaa51.gif)

We should verify that our existing mechanism for carrying over input and output bindings is sufficient, i.e. that only bindings that are being supported by the REST connector are carried over when changing from SendGrid to REST or vice versa.

__Why should we do it?__

Support switching of element templates.

**Comment by marstamm** [comment]
I played around a bit with the [demo of the connectors extension](https://potential-winner-9f6a854d.pages.github.io/), as those uses the `propertiesPanel.zeebe.changeTemplate` event.
I was able to verify that

- Properties are transferred when replacing templates as long as the binding is the same
- Properties that are not part of the new template are removed and not persisted in the XML
- This works even when group, label, or type are changed

What does not work is unlinking and then adding a new Element template. But as this is not how we currently plan to implement it, this should be fine
