### ISSUE TITLE
Allow sections to be opened per default

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#618]
__Is your feature request related to a problem? Please describe__

In the properties panel we display sections "closed per default". This negatively impacts users in places where quick configuration is needed: For example, in the element template case I want all (or at least the mandatory inputs) to be visible to the user upon applying the template.

![capture Tjkon7_optimized](https://user-images.githubusercontent.com/58601/158799740-212ccbd7-29a5-4148-9201-1bccfce0ac48.gif)

My assumption is that after the first time the user has the choice to close individual sections and using our "persistent open/close mechanism" these sections will remain closed if they are chosen again, on other elements.

__Describe the solution you'd like__

* [ ] We allow all sections (or a subset of sections) to be opened per default rather than closed per default upon showing it for the first time.

__Describe alternatives you've considered__

None.

__Additional context__

Came up in the context of connectors. Users shall be able to see all (or at least all required) fields upon applying a template to an element or creating a template-backed element.

**Comment by nikku** [comment]
CC @MaxTru @andreasgeier

**Comment by andreasgeier** [comment]
Do we have insights on how many users would like to directly implement a connector after adding it to the canvas vs the connector is just a placeholder during a design phase? @currandwyer 

What I heard from internal experts during linting research is that usually developers tend to design a (full) process diagram first (like a "process specification") and implement it afterwards.

**Comment by currandwyer** [comment]
Generally, the expectation would be that users model a process first, then configure the process element later. It might be useful to scan the fields right away to learn more about what is required given that connectors will have a variety of different element template types. But I don't see how which stage the element template is filled out is the most pertinent issue.

I expect many of these element templates to be relatively short, and to have a majority or all required fields. So, the basic principle is: if an element template isn't generally (far) below the fold when expanded, and has a number of fields the user will need to read and then complete, it makes sense to have those fields expanded by default to avoid extra clicks and maximize transparency.

**Comment by andreasgeier** [comment]
I'm a little worried that opening all groups as default will greatly increase the impression of the panel's complexity. Especially in the C7 environment.

But I'm willing to try the open variant after weighing the pros and cons to make it easier to use connectors.

**Comment by pinussilvestrus** [comment]
I'm fine with the proposal, anything other we can consider later on top 👍
