### ISSUE TITLE
Changing element template clears existing, compatible binding values

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#638]
__Describe the Bug__

As I'm using element templates and switch between different templates (i.e. using `ElementTemplates#applyTemplate`) the implementation clears compatible values, if they match the existing template default.

![capture 1uuk08_optimized](https://user-images.githubusercontent.com/58601/160605350-b78b409b-5035-4f23-976f-41afa7ec3c70.gif)

__Steps to Reproduce__

#### template-1

```
{
  "value": "https://foobar",
  "binding": {
    "type": "zeebe:input",
    "name": "url"
  }
}
```

#### template-2

```
{
  "value": "= other",
  "binding": {
    "type": "zeebe:input",
    "name": "url"
  }
}
```

* Given I have `template-1` with `zeebe:input#url = "https://foobar` applied
* When I change to `template-2` `zeebe:input#url = "= other` is set, despite the existing binding being valid in the context of `template-2`

__Expected Behavior__

Compatible, existing binding values are kept as I change the template.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: v1.0.0-alpha.7 (latest) but also `master`

**Comment by nikku** [comment]
I'll follow up with a test case to reliably reproduce it in both C7 and C8 templates.

**Comment by marstamm** [comment]
> Compatible, existing binding values are kept as I change the template.

Are we sure we want to keep existing bindings even when we did not change it from the default? I'm thinking of the scenario:

- I apply `SendGrid` Template, the default url `https://api.sendgrid.xyz/send`
- I immediately realize that I wanted a SMTP Task instead, and apply it
- URL should update to `smtp://user:host@myHost.email`

In this case, it would be weird to keep the sendgrid URL.

Implementing this would also mean that `Hidden` fields are not just hidden, but also get special behavior when applying templates. If we don't and the url input is of type `Hidden`, there is no way of knowing that the URL did not update as I would expect it until it breaks during runtime

**Comment by nikku** [comment]
@marstamm Great points.

Regarding `Hidden`, you can indeed argue it is special, as it sets a fixed value (default makes no sense either).

Regarding default over existing semantics: What your comment shows is that we need to define clearly what takes precedence over what (default values over existing compatible values) before we can act here. 

---

Double checking with our existing behavior I can confirm that the original bug does not seem to be present anymore, which is great for the user experience:

![capture R6Gcev_optimized](https://user-images.githubusercontent.com/58601/161945179-01c0d802-60fc-4faf-9776-c40a7e07cf8a.gif)

**Comment by nikku** [comment]
I do still believe we are a little bit too strict clearing things when applying a template (Service Task -> REST task): 

![capture cWHsFA_optimized](https://user-images.githubusercontent.com/58601/161947422-aa01709e-edd9-470e-9807-fa58cde164a7.gif)

Reproduce on [connectors modeling demo](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1) using 
[`send-was-rest.bpmn`](https://github.com/bpmn-io/bpmn-js-properties-panel/files/8425724/send-was-rest.bpmn.txt).

But maybe that is a different issue?

**Comment by nikku** [comment]
To your point on `url` to `url` (different semantics) conversion: If what the user entered is structurally broken after a template chenge then validation could be a way to identify this, too.

Also, as a template author I can clearly namespace my inputs so that such accidental takeover is avoided.

**Comment by marstamm** [comment]
> as a template author I can clearly namespace my inputs so that such accidental takeover is avoided.

Another Scenario would be versioning (not sure if we support it for connectors).
- "SendTemplate, version 1": `url = v1.mySendApi.com/someEndpoint`
- "SendTemplate, version 2": `url = v2.mySendApi.com/someEndpoint`

In this case, I would expect the URL to change to the new default and have the same namespace. You could argue about validation, but I doubt that this would be used for minor changes like these.

**Comment by marstamm** [comment]
> I do still believe we are a little bit too strict clearing things when applying a template (Service Task -> REST task):

I can reproduce this and will investigate

**Comment by nikku** [comment]
I think it is best to clearly capture all these scenarios in `elementTemplates#applyTemplate` test. Will do so once I'm back.

**Comment by marstamm** [comment]
I spend the last 1-2 days working on this, and it is relatively straight-forward to keep existing configuration without applied template for camunda cloud: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/661

For Platform, it is not that easy. In some cases, we explicitly override everything (e.g. [ExecutionListeners](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/ffb6a1feb9fd4e957b31d029ef30c4ca09959789/src/provider/element-templates/cmd/ChangeElementTemplateHandler.js#L230)), while at other places we do check for existing values.

If we want to support this in C7 as well, we should be clear about which bindings can be kept safely

**Comment by nikku** [comment]
The point that `Hidden` shall always override is enforced via https://github.com/camunda/web-modeler/issues/1110.

**Comment by marstamm** [comment]
> The point that Hidden shall always override is enforced via https://github.com/camunda/web-modeler/issues/1110

`Hidden` is not the root cause here, it would break with `Text` as well. Before the changes in #661 , the `ChangeElementTemplateHandler` would always create a second binding if no template was defined before:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/e0260ed9e41d012c2082a04fde5bcbd7cf230b02/src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js#L187-L196

`oldProperty = 'undefined'` => create new one

But I agree, hidden should always override the existing, see https://github.com/bpmn-io/bpmn-js-properties-panel/pull/661/commits/83d5075d093f9e6536e85e8173419332634bc76f

**Comment by marstamm** [comment]
IMO, these are possible scenarios for Element Templates that we should cover (and add Integration Test for):

- **ServiceTask -> Element Template**
    - Existing values are kept
    - defaults added when nothing exists
    - hidden values always override
- **Element Template A -> Element Template B**
    - Existing values are kept
    - new defaults override existing defaults (if no custom value was added)
    - hidden values always override
- **Element Template v1 -> Element Template v2**
    - Same as different Templates
- **Element Template -> Service Task**
    -  keep all values
- **Element Template -> Service Task -> Element Template**
    -  Round trip should end with the start configuration (keep everything)
    - If defaults were cleared, they will be added when applied

**Comment by nikku** [comment]
@marstamm Assigned you as we agreed on you'll wrap this topic up via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/661.

**Comment by nikku** [comment]
Wrapped up / closed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/661.
