### ISSUE TITLE
Do not carry over element templates during replacement

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#642]
_Context: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/632, specifically https://github.com/bpmn-io/bpmn-js-properties-panel/pull/632#pullrequestreview-924627721._

__Describe the context__

In the C7 world element templates [are] ~~had unclear semantics a template could be applied to various elements "operating on top of these elements" and being~~ carried around as the underlying element type changed. Not sure how useful that feature was in the first place, but that is how it worked.

With C8 + future bpmn-js templated elements will become dedicated, first class citizens on the diagram. We call them "email task", "email connector", and they shall be thought of as dedicated entities, "templated tasks", "connector tasks" rather than something put on top of an existing task, i.e. "service task with email template applied". Cf. [mental model, Connectors Solution Architecture](https://docs.google.com/document/d/1GhSOixwZ5A7S3ajtq7KmJv7jzW9gNFulrt2TVf1pG04/edit#heading=h.w9e0ckh5vt7z)).

In this context it does not make a lot of sense to carry over the element template as I switch from one task to another:

* I switch from template task `x` to service task => I want the results to be a plain service task
* I switch from template task `x` to template task `y` => I want the result to be a template task `y` with whatever base type is specified

If we don't go this direction we may end up in a situation where I cannot [get rid of a template via replace](https://github.com/bpmn-io/bpmn-js-connectors-extension) anymore; in some contexts thought replace is the only thing we got (i.e. web-modeler or (future) no-properties modeling).

__Describe the solution you like__

We should consider removing templates during replace _or_ create a dedicated mechanism to replace, removing templates; we shall not automagically re-apply the template on the new element.

Our existing rules on keeping properties "as fit" shall continue to apply:

* Switching from a email task (built on top of a service task) to a service task keeps compatible bindings (i.e. input/output bindings)
* Switching from an email task to a user task keeps all compatible bindings
* Switching from a send task with template `A` to a service task, template `B` changes the task type, applies a new template and carries over all compatible bindings

----

_Originally posted by @nikku in https://github.com/bpmn-io/bpmn-js-properties-panel/pull/632#pullrequestreview-924627721_

**Comment by nikku** [comment]
CC @marstamm @MaxTru @christian-konrad

**Comment by MaxTru** [comment]
I think:

* In the **as-is** we can support a use case where:
  * I apply a template to a ServiceTask and configure it (let's say `SMTP Template`)
  * I realize I want this to be represented as `SendTask` => So I switch to `SendTask`
  * I don't loose my previous configuration
  * ==> I think this is reasonable and works. So I disagree with `In the C7 world element templates had unclear semantics a template`
* HOWEVER, now we do have the use case:
  * I apply a template to a ServiceTask and configure it (let's say `SMTP Template`)
  * I realize I actually want some other Tempalte (let's say `SendGrid Template`). So I switch to `SendGrid Template` Task
  * ===> Now the configuration is still kept, BUT not visible (since the respective bindings are not configured)
  * =======> This clearly is a bad / undesired state
* In order to support both use cases, we could say:
  * Keep template and properties, if switching to another plain BPMN symbol, that still is in the `appliesTo`
  * Remove the template and switch, when changing **to another template**

**Comment by nikku** [comment]
> I apply a template to a ServiceTask and configure it (let's say SMTP Template)

This use case does not exist in C8 anymore, at least when it comes to our connectors story. You model in building blocks, and these are plain BPMN tasks _or_ domain specific tasks based off a template / "connector tasks". 

For C7 parity we support _upgrading_ via the properties panel still (to aid the transition), however in the future we shall better support this use case via the existing mechanism (create/append/replace anything).

**Comment by nikku** [comment]
> I realize I want this to be represented as SendTask => So I switch to SendTask

This distinction won't matter anymore to me as a user; the task will be shown as a "SMTP Template" task, including the icon, if provided.

**Comment by MaxTru** [comment]
What is differentiating for the user here is the icon. The following is what we have at what is used (if no icon is supplied):

1. Create new Mail Task
  * Service Task Icon appears
  * Mail Task properties are show in the Properties Panel
2. Morph Mail Task to SendMessage Task
  * Send Message Task Icon appears
  * Mail Task properties are still in the Properties Panel


But I agree, I think to include that:
* Every replace removes the element template (even if we not replace with a new template, but just with a plain BPMN)
... is sensible and easy to understand. I am +1 to implementing this.

I would just highlight this as breaking change from the UX we had so far. I don't expect that anyone would complain.

That was a productive exchange :-)

**Comment by nikku** [comment]
I'm glad you agree this direction of travel makes sense. 

In the rare moment that someone complains, a compelling case is presented (we learn!), there is always ways to _make it configurable_, opt-in to the legacy behavior (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/642#issuecomment-1082052587).

**Comment by nikku** [comment]
> I would just highlight this as breaking change from the UX we had so far. I don't expect that anyone would complain.

Agreed, too. 1.0 is the perfect time to ship such "breaking changes".

**Comment by nikku** [comment]
Decided (@MaxTru, @nikku), based on prior discussion: We'll incorporate this into properties-panel@1. Moving to ready.

**Comment by marstamm** [comment]
I don't fully understand the use-case this would solve. I mapped 3 scenarios that we currently support (pending [elementType support](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/648)). I think the one described in this ticket is covered by Scenario 3. The assumption is that a Connector always defines an `elementType`. Am I missing something?

## Same Template, different Task type

Template:
```
appliesTo: [
  "bpmn:ServiceTask",
  "bpmn:SendTask"  
]
```

1. I apply the template to a Service Task and fill out the custom Fields.
2. Now I want it to be displayed as a `SendTask` without changing the implementation.
3. I replace it with a `SendTask` using the replace Menu. 
4. The Template is still applied (current State).

## Different Templates/Connectors
I have the Templates `REST_request` and `SendMail`, where some Properties overlap. 
1. I start to configure the REST template with the email endpoints.
5. I realize that I had the wrong template applied. 
6. I replace it with the `SendMail` Template and the URLs are applied as they have the same property

## elementType specified
I have a Connector defined like this:

```
appliesTo: [
  "bpmn:Task"
],
elementType: {
  "value": "bpmn:ServiceTask"
}
```

1. I change it to a SendTask
2. The template gets unlinked, I have a basic SendTask
3. The bindings are persisted

**Comment by nikku** [comment]
@marstamm What we essentially need is a way to "get rid of templates" from the core modeling UI.

You have the choice to switch to another element template (and potentially another task type) and that keeps compatible bindings.

You have the choice to switch to a stock task (no element template) and it removes the template binding.

Will have a look into your PR tomorrow or on Monday to see if it covers this properly.

**Comment by marstamm** [comment]
What it does not cover is replacing a Template/Connector
```
appliesTo: [
  "bpmn:Task"
],
elementType: {
  "value": "bpmn:ServiceTask"
}
```

with a plain service task. Currently, this is not possible with the replace menu, as you can't replace an Element with the same Task type. I'm not sure if this is something that we should support, or if this specific case should be handled by the replace menu itself and unlink the Template there.

**Comment by nikku** [comment]
I'm aware of that, but I also opened https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/32 to follow up. Best is if we don't need to hack it into the core.
