### ISSUE TITLE
Headers / inputs are not cleaned when switching between element templates

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#653]
__Describe the bug__

The overall "check if properties are still valid during replace" interaction has a bug that affects changing from one element template to another where the first and second are distinct in their binding types (i.e. the first defines only inputs, the second one only headers).

In that case the properties are not cleaned up (inputs stay configured) despite the second template not having input bindings. Breaks the other way around, too.

![capture ZuLYdR_optimized](https://user-images.githubusercontent.com/58601/161540758-4caaa26d-9d03-47df-98f6-1d1756403d7f.gif)

__Steps to reproduce__

You can find two example templates to reproduce this [here](https://github.com/bpmn-io/bpmn-js-connectors-extension/commit/1cb6eaf8192abcf928624aa7902994e395c7caf0).

* Given I have a template that defines a task header `<a>`
* If I change to another template that does not define task headers
* Then the task header `<a>` binding is not cleaned up

I believe this is due to our C7 legacy of "only touching what has been defined"; it does not seem to be the appropriate behavior for C8 anymore.

__Expected Behavior__

Bindings (inputs, headers) are cleaned up completely, despite the new template not using them.

----

_Originally posted by @nikku in https://github.com/bpmn-io/bpmn-js-properties-panel/issues/648#issuecomment-1087471846_

**Comment by MaxTru** [comment]
@marstamm considering you investigated the replace behavior in general, could you please have a look?

**Comment by marstamm** [comment]
I checked it and can confirm that the old Input Mappings & Headers are only removed when the new Template declares Input Mappings of their own. 

This seems to be done on purpose:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/d96930011cec7e5db04776a375fc0e4f41544878/src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js#L294-L297

But I could not find the reasoning in the [PR](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/555) or [Issue](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/540) that contributed it. I think we are safe to remove this restriction

**Comment by nikku** [comment]
This is _legacy_ (C7 2016) behavior.

Our assumption in the past was that element templates work along with existing configuration.

Since then we've made it impossible to show specific existing bindings _next to_ the element templates (_entriesVisible_).

We could keep this behavior for C7, if we desire; we should move to a more consistent replace/clean anything for C8 templates. 

CC @MaxTru
