### ISSUE TITLE
Element Template custom icon does not show, if template is not found

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#657]
__Describe the Bug__

Element Template custom icon does not show, if template is not found

__Steps to Reproduce__

1. Have element with template applied. As part of this, have custom Icon
2. Remove the element tempalte from local configuration, but keep applied
3. => Notice that custom renderer still shows the icon, but propPanel does not
![Screenshot_20220405_113100](https://user-images.githubusercontent.com/42800119/161724405-9516814b-aba6-4a43-b649-1ab446970833.png)

__Expected Behavior__

I would say that the header should also show the icon.

The behavior to remove the icon with unlink should remain.

At least the custom renderer on the canvas and propPanel header should behave he same way.

__Environment__

bpmn-js-properties-panel@[1.0.0-alpha.11](https://github.com/bpmn-io/bpmn-js-properties-panel/commit/f84f5337197587eed21da020dc18b203c6ba76dd)

**Comment by MaxTru** [comment]
Let's align @pinussilvestrus @nikku

**Comment by pinussilvestrus** [comment]
> At least the custom renderer on the canvas and propPanel header should behave he same way.

I agree. I think we are too lazy getting [the icon from the template in the header](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/PanelHeaderProvider.js#L95). Instead, we should retrieve it in the same way as [in the renderer](https://github.com/bpmn-io/element-templates-icons-renderer/blob/main/src/util/index.js#L6).

**Comment by nikku** [comment]
If you ask me the properties panel is the place where we _fix things_.

If the template is unavailable, we don't show the template name, too (cf. "SERVICE TASK" being displayed).

For me it does make sense _as is_.

**Comment by nikku** [comment]
I'm inclined to close this as won't fix and wait for further feedback. What do you think?
