### ISSUE TITLE
Modeler Keyboard shortcuts triggered when editing properties

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#66]
When typing text into the properties panel, the keyboard shortcuts of the modeler are triggered. This should not be the case.

Steps to reproduce:
- select service task
- type "abcde" into Java Class property
=> space tool is activated

**Comment by pedesen** [comment]
moved to https://github.com/camunda/bpmn-io-modeler/issues/39
