### ISSUE TITLE
Improvements to FEEL expression helpers (required vs. optional)

### ISSUE THREAD

**Issue by currandwyer** [bpmn-io/bpmn-js-properties-panel#664]
__Is your feature request related to a problem? Please describe__

We have implemented new icons to help users know when a FEEL expression is required or optional in a particular field.

As there is no universally accepted icon icon for FEEL expressions, it's not clear what this icon means at first. We have very quickly gotten feedback internally that this is confusing, for example:

> while documenting the new FEEL icon in the web modeler for connectors, I intuitively assumed that the normal equal sign means FEEL is required, and the icon with a * means that FEEL is optional. I now realized it's the inverse, but I cannot reason why I assumed it in the first place, maybe I relate the * somehow with regex syntax.

> I noticed the icon next to ID. This seems new. What does it mean?

> Probably this is not even connector-related, as the problem is: A FEEL-required field (as noted by the little equal sign with asterisk) should be filled with something that starts with '='. Always. So why not showing a hint when the entered text is not a FEEL expression? And to be honest, it is actually kinda small, the little asterisk in the small icon.

__Describe the solution you'd like__

We would like to make the FEEL helpers more discoverable. This includes:

* Clearly distinguishing where FEEL is required / where FEEL is optional
* Not confusing with field being required / field being optional (these are different concerns), especially in element template land FEEL can be required, if field contents are provided.

__Describe alternatives you've considered__

To help with the clash between "FEEL required/optional" and "field required/optional" we should remove any mention of **required** or **optional** language in the context of FEEL. Instead, we should say something like "May use a FEEL expression" and "Must use a FEEL expression"

Several options are possible to clarify the meaning of the icon. One option would be to create a tooltip that appears immediately on hover, to help explain what the icon indicates. Currently the tooltip is browser-standard, only appearing after a couple of seconds, and is very easy to miss. A faster tooltip would make the pattern more learnable, although it still is not immediately obvious what the icon means exactly.
![Intro Container](https://user-images.githubusercontent.com/11223953/162732823-c79e19cd-ff88-4aa7-a126-4f2c67dc8d42.png)

We could also use an explicit tag. This is immediately very obvious what we are trying to indicate, but takes up a lot of room for what will be a regularly repeating pattern, potentially lowering the overall information density in the properties panel.

![Intro Container](https://user-images.githubusercontent.com/11223953/162731850-2775d57a-4c27-44a9-8550-6540084975a5.png)

Link to Figma explorations of alternative directions: **https://www.figma.com/file/WAYCmyTauJSVJ6bA9ZfBqI/FEEL?node-id=67%3A4236**
__Additional context__

**Comment by nikku** [comment]
Added the following:

> * Clearly distinguishing where FEEL is required / where FEEL is optional
> * Not confusing with field being required / field being optional (these are different concerns), especially in element template land FEEL can be required, if field contents are provided.

I think feedback we got is mostly about the icon in the context of element templates / connectors where `*` for FEEL being required clashes with the element actually being _optional_.

**Comment by currandwyer** [comment]
@nikku that's a great point, I have added the observation:

> To help with the clash between "FEEL required/optional" and "field required/optional" we should remove any mention of **required** or **optional** language in the context of FEEL. Instead, we should say something like "May use a FEEL expression" and "Must use a FEEL expression"

**Comment by currandwyer** [comment]
@nikku I'm pretty sure the solution is to have custom tooltips like the one I pointed to, which:
- Appear immediately or after a -very- short delay
- Have less conflicting language, like "Must be / May be a FEEL expression"

I'd like to avoid the option of using text. I think the icons are learnable enough, and any other solution will be making a lot of noise in the in the element templates.

What do you think, does that sound sensible?

**Comment by marstamm** [comment]
In context of the FEEL editor: how do we want to display the starting `=` sign, if at all?

Concept from @christian-konrad on switching between FEEL and normal input 
![image](https://user-images.githubusercontent.com/21984219/170009634-cf92e5d8-27bf-4577-b66f-3c9390c471a3.png)

**Comment by marstamm** [comment]
## Sync Results
Miro summary Board: https://miro.com/app/board/uXjVOw2MXRo=/?share_link_id=114667654183
We will conduct user research before making a final decision on this topic.

Research Questions:
- Which is the best way to discover feel expressions?
- How does Keyboard Navigation feel?

For this @marstamm will create prototypes. All prototypes should have required, optional and non-feel fields.

For Research question 1:
1. Current state in the modeler
2. `=` sign as a toggle button at the start

For Research question 2:
1. `=` sign disappears once you type it and changes the button state
2. `=` sign stays while you edit, button state changes on blur

@EvgeniyaUX will support us with conducting the user tests

**Comment by christian-konrad** [comment]
You can find more details on the research here in the research brief: https://docs.google.com/document/d/136QTXMO3msVzbSvO5ZGbw2HtYvVbmsn7CvOxyymNC-k/edit

**Comment by marstamm** [comment]
@christian-konrad , the document is restricted, how can we get access?

**Comment by christian-konrad** [comment]
@marstamm you should reach out to Evgenjia, as she owns the document

**Comment by currandwyer** [comment]
This is looking really good @marstamm ! Only problem I see is that the drop shadow is too light and blurry, making it difficult to distinguish from the selected state.

I recommend reducing the blur from 10 to 5px, and making the drop shadow a bit darker - perhaps 55. Let's also experiment with adding an additional drop shadow, to provide a sense of dimension and perspective. Perhaps we could keep the existing drop shadow, and add another one on top of it, and see how that looks.

**Comment by pinussilvestrus** [comment]
**Some quick feedback while playing around**

Cool stuff to play around with 👍 Some feedback from my side

* Are we sure about adding such a "gradient" to the FEEL-enabled state? I don't see it somewhere else and it kind of irritated me the first time I saw it.

![image](https://user-images.githubusercontent.com/9433996/172376293-ac18d221-b3f3-4a79-bb0f-dc967d56866f.png)

* Probably just a bug in the demo, but the "edited" dot is not visible on FEEL enabled

![image](https://user-images.githubusercontent.com/9433996/172376677-b0b0098b-3069-49cb-9224-0e26dac54eea.png)

![image](https://user-images.githubusercontent.com/9433996/172376712-dad08fe0-e2ca-45e8-98dd-4ff8c70e3733.png)

* Are we turning the input to a contenteditable once we enable FEEL? This one seems to be missing an accessible name, the label is also not linked to the div element (e.g. via [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role#description)). Therefore I can't focus the input when clicking the label.
![Kapture 2022-06-07 at 14 19 16](https://user-images.githubusercontent.com/9433996/172377278-8a1cd3e1-656f-4982-803d-3014f133dd22.gif)

* When enabling/disabling FEEL, the focus jumps to the input. I don't know whether I would expect this, is this intended behavior?

![Kapture 2022-06-07 at 14 21 00](https://user-images.githubusercontent.com/9433996/172377649-1d32a131-ec21-4a50-b153-d55f2393e2bb.gif)

**Comment by marstamm** [comment]
Thanks for your feedback @currandwyer .

5px shadow does look better.
![image](https://user-images.githubusercontent.com/21984219/172377309-f2a58c23-a7c6-41de-abb8-84499ddb9b55.png)

> Let's also experiment with adding an additional drop shadow, to provide a sense of dimension and perspective

I'm not sure if I understand this correctly. I find that outset shadows are hard to get right, as the button is inside of a input field and not free floating. So having a shadow beyond the bounds of the field does look weird. Do you mean 2 inset shadows that overlap, like this?

![image](https://user-images.githubusercontent.com/21984219/172378596-41d504cb-2143-46e3-b17e-aab5a1a94e2d.png)

**Comment by marstamm** [comment]
Thank you for your Feedback as well @pinussilvestrus 

> Are we sure about adding such a "gradient" to the FEEL-enabled state?

Open to discussion :slightly_smiling_face: 
See also the comment from @currandwyer regarding this. The Edge will probably be sharper and is meant to display the "enabled" state

> Probably just a bug in the demo, but the "edited" dot is not visible on FEEL enabled

Yes, this is just a bug in the demo. It is not as polished yet and was mainly created to user-test the feel actions. Same for the accessibility - i did not consider it for this demo but will keep it in mind for the full implementation.

> enabling/disabling FEEL, the focus jumps to the input

IMO, this is intended behavior when clicking, as looks like it is part of the input field. For toggeling with the keyboard, I would want to keep focus on the button, so this part would be a bug. Feel free to share your opinion on the intended behavior as well

**Comment by nikku** [comment]
Quick feedback on this state:

![image](https://user-images.githubusercontent.com/58601/172381904-6d1821d7-9427-4934-b20f-0c0ed4810e09.png)

I can hardly distinguish "can be feel, click to enable" from "is a feel expression".

If you ask me I'd rather invest in educating users about starting with `=` to write an expression than building a maybe confusing UI.

I'd keep both states ("can be feel" and "cannot be feel") empty, not allow "making it an expression" via UI, but rather ask users to simply type `=`. 

If the user types `=` in places that cannot be FEEL you'd not show the prominent `=` which could be enough distinction to tell them "this is not working the way you think it is".

**Comment by currandwyer** [comment]
@marstamm Yes exactly, I meant having two inner shadows that overlap. Sorry for the confusion. However, I like what @pinussilvestrus mentioned - are we sure that this inner shadow is really the right pattern here to indicate the active/inactive state? I actually am not sure it's right. Have we considered using color to create the distinction?

**Comment by marstamm** [comment]
I created a Demo with this option under https://marstamm.github.io/feel-editor-showcase/option2/

I played around with it a bit.
Should it still be possible to disable a feel field with a click? The button is there, but I can not go back using the mouse, so this feels wrong. But only restricting it to Keyboard might also be unintuitive

**Comment by barmac** [comment]
Some issues I noticed:

![image](https://user-images.githubusercontent.com/28307541/172548300-c2749f94-8291-498f-a06e-211e43a7bd34.png)

The "edited" dot next to _Custom Properties_ is gone when I use a FEEL expression.

![image](https://user-images.githubusercontent.com/28307541/172548458-b9438971-057e-4c34-80c4-d85c25111977.png)

It should state "FEEL" instead of "Feel".

I suspect that the color contrast as the only indicator for the three states (FEEL only/enabled/disabled) may be unnoticeable for some users. Think of people with visual impairments. Option 2 works better in that case.

**Comment by marstamm** [comment]
Integrated with https://github.com/bpmn-io/bpmn-js-properties-panel/pull/706
