### ISSUE TITLE
Something wrong in README.md

### ISSUE THREAD

**Issue by andyqier88** [bpmn-io/bpmn-js-properties-panel#667]
__Describe the Bug__

__Steps to Reproduce__

1. When I update [bpmn-js-properties-panel](https://github.com/bpmn-io/bpmn-js-properties-panel) v1.0.0 ,  there is a wrong link at the title `Use with Camunda properties`  in  [README.md](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/README.md)
![image](https://user-images.githubusercontent.com/10238991/163506855-c72c7c09-2024-4bb4-abb7-b5d11f8fadbe.png)

2. and i can not find the file in code below
```
// use Camunda properties provider
propertiesProviderModule = require('bpmn-js-properties-panel/lib/provider/camunda');
```
How can I import camunda in  bpmn-js-properties-panel@1.0.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting! The README was indeed a little outdated.

That will be fixed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/668. You can already have a look inside the changes to see how it works.
