### ISSUE TITLE
ID must be unique.

### ISSUE THREAD

**Issue by andyqier88** [bpmn-io/bpmn-js-properties-panel#682]
**When I use `new BpmnModeler` in vue3 like this**
```
<template>
<div id="canvas" class="canvas"></div>
    <div class="panel">
      <div id="js-properties-panel" ref="jsPropertiesPanel" class="panel"></div>
    </div>
</template>
<script lang="ts">
  import { defineComponent, reactive, onMounted } from 'vue';
  .....
  export default defineComponent({
    setup(props, { emit }) {
      let stateData = reactive({
        bpmnModeler: null
      });
   })
  })
  onMounted(() => {
    stateData.bpmnModeler = new BpmnModeler({
          container: '#canvas',
          propertiesPanel: {
            parent: '#js-properties-panel',
          },
          additionalModules: [
            BpmnPropertiesPanelModule,
            BpmnPropertiesProviderModule,
            CamundaPlatformPropertiesProviderModule,
            CamundaExtensionModule,
            {
              translate: ['value', customTranslate],
            },
          ],
          moddleExtensions: {
            camunda: camundaModdleDescriptor,
          },
        });
  })
```
**There is an error tip(see img below), I'm sure the ID really exists in my xml**
![image](https://user-images.githubusercontent.com/10238991/168573950-79ea97d8-45a2-47b7-8346-1446bb355347.png)

**after i debugger this problem ,I found different types see img below**
<img width="926" alt="20220516181649" src="https://user-images.githubusercontent.com/10238991/168573714-71335e56-0915-469e-9825-c68919a03cd5.png">

**I solved the problem by not using `Proxy` method, It's better to support `Proxy`**

**Comment by sitleon** [comment]
Hi I am facing same issue as you described. May I know the way you solved it by `not using Proxy method` ?

**Comment by andyqier88** [comment]
> Hi I am facing same issue as you described. May I know what is the way you solved it by `not using Proxy method` ?

we can `new BpmnModeler` like official demo show 
```
// global variable in current component 
let bpmnModeler = null 
bpmnModeler = new BpmnModeler({
....
})
```
hope it is helpful to you

**Comment by nikku** [comment]
Vue does proxify all things which can cause issues with libraries that do not expect this.

A common workaround is to mark your non-vue libraries as raw, cf. [`markRaw()` documentation](https://vuejs.org/api/reactivity-advanced.html#markraw).

Please report back if that fixes your issue.

**Comment by andyqier88** [comment]
> Vue does proxify all things which can cause issues with libraries that do not expect this.
> 
> A common workaround is to mark your non-vue libraries as raw, cf. [`markRaw()` documentation](https://vuejs.org/api/reactivity-advanced.html#markraw).
> 
> Please report back if that fixes your issue.

thanks for reply, `markRaw()` also can solve this issue
