### ISSUE TITLE
Removed input value re-appears in template defined text field

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#685]
__Describe the Bug__

As a user, when removing the input of a required field it is actually not removed (it is invalid and this not persisted). Instead it re-appears when I re-select the element:

![restthingproperties](https://user-images.githubusercontent.com/58601/168973501-dfc75dcc-c1c9-4b60-8ea8-138b64150a90.gif)

__Steps to Reproduce__

* Model a template task `A` with a required `text` binding
* Input text `FOO` => validation error disappears
* Remove text => validation error appears
* Focus another element, and focus `A` again
* __You see that `A` has `FOO` as an input text again__

__Expected Behavior__

I'd expect the value to actually be removed, similar to how we handle most errors nowadays.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Linux (Any)
- Library version: v1.0.0

----

Initially reported as connectors feedback [via this channel](https://camunda.slack.com/archives/C034N0E5YCX/p1652798095398369)

**Comment by nikku** [comment]
Intuitively for me this is a case for linting (and our lighter version of validation).

CC @andreasgeier

**Comment by nikku** [comment]
@christian-konrad Could you have a look into this, understand and assess it?

**Comment by ev-codes** [comment]
The Connectors team is not able to reproduce this bug anymore.

I would like to close this issue, but I don't have permission to do this.

@nikku would you be able to close this issue if you agree?

**Comment by nikku** [comment]
@ev-codes Thanks for the update. I'll close this.
