### ISSUE TITLE
Implement Conditional Template Activation

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js-properties-panel#690]
__What should we do?__

https://github.com/camunda/product-hub/issues/81

## Breakdown

- [x] https://github.com/camunda/element-templates-json-schema/issues/54
- [ ] Release stable version of json schema
- [x] implement for C8: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/711
  - [x] Properties panel shows entries based on condition 
  - [x] Condition mechanism  
  - [x] Adding/removing properties based on condition in xml
      - [x] on applying template 
      - [x] on value change shema
- [x] Documentation for element templates
  - [x] Update [element template docs](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/) -https://github.com/camunda/camunda-platform-docs/pull/1008
  - [x] Update [examples]( https://github.com/camunda/camunda-modeler/blob/master/resources/element-templates/cloud-samples.json) - https://github.com/camunda/camunda-modeler/pull/3008
- [ ] To be clarified: direct documentation and guidance for Conenctors (TBD)?

__Why should we do it?__

We want to make element templates more powerful and simpler for developers.

**Comment by smbea** [comment]
I spiked on the overall architecture of applying/removing conditions (with HTTP method example). This is the main points of the structure I achieved:

* **Showing entries in properties panel [`CustomProperties.createCustomEntry`]:** The entries shown in the properties panel are defined according to the properties in the template (unrelated to the xml). Therefore, we need to check that the condition is met in order to show the entry. 

``` javascript
if (isDefined(property.condition) && !checkCondition(element, template, property)) {
    // don't return entry -> entry is not applied
    return;
  }
```

* **Applying template [`ChangeElementTemplateHandler`]:** On applying template for the first time, check if condition is met for conditional properties, and if not do not apply them.

```javascript
// applies to all types of properties
_updateZeebeInputOutputParameterProperties(element, oldTemplate, newTemplate) {
...
  newProperties.forEach((newProperty) => {
    if (isDefined(newProperty.condition) && !checkCondition(element, newTemplate, newProperty)) {
       return;    // don't apply property
   }
})
... // apply property
}
```

* **Triggering condition check based on parent value change [`ChangeElementTemplateHandler.propertySetter`]**:  After updating property, check if property changed has dependant properties. If so, call propertySetter for each

```javascript
dependantProperties.forEach(property =>{
     propertySetter(bpmnFactory, commandStack, element, property, template)();
});
```
and add the following condition to the propertySetter before setting a given value:
```javascript
if (isDefined(property.condition)
     && checkCondition(element, template, property)
     && isUndefined(value)) {
        return;
}
```

---

**To consider:** default values for conditional properties. Consider example and if we should actually allow it:
* **Before** -> default values are set when applying template 
* **After** -> since conditional property won't be present in xml id not set, how to apply defaultValue when condition is met
   * **Example use case:** _Response body_ has default value. Initially, field appears empty because _http method_ selected is "GET". When method is changed to "POST", the _Response body_ value should the value would change to the default value

---

Screencast of spike result:

https://user-images.githubusercontent.com/25825387/170277238-92949dce-0ab1-42d8-ae1d-69d032d198e3.mov

**Comment by barmac** [comment]
Since https://github.com/camunda/element-templates-json-schema/issues/54 is closed, I will release an alpha of the JSON schema so that we can test it with the properties panel.

**Comment by barmac** [comment]
@smbea and I had today a super productive session around this. We are having a good progress towards a robust solution. Today, we worked on "Properties panel shows entries based on condition". The idea is to filter the properties before entries are created so that entries don't need to know about the condition mechanism.

Next step will be to implement the XML part of the epic.

**Comment by barmac** [comment]
I've pushed tests for XML updates via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/acdc8dbc7723d1ba1d77c101e6534557fa59e7d3

**Comment by barmac** [comment]
I tried to solve the blocker via a CommandInterceptor as I believe we need to include the condition mechanism in a single command just like we do with the behaviors. This means that when user triggers undo, this will at the same time undo the change in the properties as well as all of the changes triggered by the condition mechanism. However, it seems there is no single event in the command stack which is fired only once. If I listen to `element.updateModdleProperties`, my changes will also trigger the listener which leads to an infinite loop. I've also considered `commandStack.postExecuted`, but it's triggered multiple times when we use multi-command handler. Bottom line is this task will take more time than we assumed.

**Comment by barmac** [comment]
@smbea will try out a new idea how to prevent infinite loop of updates when conditional logic is applied. We want to use a flag to indicate that a change is applied as part of condition updates. It feels a bit dirty but pragmatic at the same time.
![Untitled-2022-03-09-1458](https://user-images.githubusercontent.com/28307541/172573355-85ecfb0d-1cca-48b3-a8f3-d56e40fcdaeb.png)

An alternative we considered is to pull one change at a time, but this could lead to `n` nested commands where `n` is the properties to be removed/added number.

**Comment by smbea** [comment]
I implemented the discussed solution in this branch: https://github.com/bpmn-io/bpmn-js-properties-panel/compare/master...template-conditions-cloud. We were playing around with this for platform but since the primary focus should be for cloud, I changed that. 

Currently, I still face an issue. With an optional conditional field that has a default value: when trying to set this as null, if defaults to the default value. I haven't figured out how to fix this with the current strategy.

I will have a chat with Nico and present this strategy and see if we should continue with this or look at another approach.

**Comment by smbea** [comment]
**Outcome of my chat with Nico:**

I'm going to try a mixture of my initial solution with dependant properties and the last one with the commandInterceptor.
The idea is to intercept `element.updateProperties`, check the dependant properties and maybe use propertySetter to change them instead of re-applying the template (which was less predictable)

**Comment by nikku** [comment]
Let's update the status on this one (cf. https://camunda.slack.com/archives/GP70M0J6M/p1657356752344829?thread_ts=1657316523.879639&cid=GP70M0J6M).

**Comment by barmac** [comment]
Documentation is now merged so we can close this.

**Comment by CatalinaMoisuc** [comment]
@barmac I think there is one thing left in the epic:

>  - [ ] To be clarified: direct documentation and guidance for Conenctors (TBD)?

**Comment by barmac** [comment]
Let's clarify this.

**Comment by christian-konrad** [comment]
@barmac @CatalinaMoisuc I added an issue accordingly for the connectors template/integration framework documentation.

**Comment by nikku** [comment]
As long as this is documented in the element template documentation we're fine. And we did that.

There is nothing more that we shall document (at least I don't see it).

> I added an issue accordingly for the connectors template/integration framework documentation.

Which issue did you add?

**Comment by barmac** [comment]
This is covered via https://github.com/camunda/camunda-platform-docs/issues/1050

**Comment by CatalinaMoisuc** [comment]
FYI, @christian-konrad @smbea @barmac See: https://github.com/camunda/camunda-platform-docs/issues/1050#issuecomment-1180258777
