### ISSUE TITLE
Can you provide an event to get the current active Properties Panel information

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js-properties-panel#692]
__Is your feature request related to a problem? Please describe__
The panel property information for the current activity was available through the 'propertiesPanel.changed' event in version 1.0 or earlier, but is not available in recent versions
```
EventBus.on('propertiesPanel.changed', async (event: any) => {
      const tabs = event.current.tabs;
  });
```

__Describe the solution you'd like__
Can you provide an event to get the currently active property panel group information.I want to be able to get the panel properties currently active so that I can develop the properties panel in other Web languages

__Describe alternatives you've considered__
None.

__Additional context__
None.

**Comment by smbea** [comment]
In the latest properties panel, we fire `propertiesPanel.updated`, see: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/c4aae33217a960f19f389ea6c861008c743e6c18/src/render/BpmnPropertiesPanel.js#L71
