### ISSUE TITLE
Element Template Version with created metadata should include time

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/bpmn-js-properties-panel#694]
__Problem Description__

When multiple versions of a template are published at the same date, it is impossible to distinguish them and the "Update available" dropdown contains confusing information for the user as the new version date string is the same as the one of the currently used template:

![image](https://user-images.githubusercontent.com/8982136/171161681-7417b13d-68a6-40c7-9dde-68301d96a2ed.png)

__Solution Description__

Also include the time in the version information.

**Comment by MaxTru** [comment]
Can reproduce. Also makes sense to me, since we anyhow have a full timestamp available. Proposing for `ready`
