### ISSUE TITLE
Group titles overlap element template overlays

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-properties-panel#697]
__Describe the Bug__

When opening an element template overlay (e.g. "Updated available"), the group titles overlap them which breaks the design.

![image](https://user-images.githubusercontent.com/9433996/172391397-c63e07f4-7139-49cc-a52f-8a1910f6dfbc.png)

__Steps to Reproduce__

1. Execute `npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel#master" -c "npm run start:cloud-templates"`
2. Select the "outdated" task
3. Open the "Updated available" overlay
4. See the "Custom properties" title overlaps it

__Expected Behavior__

Overlays should always be on top.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 102.0.5005.61
- OS: macOS 11.6.5
- Library version: current `master`

**Comment by pinussilvestrus** [comment]
It really seems like that `position: sticky` and using overlays via group header buttons do not work properly together. What we could do is disable the sticky header behavior for the element templates group only.

```css
.bio-properties-panel-templates-group .bio-properties-panel-group-header {
  position: initial;
}
```

![image](https://user-images.githubusercontent.com/9433996/172839468-f705550a-372e-41e8-98fc-702c38986ca6.png)

/cc @barmac @MaxTru @nikku 

-----

Sticky headers currently anyway don't work properly for the `ElementTemplatesGroup` as we use a custom group implementation (not using the `useStickyIntersectionObserver` hook).

![Kapture 2022-06-09 at 13 37 51](https://user-images.githubusercontent.com/9433996/172839692-9cc4c77e-0f0c-4b6b-bb4c-983fbb9a43c0.gif)

**Comment by pinussilvestrus** [comment]
Moving this to ready as I think that should be fixed rather soon.

**Comment by smbea** [comment]
Agreeing with Nikklas: since we have a custom implementation, the `useStickyIntersectionObserver` is not being used. And it would require some refactoring to include it because we're working a class component. For now we should just remove the sticky position for element templates - so it doesn't look broken - and tackle this later if we see fit.
