### ISSUE TITLE
Automatically resize text areas (+ text fields that can be multi-line)

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#713]
__Is your feature request related to a problem? Please describe__

As a user I'm often editing text that may be multi-line (or single line).

I'm struggling to use the properties panel as the text input controls don't work intuitive for me:

* Text areas are not sized by content but instead fixed to three lines. This is too much for no content, but not enough for any reasonable amount of text
* Text fields (i.e. `Name`) can sometimes be multi-line. I'd expect them to be single line per default but expand sensibly on multi-line inputs.

__Describe the solution you'd like__

Support for automatic resizing of _all_ text areas that are not by definition "single line":

* Single line text fields can resize to multi-line fields
* Text areas can resize (expand) up to a maximum size
* Intially text area and single line fields render based on the content (up to a certain constraint).

I want these changes to be applied _consistently_ so our users get to enjoy a uniform UX.

__Describe alternatives you've considered__

None.

__Additional context__

I believe we did have a better UX around multi-line fields in `bpmn-js-properties-panel@0.x`.

Related to https://github.com/bpmn-io/properties-panel/issues/25

-----

The following shows my usual flow of "editing" multi-line text:

![capture WE6RXC_optimized](https://user-images.githubusercontent.com/58601/176915246-57d854d9-9bef-45fa-883b-be773a7a0ce8.gif)

**Comment by nikku** [comment]
Moving to `ready` to see (review) how far we are off from consistently fixing this. We invested in the past.

**Comment by jarekdanielak** [comment]
The problem here seems to be that the text area you are using for demonstration doesn't have `autoResize` property set to `true`. 

Is this still relevant? Can you suggest which fields should have `autoResize` turned on?

**Comment by barmac** [comment]
Perhaps we want to autoresize all text areas? Make it the new default.

**Comment by nikku** [comment]
We want indeed to auto-resize all text areas (that are not by definition "single line"). This ensures a uniform UX across the whole properties panel. Cf. also https://github.com/camunda/camunda-modeler/pull/4429#issuecomment-2247787963.

**Comment by jarekdanielak** [comment]
Fixed upstream in [bpmn-io/properties-panel@3.23.0](https://github.com/bpmn-io/properties-panel/releases/tag/v3.23.0)
