### ISSUE TITLE
jQuery Properties Panel Renderer Parent Node

### ISSUE THREAD

**Issue by PaulLunkenheimer-viadee** [bpmn-io/bpmn-js-properties-panel#729]
__What should we do?__

Pre 1.0 one could attach the properties panel to a parent node which was provided as jQuery (see [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/v0.46.0/lib/PropertiesPanel.js#L411)). Now, this seems to have been deprecated (see [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/BpmnPropertiesPanelRenderer.js#L59)).
I wonder if this was a conscious decision?

__Why should we do it?__

Supporting jQuery as parent node to the properties panel would be
- practical
- in line with previous releases (see [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/v0.46.0/lib/PropertiesPanel.js#L411))
- especially it would go along with the way it is done in bpmn-js itself (see for example [here](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/BaseViewer.js#L584)).

**Comment by nikku** [comment]
Thanks for opening this issue. It is definitely something that we want to support, given the reasons you stated above. Feel free to PR the feature back into the 1.0 feature set.
