### ISSUE TITLE
Review HTML Markup & Styles in Prop Panel

### ISSUE THREAD

**Issue by meyerdan** [bpmn-io/bpmn-js-properties-panel#73]

**Comment by nikku** [comment]
@zeropaper The changes you introduced break the test suite on Chrome and Firefox:

> Chrome 46.0.2490 (Linux 0.0.0): Executed 146 of 146 (6 FAILED) (10.806 secs / 1.117 secs)

**Comment by zeropaper** [comment]
and I pushed to master?
if i did: feature branches <3
if i didn't: feature branches <3
i'll check it out asap..
:)

**Comment by zeropaper** [comment]
(and thx for the travis badge as well!)

**Comment by gimbel** [comment]
Nico said its done
