### ISSUE TITLE
Support `zeebe:property` for templating

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#731]
__Is your feature request related to a problem? Please describe__

We want to support templating for the generic [`zeebe:property`](https://github.com/camunda/zeebe/issues/9868) BPMN extension.

By doing so we open a wide range of use-cases for users to build re-usable building blocks where configurating is not important to Zeebe, but to external systems (i.e. inbound connectors).

__Describe the solution you'd like__

* [ ] I can bind a template property to `zeebe:property` in a way I can bind to `zeebe:input`
* [ ] `optional` is supported, i.e. optional `zeebe:property` binding is only serialized if it is user (or default value) defined

__Describe alternatives you've considered__

None.

-----

Depends on https://github.com/camunda-cloud/zeebe-bpmn-moddle/issues/30
Depends on https://github.com/camunda/element-templates-json-schema/issues/65
Related to https://github.com/camunda/zeebe/issues/9868
Related to https://github.com/camunda/product-hub/issues/335

**Comment by christian-konrad** [comment]
Currently no time in this iteration, moving into 'backlog' to be picked up later.

**Comment by menski** [comment]
FYI the Zeebe part was implemented with https://github.com/camunda/zeebe/pull/9955, and will be released with 8.1.0-alpha5 beginning of September, but can already be tested with the latest SNAPSHOT

**Comment by nikku** [comment]
Picking this up myself to work on it next week.

**Comment by PreetiNirwal** [comment]
Thanks @philippfromme!
