### ISSUE TITLE
the experience of User assignment when we select Assignee and Candidate groups and Candidate users

### ISSUE THREAD

**Issue by andyqier88** [bpmn-io/bpmn-js-properties-panel#744]
__Is your feature request related to a problem? Please describe__
when A newer for process design based on` bpmn-js` and `bpmn-js-properties-panel`, we confused about relationships between Candidate groups and Candidate users

__Describe the solution you'd like__

can we write a value in Assignee of User assignment, we disable Candidate groups and Candidate users for a more friendly experience 

I do not konw it is reasonable or not

**Comment by ingorichtsmeier** [comment]
See my comment here: https://forum.camunda.io/t/the-different-of-camunda-assignee-betwwen-camunda-candidateusers-and-camunda-candidategroups/39634/2
