### ISSUE TITLE
Panel header can not be translated

### ISSUE THREAD

**Issue by Abimostu** [bpmn-io/bpmn-js-properties-panel#813]
__Describe the Bug__
I tried to translate the whole bpmn modeler, and i find panel header could not be translated.
This question is the same as isue #537 .
the changelog shows it fixed at v1.11.0.
the picture shows MESSAGE START EVENT could not be translated
![WX20221118-162707](https://user-images.githubusercontent.com/16587503/202674435-5a77c819-4d1a-4c80-9bf5-832b8e19987d.png)

and i try to debug and read the source code 
i find  PanelHeaderProvider still didn't do any translation

![WX20221118-174824@2x](https://user-images.githubusercontent.com/16587503/202676483-8d70de06-cc1e-45cb-b1af-5a379bfcd2d0.png)

__Steps to Reproduce__

1. add customTranslateModule
`const modeler = new BpmnModeler({
    container: '#canvas',
    height: '100vh',
    keyboard: {
      bindTo: window
    },
    propertiesPanel: {
      parent: '#properties'
    },
    additionalModules: [
      BpmnPropertiesPanelModule,
      BpmnPropertiesProviderModule,
      customTranslateModule,
    ]
  });`
2. panel header no translated

__Expected Behavior__

header labels should be translated.

__Environment__

- Host : Edge 107.0.1418.42  (arm64) / node v18.12.1
- OS: macOS 13.0.1
- Library version:     "bpmn-js-properties-panel": "^1.11.1"  master branch 
-

**Comment by pinkheader** [comment]
你的常规和文档这些团体标签怎么翻译的啊，我是用的bpmn-js-properties-panel@1.3.0这个版本，使用translate这个模块没法翻译。

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1045.
