### ISSUE TITLE
Add ability put more then one condition to connector template

### ISSUE THREAD

**Issue by Oleksiivanov** [bpmn-io/bpmn-js-properties-panel#817]
__Is your feature request related to a problem? Please describe__

As a developer, I want to have the ability to use multiple conditions in the connector template for do section available when a few different properties equal different values;

For now, we can use only this way : 

```json
 "condition": {
        "property": "propertyType",
        "equals": "propertyValue"
      }

```

__Describe the solution you'd like__

I think that we can add `conditions` in the Connector template, and this will looks like this (concatenate with `AND`): 

```json
  "conditions": [
    {
      "property": "property_A_",
      "equals": "propertyValueA"
    },
    {
      "property": "property_B_",
      "equals": "propertyValueB"
    },
    {
      "property": "property_C_",
      "oneOf": ["a","b"]
    }
  ]
```

__Describe alternatives__

Keep the flat condidition structure, but allow additional composition:

```json
  "condition": {
    "allMatch": [
      {
        "property": "property_A_",
        "equals": "propertyValueA"
      },
      {
        "property": "property_B_",
        "equals": "propertyValueB"
      },
      {
        "property": "property_C_",
        "oneOf": ["a","b"]
      }
    ]
  }
```

__Additional context__

https://user-images.githubusercontent.com/108869886/204005549-2f1b322f-0033-4628-8b14-8452a9d28034.mov

**Comment by nikku** [comment]
@Oleksiivanov Did this pop up internal or based on user feedback?

**Comment by MaxTru** [comment]
Should these conditions be connected via a logical `AND` or `OR`? Or should this be configurable?

**Comment by nikku** [comment]
Moving to backlog for the time beeing.

**Comment by MaxTru** [comment]
@nikku, @CatalinaMoisuc given https://github.com/bpmn-io/bpmn-js-properties-panel/issues/817#issuecomment-1398087061, could you please evalaute whether this can be tackled as one of the next iterations?

**Comment by nikku** [comment]
Discussing this in next planning session.

**Comment by nikku** [comment]
@Oleksiivanov Please share two end-to-end examples of what you'd like to accomplis:

* What you have to do today
* What you'd like to accomplish (how multiple conditions support you)

This allows us to better evaluate the impact of this enhancement.

**Comment by nikku** [comment]
I guess you refer to https://github.com/camunda/product-hub/issues/81#issuecomment-1134585413, right? 

I'm nowadays in favor of "all" or "allMatch" over "and". Alternative could be "someMatch" or "some" for _OR_ concatenation.
