### ISSUE TITLE
Input mappings defined by templates not stable

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#838]
__Describe the Bug__

As a user I define element template properties in a dedicated order. As it looks like that order is not uphelt as input mappings are created. In fact it seems like we attach the last saved last in the `<zeebe:ioMapping>` list. This leads to dependent mappings not being evaluated consistently (https://github.com/camunda/web-modeler/issues/3251). 

![capture NxgZqR_optimized](https://user-images.githubusercontent.com/58601/207800985-da95607c-1a2b-4308-934a-e60b250ca815.gif)

The whole behavior is bogus to the user, and cannot worked around without knowing.

__Steps to Reproduce__

1. configure [`dependent-io.json` template](https://github.com/bpmn-io/bpmn-js-properties-panel/files/10234754/dependent-io.json.txt)
2. Model `Dependent Mapping` task
2. Change values of `First*`
3. See that we move each one of them (`zebee:input`, `zeebe:output`, `zeebe:property`) below dependent property

__Expected Behavior__

* Upon modification we uphold the order of properties defined in the template.
* Upon entry addition (i.e. conditionally enabled) we uphold the order of properties defined in template.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: 1.12.0

**Comment by nikku** [comment]
I've investigated the issue and concluded this is not an easy fix. 

Added [failing test cases](https://github.com/bpmn-io/bpmn-js-properties-panel/compare/838-stable-property-order), and moving to `ready` to be picked up in an orderly manner next year.

**Comment by nikku** [comment]
Adding the blocker label just now. 

This impacts Camunda connectors in a large scale, as it prevents real-world re-use of inbound webhook and outbound REST/JSON ([ref](https://camunda.slack.com/archives/C0350959WG1/p1671453655773349), [ref](https://camunda.slack.com/archives/C0350959WG1/p1671484548468209)). We should pick this up with priority in early 2023.

CC @CatalinaMoisuc @christian-konrad

**Comment by MaxTru** [comment]
> Adding the blocker label just now.
> 
> This impacts Camunda connectors in a large scale, as it prevents real-world re-use of inbound webhook and outbound REST/JSON ([ref](https://camunda.slack.com/archives/C0350959WG1/p1671453655773349), [ref](https://camunda.slack.com/archives/C0350959WG1/p1671484548468209)). We should pick this up with priority in early 2023.
> 
> CC @CatalinaMoisuc @christian-konrad

+1 @nikku 

@CatalinaMoisuc and @christian-konrad this really is a big thing and it would be great if you could prioritize this asap

**Comment by nikku** [comment]
@christian-konrad already bought into it. We'll prioritize this right as 2023 starts. :fireworks:

**Comment by marstamm** [comment]
Interestingly, this is not an issue with the normal io-mapping list, as we just update the moddle element instead of creating a new one:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/a8efd390ad021789529ee3975f228ce8650fb5e2/src/provider/zeebe/properties/InputOutputParameter.js#L83-L89
