### ISSUE TITLE
<camunda:properties> in Extension Elements get lost during Roundtrip

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js-properties-panel#84]
Reproduce:
- open bpmn that contains camunda properties in extension elemts
- make a change and save it

Problem
- extension elemets with camunda properties are lost

![image](https://cloud.githubusercontent.com/assets/3829733/11187201/d4a6938e-8c85-11e5-9dc6-04012252d45d.png)

**Comment by nikku** [comment]
Closed via a3f06aea2277da87fb3236babad215fb44ab20e8
