### ISSUE TITLE
Support placeholders for inputs in an element template

### ISSUE THREAD

**Issue by mbiciin** [bpmn-io/bpmn-js-properties-panel#852]
__Is your feature request related to a problem? Please describe__

I need to have a default value in some input fields, a value that will be filled automatically after I delete the value introduced manually. I tried to use the prefilled values, but they don't have this behavior. I did some tests and I saw that they are filled just once, after the update of the template in the diagram. If you change of it in the diagram, you won't be able to get back the default value. The modeler tries to keep the value introduced manually by the user. 
There is also an exceptional case when the prefilled value is not updated in the diagram, even if you're using optional:
- update the prefilled value in the template,
-  publish the template
- open the diagram
- change the value of the input field for which you're using the prefilled value
- update the template
We decide to use the prefilled values for the hidden fields that can't be changed by the user.

__Describe the solution you'd like__

- Placeholders will be useful for input fields that will have the same value most of the time, but we want to let the user change it if needed. 
- The user will be able to change the value manually, but if this value is deleted, the user will have back the default value completed automatically.
- The implementation of element templates should live in  https://github.com/bpmn-io/bpmn-js-properties-panel. 
- We consider the placeholders (https://www.w3schools.com/tags/att_input_placeholder.asp) useful for the custom element templates that we plan to support in the future. 
__Describe alternatives you've considered__
For now, as a workaround, we add notes and documentation links in the description of the fields. 

__Additional context__
These custom templates have to be very user friendly so the placeholders  will be a great feature in some cases.

**Comment by marstamm** [comment]
Hi @mbiciin , thank you for opening this issue. What Problem are you trying to fix with placeholders? 

It is possible to add default values to element templates [by setting the `value` property](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/#defining-template-properties). Does this already solve your problem?
![image](https://user-images.githubusercontent.com/21984219/212301448-be3f868d-de55-49f3-83e8-368a044e44bf.png)

Please also adjust the Ticket to use the [Feature Request Template](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md), so everyone can follow your train of thought.

Cheers!

**Comment by mbiciin** [comment]
Hi @marstamm 

I updated the ticket. Please, let me knw if you need more details.

**Comment by nikku** [comment]
> Placeholders will be useful for input fields that will have the same value most of the time, but we want to let the user change it if needed.

@mbiciin I'm not sure if that is what I expect of a placeholder. As far as I am concerned a placeholder gives me a hint on the (optional) semantic contents of a field. If the field assumes certain _default_ value I assume it to be pre-filled with that default value.

So if I understand correctly we think about two things here:

* Default values => Must be pre-filled
* Placeholders, short visual hints what may be entered


Cf. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#placeholder):

> The placeholder attribute is a string that provides a brief hint to the user as to what kind of information is expected in the field. It should be a word or short phrase that demonstrates the expected type of data, rather than an explanatory message.

**Comment by marstamm** [comment]
+1 @nikku 

The behavior described in https://github.com/bpmn-io/bpmn-js-properties-panel/issues/852#issuecomment-1386984915 would rather be achieved with an initially empty input, where the default value is applied either in the backend service or through a hidden input, not with a placeholder attribute

**Comment by nikku** [comment]
Guess placeholders (in the HTML sense) are still a valid feature request. Moving to backlog.

**Comment by nikku** [comment]
Implemented via https://github.com/bpmn-io/bpmn-js-element-templates/issues/92.
