### ISSUE TITLE
I as a Zeebe user should be able to set a retry backoff for failed jobs

### ISSUE THREAD

**Issue by aivinog1** [bpmn-io/bpmn-js-properties-panel#860]
### Is your feature request related to a problem? Please describe.

In this task, we should support [this](https://github.com/camunda/zeebe/issues/11101) in the properties panel for Zeebe Service Task (in the same way that retries are supported now).
Note that this task is blocked by https://github.com/camunda/zeebe-bpmn-moddle/issues/42.

### Describe the solution you'd like

I suppose that there should be additional input right after Retries. But I'm open to discussion. 

### Describe alternatives you've considered

Maybe we should combine retries and retry backoff into one input and parse them (i.e. something like `R3/P1DT1S` - it means we should retry 3 times with a backoff of 1 day and 1 second). But I think that we should consider this carefully. Personally, I'm voting for the approach that I described earlier.

### Additional context

[The BPMN API has already been negotiated](https://github.com/camunda/zeebe/pull/11339#pullrequestreview-1241821331). Also, I would like to take care of it by myself, so you can assign this to me.

**Comment by ingorichtsmeier** [comment]
See my comment here: https://github.com/camunda/zeebe/issues/11101#issuecomment-1410735637

**Comment by nikku** [comment]
Closing this issue. Let's re-open it once we have clarity what the desired editor support looks like. Let's use https://github.com/camunda/camunda-modeler/issues/3419 to define that support.
