### ISSUE TITLE
 'propertiesPanel' does not exist in type 'BaseViewerOptions'

### ISSUE THREAD

**Issue by soorireddy** [bpmn-io/bpmn-js-properties-panel#903]
### Describe the Bug

Argument of type '{ container: string; propertiesPanel: { parent: string; }; additionalModules: any[]; }' is not assignable to parameter of type 'BaseViewerOptions'.
  Object literal may only specify known properties, and 'propertiesPanel' does not exist in type 'BaseViewerOptions'.ts(2345)

### Steps to Reproduce
   "bpmn-js": "12.0.0",
   "bpmn-js-properties-panel": "1.20.3",
 "@bpmn-io/properties-panel": "1.7.0",

1. upgrade bpmn-js & properties panel
 
NOTE :  

### Expected Behavior

Should be able to view Properties panel 

### Environment
 "@angular/core": "15.2.4", & typescript

**Comment by nikku** [comment]
@philippfromme Is this an issue with our newly released type definitions?

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/pull/1884.

**Comment by nikku** [comment]
Fixed with `bpmn-js@12.1.0`
