### ISSUE TITLE
Limiting Variable suggestions in element templates to I/O-Mappings is to restrictive

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/bpmn-js-properties-panel#904]
### Describe the Bug

With https://github.com/bpmn-io/bpmn-js-properties-panel/pull/902 we limit which templated elements get variable suggestions. We only show it for Input/Output mappings.

However, there are many other properties where we can safely suggest variables, e.g. `zeebe:taskDefinition`, `zeebe:assignmentDefinition`, or all `zeebe:taskSchedule` attributes

### Steps to Reproduce

1. Create and apply an element template with the property:
```json    
   {
      "type": "String",
      "feel": "optional",
      "value": "task-type",
      "binding": {
        "type": "zeebe:taskDefinition:type"
      }
    }
```
2. start typing the expression
3. no variable suggestions are shown 

### Expected Behavior

As the expression is evaluated by the engine, I get suggestions for the available variables.

### Suggested Changes

Instead of having a white-list of allowed bindings, suggest variables by default and only disallow bindings which are known to only be used by external systems, such as `zeebe:TaskHeader` and `zeebe:property`

### Environment

- Library version: 1.20.3

**Comment by nikku** [comment]
:see_no_evil: Better unrestrict ourselves slowly I guess, than giving wrong advice :rofl:

**Comment by nikku** [comment]
Moving to `ready`. It effectively is a 5.10 regression.
