### ISSUE TITLE
Allow partial update and save of property groups

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-properties-panel#91]
Property groups should be saved independently, keeping dirty (unsaved and invalid) state in other groups.

**Comment by nikku** [comment]
Isn't that already implemented with the latest save changes?

**Comment by pedesen** [comment]
Yep. Implemented in https://github.com/bpmn-io/bpmn-js-properties-panel/commit/6cd090000b83a24b42545482da28d8bb4d1afe0a.
