### ISSUE TITLE
Example data is not shown anymore in autocompletion

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/bpmn-js-properties-panel#934]
### Describe the Bug

Example data is not shown anymore in autocompletion.

### Steps to Reproduce

1. Add example data to one task
2. Try to complete it in a FEEL expression of another task
3. None of the example variables appear

https://github.com/bpmn-io/bpmn-js-properties-panel/assets/56470362/36051c7c-e52a-4f11-aa04-4c3dad370463

### Expected Behavior

All example data is shown in autocompletion as before.

### Environment

- Camunda Web Modeler as of June 6th 2023
- Desktop Modeler 5.12-rc0

**Comment by barmac** [comment]
It works OK in the element's output mapping, but not in the no outputs mapping case:

(https://docs.camunda.io/docs/components/modeler/data-handling/)

> If an element has output mappings, the data will only be available in the element itself. 

This works.

> Otherwise, all variables will be passed to the parent scope.

This doesn't.

**Comment by barmac** [comment]
It did not work as documented already in 5.11.0.

https://github.com/bpmn-io/bpmn-js-properties-panel/assets/28307541/89c870cb-13e8-494a-99a1-e39b25d0144c

**Comment by barmac** [comment]
Last and only version it worked as documented was 5.10.0

**Comment by barmac** [comment]
This should be fixed in https://github.com/camunda/example-data-properties-provider

**Comment by barmac** [comment]
OK so this is closed as not planned.
