### ISSUE TITLE
Camunda 8 Form Reference

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-properties-panel#949]
The upcoming form deployment and linking feature will allow users to link to a deployed form through the properties panel. If the user chooses to embed, the existing _Form JSON Configuration_ field is shown.

![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/7633572/c0fb5084-02a3-4109-ad1a-d30aa29c1675)

If the user chooses to link, a new _Form ID_ field is shown.

![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/7633572/3df882c7-deb0-4901-9a0c-20d022481a82)

### Tasks

- [ ] add select option for linked form
- [ ] add text field form ID

---

Product Hub Issue: https://github.com/camunda/product-hub/issues/419
Figma: https://www.figma.com/proto/ArESsfaYnKWs9XFJl0WgvW/Form-deployment?page-id=381%3A18143&type=design&node-id=408-17411&viewport=2287%2C1554%2C0.22&t=NTbiEanf5Udhzjts-1&scaling=scale-down&starting-point-node-id=408%3A17411

**Comment by philippfromme** [comment]
Example XML from the [specification](https://docs.google.com/document/d/13FTH_lDAJYnQf_YG15szJas7GsGGcNF-LT-mqTSCOf0/edit):

```xml
<bpmn:userTask id="Activity_0b43p4y" name="fdtest1_usertask">
  <bpmn:extensionElements>
    <zeebe:formDefinition formKey="camunda-forms:bpmn:ref:Forms_02jku8d" formType="ref"/>
  </bpmn:extensionElements>
  <bpmn:incoming>Flow_0w8lgy5</bpmn:incoming>
  <bpmn:outgoing>Flow_0qfcqby</bpmn:outgoing>
</bpmn:userTask>
```

**Comment by nikku** [comment]
@philippfromme I updated this to comply with the latest (and agreed upon) specification that uses `formDefinition#formId` for external form linking.

**Comment by nikku** [comment]
We'd want to update https://github.com/camunda/zeebe-bpmn-moddle/pull/49 accordingly.

One thing [I flagged](https://github.com/camunda/zeebe-bpmn-moddle/pull/49#issuecomment-1677629179) (CC @YanaSegal) is that I'd like to establish external linking as a pattern _immediately_. Hence I propose to change the labels:

* Embedded -> `Camunda Forms (Embedded)`
* External, the new future -> `Camunda Forms`

What do you think about that change?

**Comment by philippfromme** [comment]
Apparently, there is a reason not to promote linking:

> In production, this [embedding] is actually an advantage, because developers don't want form changes to appear adhoc in running processes, which is compromising production stability

cf. https://github.com/camunda/product-hub/issues/419#issue-1359878416

So I'm not sure what our strategy should be.

**Comment by nikku** [comment]
I've raised what @philippfromme and myself discussed via https://github.com/camunda/product-hub/issues/419#issuecomment-1695757302.

**Comment by nikku** [comment]
Will look into this POST release.
