### ISSUE TITLE
Property panel form validation not effective

### ISSUE THREAD

**Issue by wangshunshun** [bpmn-io/bpmn-js-properties-panel#951]
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/26266527/13fb3c73-4db1-497b-839f-0878670e7287)
When assigning an XML value obtained from the interface to bpmn, the message 'Element must have a unique id' is always reported. However, after modifying the value in the input box, the prompt is no longer present.
The code is as follows:
onMounted(() => {
  const customTranslateModle = {
    translate: ['value', customTranslate]
  }
  modeler.value = new Modeler({
    container: '#workFlowCanvas',
    propertiesPanel: {
      parent: '#js-properties-panel'
    },
    additionalModules: [propertiesPanelModule, propertiesProviderModule, magicPropertiesProviderModule, customTranslateModle],
    moddleExtensions: {
      camunda: CamundaBpmnModdle,
      task: taskjobModdleDescriptor
    }
  })

  id.value = route.query.id
  getDetails()
})
const getDetails = () => {
  processTemplateDetailAPI(route.query.id).then(res => {
    if (res.code == 200) {
      templateInfo = Object.assign({}, res.data)
      createNewDiagram()
    }
  })
}
const createNewDiagram = async () => {
  let diagramXML = ``
  if (templateInfo.bpmnStr) {
    diagramXML = templateInfo.bpmnStr
  }
  try {
    const result = await modeler.value.importXML(diagramXML)
    const { err } = result
    if (!err) {
      success()
    }
  } catch (err) {
    console.log(err.message, err.warnings);
  }
}

**Comment by nikku** [comment]
The message does exactly what it should do, or am I wrong?

If there is an ID duplication _then_ it shows an error. If you change the ID to be unique, _then_ the error vanishes.

**Comment by wangshunshun** [comment]
> 该消息完全按照其应有的功能执行，还是我错了？
> 
> 如果存在 ID 重复，_则会_显示错误。如果将 ID 更改为唯一，_则_错误就会消失。

The ID is the unique value. When I first entered the page, I reported an error with a duplicate ID. Then I casually added a number and deleted the prompt, which disappeared.

**Comment by nikku** [comment]
Unfortunately I cannot reproduce your issue. Or maybe we miss-understand each other.

**Comment by 52Tiantian** [comment]
I have also encountered the same problem. Have you solved it?

**Comment by barmac** [comment]
We are not going to fix issues with v0.x of this repository. Please upgrade to the latest, and if the issue is still present, comment.

**Comment by 52Tiantian** [comment]
> 我们不会修复此存储库 v0.x 中的问题。请升级到最新版本，如果问题仍然存在，请发表评论。

I have upgraded the version to 5. x, but this issue still exists. As long as the content is imported by the importXML method, it will trigger this problem, which looks like the update of the content has not been monitored

**Comment by barmac** [comment]
Can you please share a [codesandbox](https://codesandbox.io/) which reproduces the issue?

**Comment by GakkiMaou** [comment]
https://github.com/bpmn-io/bpmn-js-properties-panel/issues/682

**Comment by barmac** [comment]
Please clarify how this link helps.

**Comment by GakkiMaou** [comment]
![image](https://github.com/user-attachments/assets/27a28939-c6cb-4f23-b75b-5cb28f89a15d)

Do not use proxy objects.
