### ISSUE TITLE
STYLE CDN IS NOT WORKING: bpmn-js-properties-panel/v/1.3.0 effected css issue

### ISSUE THREAD

**Issue by shuhaib-aot** [bpmn-io/bpmn-js-properties-panel#961]
### Describe the Bug

 am currently utilizing "bpmn-js-properties-panel": "^1.3.0" in my project. However, it appears that the CSS links I had been relying on are no longer functional. Specifically, the following links are resulting in 404 errors:

```
Original: <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel/dist/assets/properties-panel.css">
Original: <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel/dist/assets/element-templates.css">
```
It has come to my attention that there have been updates to the CDN, but it seems that the existing version's CDNs have been affected. I would like to suggest that maintaining the availability of CDNs for existing versions is a best practice that could be considered for situations like this.
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/95394061/3544b48b-f226-4630-8ef0-16a2df021ad8)

## These links are directly to latest version
![image](https://github.com/bpmn-io/bpmn-js-properties-panel/assets/95394061/8a920be5-22b3-45d8-8146-8d6bbbf5347b)

**Comment by marstamm** [comment]
Hi @shuhaib-aot , when using the CDN without a version, it will fetch assets for the latest release. In the latest major release, we removed the CSS files (cf. [Changelog](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/CHANGELOG.md#500)).

Please change your CSS links to relate to the version of the properties panel you are using by adding a version tag to the link

```diff
- <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel/dist/assets/properties-panel.css">
- <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel/dist/assets/element-templates.css">
+ <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel@1/dist/assets/properties-panel.css">
+ <link rel="stylesheet" href="https://unpkg.com/bpmn-js-properties-panel@1/dist/assets/element-templates.css">
```
