### ISSUE TITLE
I can edit mapDecisionResult for businessRulesTask

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmn-js-properties-panel#98]
Otherwise I can't get the result from the decision back into the process.

**Comment by meyerdan** [comment]
This should be already possible.

**Comment by meyerdan** [comment]
![image](https://cloud.githubusercontent.com/assets/488063/11426857/282550c8-945f-11e5-8303-ca6a498aed1b.png)

**Comment by ingorichtsmeier** [comment]
Still missing in the latest build on my machine. What else do I have to clean up? I recently dropped the folder and unpack the zip-content.

![br-task-panel](https://cloud.githubusercontent.com/assets/7870843/11443227/a0f88ab2-951b-11e5-8152-4f4019c79d20.png)

**Comment by ingorichtsmeier** [comment]
Ah, you have to enter at least one character before the dropdown appears. Bad user experience at the first sight ...

**Comment by meyerdan** [comment]
you need to input something into the result variable
