### ISSUE TITLE
Redo does not work in FEEL input when undone till empty input

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-properties-panel#981]
### Describe the Bug

Given I type in the FEEL entry, when I press cmd+Z and cmd+Y, in FEEL input, redo stops to work as soon as I reach empty input with undo.

### Steps to Reproduce

1. Type in FEEL input
2. Undo until input is empty
3. Try to redo
4. Nothing happens

### Expected Behavior

Redo should work.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: Confirmed in v5.3.0-v5.5.0

**Comment by marstamm** [comment]
I can only reproduce this issue in Input/Output fields. Other FEEL enabled fields, such as Task type or Script Tasks FEEL expressions manage the undo stack correctly.
