### ISSUE TITLE
I can set the retry time cycle for jobs on multi instance loop characteristics

### ISSUE THREAD

**Issue by saig0** [bpmn-io/bpmn-js-properties-panel#99]
AT:
* I can set the retry time cycle for jobs on multi instance loop characteristics. See #28 
* Special behavior with asynchronous continuations: -- if neiter async before nor after are checked on multi instance loop characteristics (see #26), the retry time cycle input field is not shown

```xml
<serviceTask id="..">
  <multiInstanceLoopCharacteristics camunda:asyncBefore="true" camunda:asyncAfter="true">
    <extensionElements>
       <camunda:failedJobRetryTimeCycle>R5/PT5M</camunda:failedJobRetryTimeCycle>
    </extensionElements>  
  </multiInstanceLoopCharacteristics>
</serviceTask>
```

**Comment by meyerdan** [comment]
I have trouble putting this on master (failing testcases). Maybe I need to merge another branch first?

**Comment by meyerdan** [comment]
Hi Stefan: I wanted to talk about this on Friday: The code looks OK but when I merge it I have test failures. I do not have testfailures when I run the testsuite on the branch. There is nothing wrong with the code it just does not "fit" on master anymore. I wanted to look into it but then ran out of time. Could you please merge it yourself?

**Comment by shentschel** [comment]
Hi Daniel.

I merged the branch against the master but there where some changes.  So can you have a second look on the code?

Cheers,

Stefan
