### ISSUE TITLE
After installation, startup project error

### ISSUE THREAD

**Issue by daughterRui** [bpmn-io/bpmn-js-properties-panel#995]
### Describe the Bug

<img width="514" alt="mx_screencap_20231025_170149" src="https://github.com/bpmn-io/bpmn-js-properties-panel/assets/18068805/bae03a7d-5ef5-4237-ae56-51ad724459da">

bpmn-js-properties-panel  -> @bpmn-io/properties-panel -> feelers -> lezer-feel

Finally, it was reported incorrectly in lezer-feel ！！！

### Environment

- node: 14.17.1
- vue: 2.6.11

**Comment by barmac** [comment]
Please add the steps to reproduce. Also note that node@14 is not supported anymore.

**Comment by barmac** [comment]
Closing this as `invalid`. Feel free to comment when you are ready to provide more details.
